import { DayPlan, Phase } from '@/types';

export const roadmapData: DayPlan[] = [
  // =============================================
  // PHASE 1: FOUNDATION (Days 1-21)
  // =============================================
  {
    id: 1,
    phase: 'foundation',
    week: 1,
    title: 'Getting Started with Rust',
    goal: 'Install Rust toolchain, understand Cargo, and write your first program',
    targetSkills: ['Rust Installation', 'Cargo', 'Hello World', 'rustup'],
    lessons: [
      {
        id: 'day1-lesson1',
        title: 'Install Rust & Toolchain Setup',
        duration: 45,
        type: 'video',
        resource: { platform: 'udemy', url: 'https://www.udemy.com/course/ultimate-rust-crash-course/', title: 'Ultimate Rust Crash Course', section: 'Section 1: Getting Started' },
        description: 'Install rustup, configure your IDE, and understand the Rust ecosystem',
        objectives: ['Install rustup and Rust toolchain', 'Set up VS Code with rust-analyzer', 'Understand Rust editions'],
      },
      {
        id: 'day1-lesson2',
        title: 'The Rust Book: Getting Started',
        duration: 60,
        type: 'reading',
        resource: { platform: 'rustbook', url: 'https://doc.rust-lang.org/book/ch01-01-installation.html', title: 'Chapter 1: Getting Started' },
        description: 'Read the official introduction to Rust installation and Hello World',
        objectives: ['Understand rustc vs cargo', 'Create first project with cargo new', 'Understand Cargo.toml'],
      },
      {
        id: 'day1-lesson3',
        title: 'Cargo Deep Dive',
        duration: 60,
        type: 'coding',
        resource: { platform: 'docs', url: 'https://doc.rust-lang.org/cargo/', title: 'The Cargo Book' },
        description: 'Learn cargo commands: build, run, check, test, doc',
        objectives: ['Master cargo build/run/check', 'Understand debug vs release builds', 'Add dependencies to Cargo.toml'],
        codeExercise: {
          prompt: 'Create a new Cargo project that uses the `rand` crate to generate a random number between 1 and 100',
          starterCode: 'use rand::Rng;\n\nfn main() {\n    // TODO: Generate and print a random number\n}',
          hint: 'Add rand = "0.8" to Cargo.toml, then use rand::thread_rng().gen_range(1..=100)',
        },
      },
      {
        id: 'day1-lesson4',
        title: 'Rustlings: Intro Exercises',
        duration: 75,
        type: 'exercise',
        resource: { platform: 'github', url: 'https://github.com/rust-lang/rustlings', title: 'Rustlings' },
        description: 'Complete the intro and variables sections of Rustlings',
        objectives: ['Set up Rustlings locally', 'Complete intro1-intro2', 'Complete variables1-variables6'],
      },
    ],
    dailyChallenge: { title: 'Hello Rustacean', description: 'Create a Cargo project that prints your name, today\'s date, and a random motivational quote from an array', estimatedTime: 30 },
    reviewTopics: [],
    status: 'locked',
  },
  {
    id: 2,
    phase: 'foundation',
    week: 1,
    title: 'Variables, Mutability & Data Types',
    goal: 'Understand variable binding, mutability, shadowing, and scalar/compound types',
    targetSkills: ['Variables', 'Mutability', 'Shadowing', 'Data Types', 'Constants'],
    lessons: [
      {
        id: 'day2-lesson1',
        title: 'Variables & Mutability',
        duration: 50,
        type: 'video',
        resource: { platform: 'udemy', url: 'https://www.udemy.com/course/ultimate-rust-crash-course/', title: 'Ultimate Rust Crash Course', section: 'Section 2: Fundamentals' },
        description: 'Learn about let bindings, mut keyword, and constants',
        objectives: ['Understand immutability by default', 'Use mut for mutable variables', 'Differentiate const vs let'],
      },
      {
        id: 'day2-lesson2',
        title: 'The Rust Book: Variables & Data Types',
        duration: 60,
        type: 'reading',
        resource: { platform: 'rustbook', url: 'https://doc.rust-lang.org/book/ch03-01-variables-and-mutability.html', title: 'Chapter 3.1-3.2: Variables and Data Types' },
        description: 'Deep dive into Rust\'s type system fundamentals',
        objectives: ['Master scalar types: i32, f64, bool, char', 'Understand compound types: tuples, arrays', 'Learn type annotations'],
      },
      {
        id: 'day2-lesson3',
        title: 'Shadowing & Type Conversions',
        duration: 60,
        type: 'coding',
        resource: { platform: 'custom', url: 'https://play.rust-lang.org/', title: 'Rust Playground' },
        description: 'Practice variable shadowing and type casting',
        objectives: ['Use shadowing to change types', 'Convert between numeric types', 'Understand type inference'],
        codeExercise: {
          prompt: 'Create a temperature converter that converts Fahrenheit to Celsius. Use shadowing to first parse a string to f64, then calculate the result.',
          starterCode: 'fn main() {\n    let fahrenheit = "98.6";\n    // TODO: Shadow fahrenheit as f64, then convert to celsius\n    // Formula: (F - 32) * 5/9\n}',
          hint: 'Use fahrenheit.parse::<f64>().unwrap() to shadow the string as a number',
        },
      },
      {
        id: 'day2-lesson4',
        title: 'Rustlings: Primitive Types',
        duration: 70,
        type: 'exercise',
        resource: { platform: 'github', url: 'https://github.com/rust-lang/rustlings', title: 'Rustlings' },
        description: 'Complete primitive_types exercises',
        objectives: ['Work with tuples and arrays', 'Practice array slicing', 'Destructure tuples'],
      },
    ],
    dailyChallenge: { title: 'Type Explorer', description: 'Write a program that demonstrates all scalar types, creates a tuple of mixed types, destructures it, and prints each value with its type name using std::any::type_name', estimatedTime: 30 },
    reviewTopics: ['Cargo commands', 'Project structure'],
    status: 'locked',
  },
  {
    id: 3,
    phase: 'foundation',
    week: 1,
    title: 'Functions & Control Flow',
    goal: 'Master function definitions, parameters, return values, and control flow',
    targetSkills: ['Functions', 'Parameters', 'Return Values', 'if/else', 'Loops'],
    lessons: [
      {
        id: 'day3-lesson1',
        title: 'Functions in Rust',
        duration: 50,
        type: 'video',
        resource: { platform: 'udemy', url: 'https://www.udemy.com/course/ultimate-rust-crash-course/', title: 'Ultimate Rust Crash Course', section: 'Section 2: Functions' },
        description: 'Function syntax, parameters, return types, and expressions vs statements',
        objectives: ['Define functions with typed parameters', 'Understand expression-based returns', 'Use the return keyword vs implicit return'],
      },
      {
        id: 'day3-lesson2',
        title: 'The Rust Book: Functions & Control Flow',
        duration: 60,
        type: 'reading',
        resource: { platform: 'rustbook', url: 'https://doc.rust-lang.org/book/ch03-03-how-functions-work.html', title: 'Chapter 3.3-3.5: Functions and Control Flow' },
        description: 'Comprehensive reading on functions, if/else, and loops',
        objectives: ['Master if/else as expressions', 'Use loop, while, and for', 'Understand loop labels and break with values'],
      },
      {
        id: 'day3-lesson3',
        title: 'Control Flow Patterns',
        duration: 70,
        type: 'coding',
        resource: { platform: 'custom', url: 'https://play.rust-lang.org/', title: 'Rust Playground' },
        description: 'Practice complex control flow patterns',
        objectives: ['Nest loops with labels', 'Use for with ranges and iterators', 'Combine if let with option types'],
        codeExercise: {
          prompt: 'Write a function `fizzbuzz(n: u32)` that prints FizzBuzz from 1 to n. Then write a function that returns the nth Fibonacci number using a loop.',
          starterCode: 'fn fizzbuzz(n: u32) {\n    // TODO\n}\n\nfn fibonacci(n: u32) -> u64 {\n    // TODO\n}\n\nfn main() {\n    fizzbuzz(20);\n    println!("fib(10) = {}", fibonacci(10));\n}',
          hint: 'For fibonacci, use two variables and swap them in a loop',
        },
      },
      {
        id: 'day3-lesson4',
        title: 'Rustlings: Functions & If',
        duration: 60,
        type: 'exercise',
        resource: { platform: 'github', url: 'https://github.com/rust-lang/rustlings', title: 'Rustlings' },
        description: 'Complete functions and if exercises',
        objectives: ['Fix function signatures', 'Use if as expression', 'Practice return values'],
      },
    ],
    dailyChallenge: { title: 'Number Guessing Game', description: 'Build a simple number guessing game: generate a random number, loop to get guesses, give "too high/too low" hints, count attempts', estimatedTime: 45 },
    reviewTopics: ['Variables & mutability', 'Data types'],
    status: 'locked',
  },
  {
    id: 4,
    phase: 'foundation',
    week: 1,
    title: 'Strings & String Slices',
    goal: 'Understand String vs &str, UTF-8 encoding, and string manipulation',
    targetSkills: ['String', '&str', 'UTF-8', 'String Methods', 'Formatting'],
    lessons: [
      {
        id: 'day4-lesson1',
        title: 'Strings in Rust',
        duration: 55,
        type: 'video',
        resource: { platform: 'udemy', url: 'https://www.udemy.com/course/ultimate-rust-crash-course/', title: 'Ultimate Rust Crash Course', section: 'Section 3: Strings' },
        description: 'Learn the difference between String and &str',
        objectives: ['Understand heap-allocated String', 'Work with string slices &str', 'Convert between String and &str'],
      },
      {
        id: 'day4-lesson2',
        title: 'The Rust Book: Common Collections - Strings',
        duration: 60,
        type: 'reading',
        resource: { platform: 'rustbook', url: 'https://doc.rust-lang.org/book/ch08-02-strings.html', title: 'Chapter 8.2: Storing UTF-8 Encoded Text' },
        description: 'Deep dive into Rust\'s string handling',
        objectives: ['Understand UTF-8 encoding in Rust', 'Use push_str, format!, concatenation', 'Iterate over chars and bytes'],
      },
      {
        id: 'day4-lesson3',
        title: 'String Manipulation Practice',
        duration: 75,
        type: 'coding',
        resource: { platform: 'custom', url: 'https://play.rust-lang.org/', title: 'Rust Playground' },
        description: 'Build string processing utilities',
        objectives: ['Split, trim, and search strings', 'Use format! macro', 'Handle string indexing safely'],
        codeExercise: {
          prompt: 'Write functions: reverse_string, count_vowels, is_palindrome, and title_case. Each takes &str and returns appropriate types.',
          starterCode: 'fn reverse_string(s: &str) -> String {\n    // TODO\n}\n\nfn count_vowels(s: &str) -> usize {\n    // TODO\n}\n\nfn is_palindrome(s: &str) -> bool {\n    // TODO\n}\n\nfn title_case(s: &str) -> String {\n    // TODO\n}',
          hint: 'Use .chars() iterator for character-level operations',
        },
      },
      {
        id: 'day4-lesson4',
        title: 'Rustlings: Strings',
        duration: 50,
        type: 'exercise',
        resource: { platform: 'github', url: 'https://github.com/rust-lang/rustlings', title: 'Rustlings' },
        description: 'Complete strings exercises',
        objectives: ['Convert between String and &str', 'Use string methods', 'Handle string ownership'],
      },
    ],
    dailyChallenge: { title: 'Text Analyzer', description: 'Build a text analyzer that counts words, sentences, paragraphs, and finds the most common word in a given text', estimatedTime: 40 },
    reviewTopics: ['Functions', 'Control flow', 'Loops'],
    status: 'locked',
  },
  {
    id: 5,
    phase: 'foundation',
    week: 1,
    title: 'Collections: Vec & HashMap',
    goal: 'Master vectors, hash maps, and common collection patterns',
    targetSkills: ['Vec', 'HashMap', 'Iterators Basics', 'Collection Methods'],
    lessons: [
      {
        id: 'day5-lesson1',
        title: 'Vectors and HashMaps',
        duration: 50,
        type: 'video',
        resource: { platform: 'udemy', url: 'https://www.udemy.com/course/ultimate-rust-crash-course/', title: 'Ultimate Rust Crash Course', section: 'Section 3: Collections' },
        description: 'Learn Vec<T> and HashMap<K, V> fundamentals',
        objectives: ['Create and modify vectors', 'Use HashMap for key-value storage', 'Iterate over collections'],
      },
      {
        id: 'day5-lesson2',
        title: 'The Rust Book: Common Collections',
        duration: 60,
        type: 'reading',
        resource: { platform: 'rustbook', url: 'https://doc.rust-lang.org/book/ch08-01-vectors.html', title: 'Chapter 8.1 & 8.3: Vectors and Hash Maps' },
        description: 'Comprehensive guide to Rust collections',
        objectives: ['Use vec! macro', 'Access elements safely with get()', 'Use entry API for HashMaps'],
      },
      {
        id: 'day5-lesson3',
        title: 'Collection Algorithms',
        duration: 70,
        type: 'coding',
        resource: { platform: 'custom', url: 'https://play.rust-lang.org/', title: 'Rust Playground' },
        description: 'Implement common algorithms using collections',
        objectives: ['Sort and filter vectors', 'Group data with HashMaps', 'Use iterator methods'],
        codeExercise: {
          prompt: 'Create a student grade tracker: store student names and their grades in a HashMap, implement functions for average grade, highest scorer, and students above a threshold.',
          starterCode: 'use std::collections::HashMap;\n\nfn main() {\n    let mut grades: HashMap<String, Vec<f64>> = HashMap::new();\n    // TODO: Add students and grades\n    // TODO: Calculate averages\n    // TODO: Find highest scorer\n}',
          hint: 'Use entry().or_insert_with(Vec::new) for adding grades',
        },
      },
      {
        id: 'day5-lesson4',
        title: 'Rustlings: Collections',
        duration: 60,
        type: 'exercise',
        resource: { platform: 'github', url: 'https://github.com/rust-lang/rustlings', title: 'Rustlings' },
        description: 'Complete vec and hashmap exercises',
        objectives: ['Manipulate vectors', 'Use HashMap entry API', 'Iterate and collect'],
      },
    ],
    dailyChallenge: { title: 'Word Frequency Counter', description: 'Build a program that reads text, counts word frequency using HashMap, and displays the top 10 most common words sorted by frequency', estimatedTime: 35 },
    reviewTopics: ['Strings', 'String slices', 'UTF-8'],
    status: 'locked',
  },
  {
    id: 6,
    phase: 'foundation',
    week: 1,
    title: 'Expressions, Statements & Comments',
    goal: 'Understand Rust\'s expression-oriented nature and documentation',
    targetSkills: ['Expressions', 'Statements', 'Block Expressions', 'Doc Comments', 'Attributes'],
    lessons: [
      {
        id: 'day6-lesson1',
        title: 'Expressions vs Statements',
        duration: 45,
        type: 'video',
        resource: { platform: 'udemy', url: 'https://www.udemy.com/course/ultimate-rust-crash-course/', title: 'Ultimate Rust Crash Course', section: 'Section 2: Expressions' },
        description: 'Why Rust is expression-oriented and how to use it',
        objectives: ['Distinguish expressions from statements', 'Use blocks as expressions', 'Leverage expression-based returns'],
      },
      {
        id: 'day6-lesson2',
        title: 'The Rust Book: Understanding Ownership Preview',
        duration: 60,
        type: 'reading',
        resource: { platform: 'rustbook', url: 'https://doc.rust-lang.org/book/ch04-00-understanding-ownership.html', title: 'Chapter 4: Understanding Ownership (Preview)' },
        description: 'Preview ownership concepts before deep dive next week',
        objectives: ['Understand stack vs heap', 'Preview the ownership concept', 'See why Rust needs ownership'],
      },
      {
        id: 'day6-lesson3',
        title: 'Documentation & Testing Intro',
        duration: 75,
        type: 'coding',
        resource: { platform: 'docs', url: 'https://doc.rust-lang.org/rustdoc/', title: 'The rustdoc Book' },
        description: 'Write doc comments and basic tests',
        objectives: ['Write /// doc comments', 'Generate documentation with cargo doc', 'Write basic #[test] functions'],
        codeExercise: {
          prompt: 'Create a small math library with functions add, subtract, multiply, divide. Add doc comments with examples to each function, and write unit tests.',
          starterCode: '/// Adds two numbers together.\n///\n/// # Examples\n/// ```\n/// assert_eq!(add(2, 3), 5);\n/// ```\npub fn add(a: i32, b: i32) -> i32 {\n    // TODO\n}\n\n// TODO: More functions with docs and tests\n\n#[cfg(test)]\nmod tests {\n    use super::*;\n    // TODO: Write tests\n}',
          hint: 'Use #[test] attribute and assert_eq! macro',
        },
      },
      {
        id: 'day6-lesson4',
        title: 'Week 1 Review Exercises',
        duration: 60,
        type: 'quiz',
        resource: { platform: 'custom', url: 'https://play.rust-lang.org/', title: 'Self-Assessment Quiz' },
        description: 'Review all Week 1 concepts with practical exercises',
        objectives: ['Review variables and types', 'Review functions and control flow', 'Review strings and collections'],
      },
    ],
    dailyChallenge: { title: 'Mini Library', description: 'Create a documented mini-library with at least 5 utility functions, full doc comments, and comprehensive unit tests', estimatedTime: 45 },
    reviewTopics: ['Collections', 'Vec methods', 'HashMap'],
    status: 'locked',
  },
  {
    id: 7,
    phase: 'foundation',
    week: 1,
    title: 'Week 1 Project: CLI Calculator',
    goal: 'Build a command-line calculator combining all Week 1 concepts',
    targetSkills: ['CLI Apps', 'Input Parsing', 'Error Messages', 'Project Structure'],
    lessons: [
      {
        id: 'day7-lesson1',
        title: 'CLI Application Patterns',
        duration: 50,
        type: 'video',
        resource: { platform: 'udemy', url: 'https://www.udemy.com/course/ultimate-rust-crash-course/', title: 'Ultimate Rust Crash Course', section: 'Section 3: Exercise' },
        description: 'Learn patterns for building CLI applications in Rust',
        objectives: ['Read user input with std::io', 'Parse strings to numbers', 'Structure a multi-file project'],
      },
      {
        id: 'day7-lesson2',
        title: 'Reading User Input',
        duration: 45,
        type: 'reading',
        resource: { platform: 'rustbook', url: 'https://doc.rust-lang.org/book/ch02-00-guessing-game-tutorial.html', title: 'Chapter 2: Programming a Guessing Game' },
        description: 'Follow the guessing game tutorial for input handling',
        objectives: ['Use std::io::stdin()', 'Handle parse errors', 'Implement game loop'],
      },
      {
        id: 'day7-lesson3',
        title: 'Build: CLI Calculator',
        duration: 120,
        type: 'project',
        resource: { platform: 'custom', url: 'https://play.rust-lang.org/', title: 'Project' },
        description: 'Build a full-featured CLI calculator',
        objectives: ['Support +, -, *, / operations', 'Handle invalid input gracefully', 'Support expression history', 'Add help command'],
        codeExercise: {
          prompt: 'Build a REPL calculator that supports basic math operations, parentheses, and maintains a history of calculations.',
          starterCode: 'use std::io;\n\nfn main() {\n    println!("Rust Calculator v1.0");\n    println!("Type \\"help\\" for commands, \\"quit\\" to exit");\n    let mut history: Vec<String> = Vec::new();\n    loop {\n        // TODO: Read input, parse, calculate, store history\n    }\n}',
          hint: 'Split the input by spaces, match the operator, and handle errors with match',
        },
      },
      {
        id: 'day7-lesson4',
        title: 'Code Review & Refactoring',
        duration: 25,
        type: 'exercise',
        resource: { platform: 'custom', url: 'https://play.rust-lang.org/', title: 'Self Review' },
        description: 'Review and improve your calculator code',
        objectives: ['Add documentation', 'Refactor repeated code', 'Add edge case handling'],
      },
    ],
    dailyChallenge: { title: 'Calculator Extension', description: 'Add support for storing variables (let x = 5), using them in calculations, and a "history" command that shows past results', estimatedTime: 45 },
    reviewTopics: ['All Week 1 topics', 'String parsing', 'Collections'],
    status: 'locked',
  },
  // Week 2: Ownership, Borrowing, References
  {
    id: 8,
    phase: 'foundation',
    week: 2,
    title: 'Ownership Fundamentals',
    goal: 'Understand Rust\'s ownership system: move semantics, Copy trait, and drop',
    targetSkills: ['Ownership', 'Move Semantics', 'Copy Trait', 'Drop', 'Stack vs Heap'],
    lessons: [
      {
        id: 'day8-lesson1',
        title: 'Understanding Ownership',
        duration: 60,
        type: 'video',
        resource: { platform: 'udemy', url: 'https://www.udemy.com/course/ultimate-rust-crash-course/', title: 'Ultimate Rust Crash Course', section: 'Section 4: Ownership' },
        description: 'The core concept that makes Rust unique',
        objectives: ['Understand ownership rules', 'See how moves work', 'Understand when values are dropped'],
      },
      {
        id: 'day8-lesson2',
        title: 'The Rust Book: What is Ownership?',
        duration: 60,
        type: 'reading',
        resource: { platform: 'rustbook', url: 'https://doc.rust-lang.org/book/ch04-01-what-is-ownership.html', title: 'Chapter 4.1: What is Ownership?' },
        description: 'The definitive guide to Rust ownership',
        objectives: ['Master the three ownership rules', 'Understand String memory layout', 'Visualize stack and heap'],
      },
      {
        id: 'day8-lesson3',
        title: 'Ownership in Practice',
        duration: 70,
        type: 'coding',
        resource: { platform: 'custom', url: 'https://play.rust-lang.org/', title: 'Rust Playground' },
        description: 'Hands-on ownership exercises',
        objectives: ['Fix ownership errors', 'Use clone when needed', 'Understand Copy vs Move'],
        codeExercise: {
          prompt: 'Fix the following code so it compiles. Understand WHY each error occurs and choose the best fix (move, clone, or restructure).',
          starterCode: 'fn main() {\n    let s1 = String::from("hello");\n    let s2 = s1;\n    println!("{}", s1); // Error!\n    \n    let v = vec![1, 2, 3];\n    let v2 = v;\n    println!("{:?}", v); // Error!\n    \n    let name = String::from("Rust");\n    greet(name);\n    println!("Name is {}", name); // Error!\n}\n\nfn greet(name: String) {\n    println!("Hello, {}!", name);\n}',
          hint: 'Consider using .clone() or changing greet to take &str instead',
        },
      },
      {
        id: 'day8-lesson4',
        title: 'Rustlings: Move Semantics',
        duration: 50,
        type: 'exercise',
        resource: { platform: 'github', url: 'https://github.com/rust-lang/rustlings', title: 'Rustlings' },
        description: 'Complete move_semantics exercises',
        objectives: ['Fix move errors', 'Understand when cloning is necessary', 'Return ownership from functions'],
      },
    ],
    dailyChallenge: { title: 'Ownership Puzzle', description: 'Create a program that demonstrates all three ownership rules with real-world analogies (book lending, car keys, etc.)', estimatedTime: 30 },
    reviewTopics: ['Stack vs Heap', 'String memory layout'],
    status: 'locked',
  },
  {
    id: 9,
    phase: 'foundation',
    week: 2,
    title: 'References & Borrowing',
    goal: 'Master immutable and mutable references, borrowing rules',
    targetSkills: ['References', 'Borrowing', '&T', '&mut T', 'Borrow Rules'],
    lessons: [
      {
        id: 'day9-lesson1',
        title: 'References and Borrowing',
        duration: 55,
        type: 'video',
        resource: { platform: 'udemy', url: 'https://www.udemy.com/course/ultimate-rust-crash-course/', title: 'Ultimate Rust Crash Course', section: 'Section 4: References' },
        description: 'Learn to borrow values without taking ownership',
        objectives: ['Create immutable references', 'Create mutable references', 'Understand the borrowing rules'],
      },
      {
        id: 'day9-lesson2',
        title: 'The Rust Book: References and Borrowing',
        duration: 60,
        type: 'reading',
        resource: { platform: 'rustbook', url: 'https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html', title: 'Chapter 4.2: References and Borrowing' },
        description: 'Deep understanding of Rust\'s reference system',
        objectives: ['No two mutable references rule', 'Mixing mutable and immutable references', 'Dangling references prevention'],
      },
      {
        id: 'day9-lesson3',
        title: 'Borrowing Patterns',
        duration: 75,
        type: 'coding',
        resource: { platform: 'custom', url: 'https://play.rust-lang.org/', title: 'Rust Playground' },
        description: 'Practice real-world borrowing patterns',
        objectives: ['Pass references to functions', 'Return references safely', 'Understand NLL (Non-Lexical Lifetimes)'],
        codeExercise: {
          prompt: 'Write a function `longest_word` that takes a &str reference and returns a &str of the longest word. Then write `capitalize_first` that takes &mut String and capitalizes the first letter.',
          starterCode: 'fn longest_word(s: &str) -> &str {\n    // TODO: Find and return the longest word\n}\n\nfn capitalize_first(s: &mut String) {\n    // TODO: Capitalize the first character in-place\n}\n\nfn main() {\n    let text = "the quick brown fox";\n    println!("Longest: {}", longest_word(text));\n    let mut name = String::from("rust");\n    capitalize_first(&mut name);\n    println!("Capitalized: {}", name);\n}',
          hint: 'Use split_whitespace() and max_by_key(|w| w.len())',
        },
      },
      {
        id: 'day9-lesson4',
        title: 'Rustlings: References',
        duration: 50,
        type: 'exercise',
        resource: { platform: 'github', url: 'https://github.com/rust-lang/rustlings', title: 'Rustlings' },
        description: 'Complete borrowing exercises',
        objectives: ['Fix borrowing violations', 'Use references correctly', 'Understand lifetime basics'],
      },
    ],
    dailyChallenge: { title: 'Reference Tracker', description: 'Build a simple database struct that stores records and provides methods using &self and &mut self appropriately', estimatedTime: 40 },
    reviewTopics: ['Ownership rules', 'Move semantics', 'Clone'],
    status: 'locked',
  },
  {
    id: 10,
    phase: 'foundation',
    week: 2,
    title: 'Slices',
    goal: 'Master string slices and array slices for efficient data access',
    targetSkills: ['String Slices', 'Array Slices', '&[T]', 'Range Syntax', 'Slice Methods'],
    lessons: [
      {
        id: 'day10-lesson1',
        title: 'The Slice Type',
        duration: 50,
        type: 'video',
        resource: { platform: 'udemy', url: 'https://www.udemy.com/course/ultimate-rust-crash-course/', title: 'Ultimate Rust Crash Course', section: 'Section 4: Slices' },
        description: 'Understand slices as views into contiguous sequences',
        objectives: ['Create string slices', 'Create array/vector slices', 'Use slice as function parameters'],
      },
      {
        id: 'day10-lesson2',
        title: 'The Rust Book: The Slice Type',
        duration: 60,
        type: 'reading',
        resource: { platform: 'rustbook', url: 'https://doc.rust-lang.org/book/ch04-03-slices.html', title: 'Chapter 4.3: The Slice Type' },
        description: 'Complete understanding of slice types',
        objectives: ['Understand &str as a string slice', 'Use range syntax for slicing', 'Write functions that accept slices'],
      },
      {
        id: 'day10-lesson3',
        title: 'Working with Slices',
        duration: 75,
        type: 'coding',
        resource: { platform: 'custom', url: 'https://play.rust-lang.org/', title: 'Rust Playground' },
        description: 'Build utility functions using slices',
        objectives: ['Find elements in slices', 'Window and chunk iteration', 'Implement search algorithms on slices'],
        codeExercise: {
          prompt: 'Implement `first_word`, `find_substring`, and `split_at_char` functions that work with string slices. Also implement `sum_slice` and `max_slice` for &[i32].',
          starterCode: 'fn first_word(s: &str) -> &str {\n    // TODO: Return the first word\n}\n\nfn sum_slice(nums: &[i32]) -> i32 {\n    // TODO\n}\n\nfn max_slice(nums: &[i32]) -> Option<&i32> {\n    // TODO\n}',
          hint: 'Use .find() for finding character positions, .iter().sum() for summing',
        },
      },
      {
        id: 'day10-lesson4',
        title: 'Ownership & Borrowing Review',
        duration: 55,
        type: 'quiz',
        resource: { platform: 'custom', url: 'https://play.rust-lang.org/', title: 'Practice Quiz' },
        description: 'Comprehensive quiz on ownership, references, and slices',
        objectives: ['Identify ownership issues', 'Fix borrowing errors', 'Choose between &, &mut, and owned'],
      },
    ],
    dailyChallenge: { title: 'CSV Parser', description: 'Build a simple CSV parser using slices: parse a CSV string, extract columns by index, and filter rows by a condition', estimatedTime: 45 },
    reviewTopics: ['References', 'Borrowing rules', 'Mutable references'],
    status: 'locked',
  },
  // Days 11-14: Continue ownership deep dive
  ...[11, 12, 13, 14].map((id): DayPlan => ({
    id,
    phase: 'foundation',
    week: 2,
    title: [
      'Ownership with Structs',
      'Lifetime Annotations Preview',
      'Ownership Patterns & Anti-patterns',
      'Week 2 Project: Text Processor',
    ][id - 11],
    goal: [
      'Understand how ownership works with struct fields',
      'Preview lifetime annotations for function signatures',
      'Learn common ownership patterns and when to clone vs borrow',
      'Build a text processor combining ownership, borrowing, and slices',
    ][id - 11],
    targetSkills: [
      ['Struct Ownership', 'Field Borrowing', 'Methods'],
      ['Lifetime Basics', 'Function Signatures', 'Struct Lifetimes'],
      ['Cow', 'ToOwned', 'AsRef', 'Deref'],
      ['Text Processing', 'File I/O', 'Error Handling Basics'],
    ][id - 11],
    lessons: [],
    dailyChallenge: {
      title: ['Struct Builder', 'Lifetime Explorer', 'Pattern Catalog', 'Text Processor'][id - 11],
      description: [
        'Create a User struct with owned and borrowed fields, implement Display',
        'Write functions with explicit lifetime annotations and test them',
        'Document 5 common ownership patterns with code examples',
        'Build a text processor that reads a file, transforms content, and writes output',
      ][id - 11],
      estimatedTime: 40,
    },
    reviewTopics: id === 11 ? ['Slices', 'Borrowing'] : ['Previous day topics'],
    status: 'locked',
  })),
  // Week 3: Structs, Enums, Pattern Matching
  ...[15, 16, 17, 18, 19, 20, 21].map((id): DayPlan => ({
    id,
    phase: 'foundation',
    week: 3,
    title: [
      'Structs & Methods',
      'Enums & Variants',
      'Pattern Matching with match',
      'Option<T> Deep Dive',
      'Result<T, E> & Error Handling Basics',
      'if let, while let & Nested Patterns',
      'Week 3 Project: Task Manager CLI',
    ][id - 15],
    goal: [
      'Define structs, implement methods and associated functions',
      'Create enums with data variants, understand algebraic data types',
      'Master the match expression and exhaustive pattern matching',
      'Use Option for nullable values safely',
      'Handle errors with Result, the ? operator, and custom error types',
      'Use pattern matching shortcuts and complex patterns',
      'Build a full CLI task manager using structs, enums, and pattern matching',
    ][id - 15],
    targetSkills: [
      ['Structs', 'impl Blocks', 'Methods', 'Associated Functions'],
      ['Enums', 'Variants', 'Algebraic Types', 'impl for Enums'],
      ['match', 'Patterns', 'Guards', 'Exhaustiveness'],
      ['Option<T>', 'Some/None', 'unwrap_or', 'map/and_then'],
      ['Result<T,E>', '? Operator', 'Custom Errors', 'Error Propagation'],
      ['if let', 'while let', 'Destructuring', 'Nested Patterns'],
      ['CLI Project', 'File Persistence', 'Serialization'],
    ][id - 15],
    lessons: [],
    dailyChallenge: {
      title: ['Shape Calculator', 'Card Deck', 'Expression Parser', 'Safe Division', 'Config Loader', 'Pattern Master', 'Task Manager'][id - 15],
      description: [
        'Create Shape enum with Circle, Rectangle, Triangle variants and calculate area/perimeter',
        'Model a card deck with Suit and Rank enums, implement shuffle and deal',
        'Parse and evaluate simple math expressions using match',
        'Build a calculator that uses Option and handles division by zero gracefully',
        'Load configuration from a file using Result, provide defaults for missing values',
        'Create a nested JSON-like data structure and pattern-match to extract values',
        'Build a persistent CLI task manager with add, complete, delete, list, and filter commands',
      ][id - 15],
      estimatedTime: 45,
    },
    reviewTopics: id === 15 ? ['Ownership', 'References', 'Slices'] : ['Previous day topics'],
    status: 'locked',
  })),

  // =============================================
  // PHASE 2: INTERMEDIATE (Days 22-50)
  // =============================================
  ...[22, 23, 24, 25, 26, 27, 28, 29, 30].map((id): DayPlan => ({
    id,
    phase: 'intermediate',
    week: Math.ceil(id / 7),
    title: [
      'Traits: Defining Shared Behavior',
      'Trait Implementations & Default Methods',
      'Generics: Functions & Structs',
      'Generic Trait Bounds',
      'Lifetimes in Depth',
      'Closures: Anonymous Functions',
      'Iterators & Iterator Trait',
      'Iterator Adaptors & Collecting',
      'Combining Closures, Iterators & Generics',
    ][id - 22],
    goal: [
      'Define traits and understand them as interfaces for shared behavior',
      'Implement traits for custom types and use default method implementations',
      'Write generic functions and structs that work with any type',
      'Use trait bounds to constrain generic types',
      'Master lifetime annotations in functions, structs, and impl blocks',
      'Create and use closures, understand capture modes (Fn, FnMut, FnOnce)',
      'Implement the Iterator trait and understand lazy evaluation',
      'Master map, filter, fold, chain, zip and other iterator adaptors',
      'Build complex data pipelines combining all intermediate concepts',
    ][id - 22],
    targetSkills: [
      ['Traits', 'trait keyword', 'impl Trait'],
      ['Default Methods', 'Supertraits', 'Derive'],
      ['Generics', 'Type Parameters', 'Monomorphization'],
      ['Trait Bounds', 'where Clauses', 'impl Trait Syntax'],
      ['Lifetimes', "'a Syntax", 'Lifetime Elision'],
      ['Closures', 'Fn/FnMut/FnOnce', 'Capture'],
      ['Iterator', 'next()', 'IntoIterator'],
      ['map', 'filter', 'fold', 'collect'],
      ['Data Pipelines', 'Functional Rust', 'Method Chaining'],
    ][id - 22],
    lessons: id <= 24 ? [
      {
        id: `day${id}-lesson1`,
        title: `${['Traits Introduction', 'Advanced Traits', 'Generics Fundamentals'][id - 22]}`,
        duration: 55,
        type: 'video' as const,
        resource: { platform: 'udemy' as const, url: 'https://www.udemy.com/course/ultimate-rust-2/', title: 'Ultimate Rust 2: Intermediate Concepts', section: `Section ${id - 20}` },
        description: `Learn ${['trait definitions and basic implementations', 'default methods and trait inheritance', 'generic type parameters'][id - 22]}`,
        objectives: [
          `Understand ${['trait syntax', 'default methods', 'generic syntax'][id - 22]}`,
          `Practice ${['implementing traits', 'trait inheritance', 'generic functions'][id - 22]}`,
        ],
      },
      {
        id: `day${id}-lesson2`,
        title: 'Rust Book Deep Dive',
        duration: 60,
        type: 'reading' as const,
        resource: { platform: 'rustbook' as const, url: `https://doc.rust-lang.org/book/ch10-0${id - 21}-${['traits', 'traits', 'generics'][id - 22]}.html`, title: `Chapter 10: Generic Types, Traits, and Lifetimes` },
        description: 'Read the official documentation on this topic',
        objectives: ['Understand the theory', 'See practical examples'],
      },
      {
        id: `day${id}-lesson3`,
        title: 'Hands-on Coding',
        duration: 75,
        type: 'coding' as const,
        resource: { platform: 'custom' as const, url: 'https://play.rust-lang.org/', title: 'Rust Playground' },
        description: 'Practice with coding exercises',
        objectives: ['Apply concepts to real problems', 'Build small projects'],
        codeExercise: {
          prompt: [
            'Define a Shape trait with area() and perimeter() methods. Implement it for Circle, Rectangle, and Triangle structs.',
            'Create a Printable trait with a default method. Create a Loggable supertrait. Implement both for a LogEntry struct.',
            'Write a generic function find_largest<T: PartialOrd>(list: &[T]) -> &T that works for any comparable type.',
          ][id - 22],
          starterCode: [
            'trait Shape {\n    fn area(&self) -> f64;\n    fn perimeter(&self) -> f64;\n}\n\nstruct Circle { radius: f64 }\nstruct Rectangle { width: f64, height: f64 }\n// TODO: Implement Shape for each',
            'trait Printable {\n    fn print(&self);\n    fn print_with_prefix(&self, prefix: &str) {\n        print!("{}: ", prefix);\n        self.print();\n    }\n}\n// TODO: Create Loggable supertrait and LogEntry struct',
            'fn find_largest<T>(list: &[T]) -> &T {\n    // TODO: Implement generically\n}\n// Test with Vec<i32> and Vec<String>',
          ][id - 22],
          hint: ['Use std::f64::consts::PI for circle', 'Supertraits: trait Loggable: Printable + Display', 'Add PartialOrd bound: T: PartialOrd'][id - 22],
        },
      },
      {
        id: `day${id}-lesson4`,
        title: 'Rustlings Exercises',
        duration: 50,
        type: 'exercise' as const,
        resource: { platform: 'github' as const, url: 'https://github.com/rust-lang/rustlings', title: 'Rustlings' },
        description: `Complete ${['traits', 'traits', 'generics'][id - 22]} exercises`,
        objectives: ['Reinforce understanding', 'Practice edge cases'],
      },
    ] : [],
    dailyChallenge: {
      title: ['Trait Zoo', 'Plugin System', 'Generic Container', 'Bounded Queue', 'Lifetime Puzzle', 'Closure Calculator', 'Custom Range Iterator', 'Data Pipeline', 'Functional Toolkit'][id - 22],
      description: [
        'Create a zoo simulation with Animal trait, multiple species implementing it, and a function that accepts any Animal',
        'Build a simple plugin system using traits with default implementations',
        'Create a generic Stack<T> with push, pop, peek, is_empty methods',
        'Build a BoundedQueue<T: Display + Clone> with max capacity',
        'Write functions that return references with proper lifetime annotations',
        'Build a calculator that uses closures for operations stored in a HashMap',
        'Implement Iterator for a custom Fibonacci struct',
        'Process a list of sales records: filter, map, group, and aggregate using iterator chains',
        'Build a utility library that combines generics, traits, closures, and iterators',
      ][id - 22],
      estimatedTime: 40,
    },
    reviewTopics: id === 22 ? ['Structs', 'Enums', 'Pattern Matching'] : ['Previous day concepts'],
    status: 'locked',
  })),
  // Days 31-50: Rest of intermediate
  ...[...Array(20)].map((_, i): DayPlan => {
    const id = 31 + i;
    const topics = [
      'Advanced Iterator Patterns', 'Custom Error Types', 'Error Handling Strategies',
      'The From & Into Traits', 'Modules & Visibility', 'Crate Structure & Workspaces',
      'Using External Crates', 'Serde Serialization', 'File I/O Patterns',
      'Testing Fundamentals', 'Integration Testing', 'Documentation & Rustdoc',
      'Cargo Features & Profiles', 'Macros: macro_rules!', 'Procedural Macro Overview',
      'Smart String Patterns', 'Type Aliases & Newtype', 'Intermediate Review Day 1',
      'Intermediate Review Day 2', 'Intermediate Project: CLI Tool',
    ];
    return {
      id,
      phase: 'intermediate',
      week: Math.ceil(id / 7),
      title: topics[i],
      goal: `Master ${topics[i].toLowerCase()} concepts and apply them in practice`,
      targetSkills: [topics[i], 'Rust Intermediate'],
      lessons: [],
      dailyChallenge: { title: topics[i], description: `Complete exercises and build a mini-project related to ${topics[i].toLowerCase()}`, estimatedTime: 40 },
      reviewTopics: [],
      status: 'locked',
    };
  }),

  // =============================================
  // PHASE 3: ADVANCED (Days 51-75)
  // =============================================
  ...[...Array(25)].map((_, i): DayPlan => {
    const id = 51 + i;
    const topics = [
      'Box<T> & Heap Allocation', 'Rc<T> & Reference Counting', 'RefCell<T> & Interior Mutability',
      'Arc<T> & Thread-Safe Sharing', 'Cow<T> & Clone-on-Write', 'Smart Pointer Patterns',
      'Threads & spawn', 'Message Passing with Channels', 'Shared State & Mutex',
      'Send & Sync Traits', 'Thread Pool Patterns', 'Async/Await Fundamentals',
      'Futures & Tokio Runtime', 'Async I/O & Networking', 'Async Patterns & Error Handling',
      'Unsafe Rust Fundamentals', 'Raw Pointers & FFI', 'Unsafe Abstractions',
      'Memory Layout & Alignment', 'Performance Profiling', 'Benchmarking with Criterion',
      'Zero-Cost Abstractions', 'Advanced Type System Tricks', 'Advanced Review',
      'Advanced Project: Concurrent Web Scraper',
    ];
    return {
      id,
      phase: 'advanced',
      week: Math.ceil(id / 7),
      title: topics[i],
      goal: `Master ${topics[i].toLowerCase()} for systems-level Rust programming`,
      targetSkills: [topics[i], 'Systems Programming'],
      lessons: [],
      dailyChallenge: { title: topics[i], description: `Implement and practice ${topics[i].toLowerCase()} concepts`, estimatedTime: 45 },
      reviewTopics: [],
      status: 'locked',
    };
  }),

  // =============================================
  // PHASE 4: EXAM PREP (Days 76-95)
  // =============================================
  ...[...Array(20)].map((_, i): DayPlan => {
    const id = 76 + i;
    const topics = [
      'Ownership & Borrowing Review', 'Type System Review', 'Traits & Generics Review',
      'Lifetime Review', 'Error Handling Review', 'Collections & Iterators Review',
      'Concurrency Review', 'Async Rust Review', 'Smart Pointers Review',
      'Unsafe Rust Review', 'Modules & Crates Review', 'Testing Review',
      'Macros Review', 'Memory Management Review', 'Performance Review',
      'Full Mock Exam 1', 'Full Mock Exam 2', 'Full Mock Exam 3',
      'Weak Areas Remediation', 'Exam Day Preparation',
    ];
    return {
      id,
      phase: 'exam-prep',
      week: Math.ceil(id / 7),
      title: topics[i],
      goal: id <= 90 ? `Deep review of ${topics[i].replace(' Review', '').toLowerCase()} for certification` : id <= 93 ? 'Complete a full timed mock exam under exam conditions' : 'Final preparation and confidence building',
      targetSkills: [topics[i], 'Certification'],
      lessons: [],
      dailyChallenge: { title: topics[i], description: id <= 90 ? `Create a comprehensive cheat sheet for ${topics[i].replace(' Review', '').toLowerCase()}` : 'Complete timed practice under exam conditions', estimatedTime: 45 },
      reviewTopics: [],
      status: 'locked',
    };
  }),

  // =============================================
  // PHASE 5: JOB HUNT (Days 96-110)
  // =============================================
  ...[...Array(15)].map((_, i): DayPlan => {
    const id = 96 + i;
    const topics = [
      'Resume Update with Rust Cert', 'Portfolio Website Setup', 'GitHub Profile Polish',
      'Open Source Contribution', 'Rust Project Showcase', 'LinkedIn Optimization',
      'Job Board Strategy', 'Apply: Web3 Companies', 'Apply: Systems Companies',
      'Apply: Fintech Companies', 'Apply: Infrastructure Companies', 'Apply: Startup Companies',
      'Networking & Community', 'Follow-up Strategy', 'Job Hunt Review',
    ];
    return {
      id,
      phase: 'job-hunt',
      week: Math.ceil(id / 7),
      title: topics[i],
      goal: `${topics[i]} — build your professional presence and apply strategically`,
      targetSkills: [topics[i], 'Career Development'],
      lessons: [],
      dailyChallenge: { title: topics[i], description: `Complete today's job hunt tasks focused on ${topics[i].toLowerCase()}`, estimatedTime: 45 },
      reviewTopics: [],
      status: 'locked',
    };
  }),

  // =============================================
  // PHASE 6: INTERVIEW PREP (Days 111-120)
  // =============================================
  ...[...Array(10)].map((_, i): DayPlan => {
    const id = 111 + i;
    const topics = [
      'Rust Technical Questions', 'Ownership & Lifetimes Interview Q&A', 'Concurrency Interview Questions',
      'System Design: Rust Services', 'System Design: Distributed Systems', 'Live Coding Practice',
      'Behavioral Interview Prep', 'Mock Interview 1', 'Mock Interview 2',
      'Negotiation & Final Prep',
    ];
    return {
      id,
      phase: 'interview-prep',
      week: Math.ceil(id / 7),
      title: topics[i],
      goal: `${topics[i]} — prepare to ace your Rust developer interviews`,
      targetSkills: [topics[i], 'Interview Skills'],
      lessons: [],
      dailyChallenge: { title: topics[i], description: `Practice ${topics[i].toLowerCase()} scenarios and prepare responses`, estimatedTime: 45 },
      reviewTopics: [],
      status: 'locked',
    };
  }),
];

export function getDaysByPhase(phase: Phase): DayPlan[] {
  return roadmapData.filter((d) => d.phase === phase);
}

export function getPhaseInfo(phase: Phase): {
  name: string;
  color: string;
  days: string;
  description: string;
} {
  const phases: Record<Phase, { name: string; color: string; days: string; description: string }> = {
    foundation: { name: 'Foundation', color: 'blue', days: '1-21', description: 'Rust basics, ownership, and core concepts' },
    intermediate: { name: 'Intermediate', color: 'violet', days: '22-50', description: 'Traits, generics, lifetimes, and modules' },
    advanced: { name: 'Advanced', color: 'amber', days: '51-75', description: 'Async, concurrency, unsafe, and performance' },
    'exam-prep': { name: 'Exam Prep', color: 'red', days: '76-95', description: 'Mock exams, review, and certification readiness' },
    'job-hunt': { name: 'Job Hunt', color: 'emerald', days: '96-110', description: 'Resume, portfolio, and job applications' },
    'interview-prep': { name: 'Interview Prep', color: 'pink', days: '111-120', description: 'Technical interviews and negotiation' },
  };
  return phases[phase];
}
