import type { LeetCodeProblem } from "@/types"

// Real LeetCode problem data organized by category
// Problems use real titles and URLs from leetcode.com

const arrayProblems: Omit<LeetCodeProblem, 'done' | 'doneAt' | 'notes'>[] = [
  { id: 1, title: "Two Sum", difficulty: "Easy", tags: ["Array", "Hash Table"], url: "https://leetcode.com/problems/two-sum/" },
  { id: 26, title: "Remove Duplicates from Sorted Array", difficulty: "Easy", tags: ["Array", "Two Pointers"], url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/" },
  { id: 27, title: "Remove Element", difficulty: "Easy", tags: ["Array", "Two Pointers"], url: "https://leetcode.com/problems/remove-element/" },
  { id: 35, title: "Search Insert Position", difficulty: "Easy", tags: ["Array", "Binary Search"], url: "https://leetcode.com/problems/search-insert-position/" },
  { id: 53, title: "Maximum Subarray", difficulty: "Medium", tags: ["Array", "Divide and Conquer", "Dynamic Programming"], url: "https://leetcode.com/problems/maximum-subarray/" },
  { id: 66, title: "Plus One", difficulty: "Easy", tags: ["Array", "Math"], url: "https://leetcode.com/problems/plus-one/" },
  { id: 88, title: "Merge Sorted Array", difficulty: "Easy", tags: ["Array", "Two Pointers", "Sorting"], url: "https://leetcode.com/problems/merge-sorted-array/" },
  { id: 121, title: "Best Time to Buy and Sell Stock", difficulty: "Easy", tags: ["Array", "Dynamic Programming"], url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/" },
  { id: 122, title: "Best Time to Buy and Sell Stock II", difficulty: "Medium", tags: ["Array", "Dynamic Programming", "Greedy"], url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/" },
  { id: 169, title: "Majority Element", difficulty: "Easy", tags: ["Array", "Hash Table", "Divide and Conquer"], url: "https://leetcode.com/problems/majority-element/" },
  { id: 189, title: "Rotate Array", difficulty: "Medium", tags: ["Array", "Math", "Two Pointers"], url: "https://leetcode.com/problems/rotate-array/" },
  { id: 217, title: "Contains Duplicate", difficulty: "Easy", tags: ["Array", "Hash Table", "Sorting"], url: "https://leetcode.com/problems/contains-duplicate/" },
  { id: 238, title: "Product of Array Except Self", difficulty: "Medium", tags: ["Array", "Prefix Sum"], url: "https://leetcode.com/problems/product-of-array-except-self/" },
  { id: 268, title: "Missing Number", difficulty: "Easy", tags: ["Array", "Hash Table", "Math", "Bit Manipulation"], url: "https://leetcode.com/problems/missing-number/" },
  { id: 283, title: "Move Zeroes", difficulty: "Easy", tags: ["Array", "Two Pointers"], url: "https://leetcode.com/problems/move-zeroes/" },
  { id: 485, title: "Max Consecutive Ones", difficulty: "Easy", tags: ["Array"], url: "https://leetcode.com/problems/max-consecutive-ones/" },
  { id: 532, title: "K-diff Pairs in an Array", difficulty: "Medium", tags: ["Array", "Hash Table", "Two Pointers", "Binary Search", "Sorting"], url: "https://leetcode.com/problems/k-diff-pairs-in-an-array/" },
  { id: 560, title: "Subarray Sum Equals K", difficulty: "Medium", tags: ["Array", "Hash Table", "Prefix Sum"], url: "https://leetcode.com/problems/subarray-sum-equals-k/" },
  { id: 605, title: "Can Place Flowers", difficulty: "Easy", tags: ["Array", "Greedy"], url: "https://leetcode.com/problems/can-place-flowers/" },
  { id: 643, title: "Maximum Average Subarray I", difficulty: "Easy", tags: ["Array", "Sliding Window"], url: "https://leetcode.com/problems/maximum-average-subarray-i/" },
  { id: 724, title: "Find Pivot Index", difficulty: "Easy", tags: ["Array", "Prefix Sum"], url: "https://leetcode.com/problems/find-pivot-index/" },
  { id: 747, title: "Largest Number At Least Twice of Others", difficulty: "Easy", tags: ["Array", "Sorting"], url: "https://leetcode.com/problems/largest-number-at-least-twice-of-others/" },
  { id: 832, title: "Flipping an Image", difficulty: "Easy", tags: ["Array", "Two Pointers", "Bit Manipulation"], url: "https://leetcode.com/problems/flipping-an-image/" },
  { id: 896, title: "Monotonic Array", difficulty: "Easy", tags: ["Array"], url: "https://leetcode.com/problems/monotonic-array/" },
  { id: 941, title: "Valid Mountain Array", difficulty: "Easy", tags: ["Array"], url: "https://leetcode.com/problems/valid-mountain-array/" },
  { id: 977, title: "Squares of a Sorted Array", difficulty: "Easy", tags: ["Array", "Two Pointers", "Sorting"], url: "https://leetcode.com/problems/squares-of-a-sorted-array/" },
  { id: 1089, title: "Duplicate Zeros", difficulty: "Easy", tags: ["Array", "Two Pointers"], url: "https://leetcode.com/problems/duplicate-zeros/" },
  { id: 1295, title: "Find Numbers with Even Number of Digits", difficulty: "Easy", tags: ["Array"], url: "https://leetcode.com/problems/find-numbers-with-even-number-of-digits/" },
  { id: 1480, title: "Running Sum of 1d Array", difficulty: "Easy", tags: ["Array", "Prefix Sum"], url: "https://leetcode.com/problems/running-sum-of-1d-array/" },
  { id: 1672, title: "Richest Customer Wealth", difficulty: "Easy", tags: ["Array", "Matrix"], url: "https://leetcode.com/problems/richest-customer-wealth/" },
  { id: 11, title: "Container With Most Water", difficulty: "Medium", tags: ["Array", "Two Pointers", "Greedy"], url: "https://leetcode.com/problems/container-with-most-water/" },
  { id: 15, title: "3Sum", difficulty: "Medium", tags: ["Array", "Two Pointers", "Sorting"], url: "https://leetcode.com/problems/3sum/" },
  { id: 16, title: "3Sum Closest", difficulty: "Medium", tags: ["Array", "Two Pointers", "Sorting"], url: "https://leetcode.com/problems/3sum-closest/" },
  { id: 31, title: "Next Permutation", difficulty: "Medium", tags: ["Array", "Two Pointers"], url: "https://leetcode.com/problems/next-permutation/" },
  { id: 33, title: "Search in Rotated Sorted Array", difficulty: "Medium", tags: ["Array", "Binary Search"], url: "https://leetcode.com/problems/search-in-rotated-sorted-array/" },
  { id: 34, title: "Find First and Last Position of Element in Sorted Array", difficulty: "Medium", tags: ["Array", "Binary Search"], url: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/" },
  { id: 39, title: "Combination Sum", difficulty: "Medium", tags: ["Array", "Backtracking"], url: "https://leetcode.com/problems/combination-sum/" },
  { id: 40, title: "Combination Sum II", difficulty: "Medium", tags: ["Array", "Backtracking"], url: "https://leetcode.com/problems/combination-sum-ii/" },
  { id: 41, title: "First Missing Positive", difficulty: "Hard", tags: ["Array", "Hash Table"], url: "https://leetcode.com/problems/first-missing-positive/" },
  { id: 42, title: "Trapping Rain Water", difficulty: "Hard", tags: ["Array", "Two Pointers", "Dynamic Programming", "Stack", "Monotonic Stack"], url: "https://leetcode.com/problems/trapping-rain-water/" },
  { id: 45, title: "Jump Game II", difficulty: "Medium", tags: ["Array", "Dynamic Programming", "Greedy"], url: "https://leetcode.com/problems/jump-game-ii/" },
  { id: 48, title: "Rotate Image", difficulty: "Medium", tags: ["Array", "Math", "Matrix"], url: "https://leetcode.com/problems/rotate-image/" },
  { id: 54, title: "Spiral Matrix", difficulty: "Medium", tags: ["Array", "Matrix", "Simulation"], url: "https://leetcode.com/problems/spiral-matrix/" },
  { id: 55, title: "Jump Game", difficulty: "Medium", tags: ["Array", "Dynamic Programming", "Greedy"], url: "https://leetcode.com/problems/jump-game/" },
  { id: 56, title: "Merge Intervals", difficulty: "Medium", tags: ["Array", "Sorting"], url: "https://leetcode.com/problems/merge-intervals/" },
  { id: 57, title: "Insert Interval", difficulty: "Medium", tags: ["Array"], url: "https://leetcode.com/problems/insert-interval/" },
  { id: 59, title: "Spiral Matrix II", difficulty: "Medium", tags: ["Array", "Matrix", "Simulation"], url: "https://leetcode.com/problems/spiral-matrix-ii/" },
  { id: 73, title: "Set Matrix Zeroes", difficulty: "Medium", tags: ["Array", "Hash Table", "Matrix"], url: "https://leetcode.com/problems/set-matrix-zeroes/" },
  { id: 75, title: "Sort Colors", difficulty: "Medium", tags: ["Array", "Two Pointers", "Sorting"], url: "https://leetcode.com/problems/sort-colors/" },
  { id: 78, title: "Subsets", difficulty: "Medium", tags: ["Array", "Backtracking", "Bit Manipulation"], url: "https://leetcode.com/problems/subsets/" },
  { id: 79, title: "Word Search", difficulty: "Medium", tags: ["Array", "Backtracking", "Matrix"], url: "https://leetcode.com/problems/word-search/" },
  { id: 80, title: "Remove Duplicates from Sorted Array II", difficulty: "Medium", tags: ["Array", "Two Pointers"], url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii/" },
  { id: 81, title: "Search in Rotated Sorted Array II", difficulty: "Medium", tags: ["Array", "Binary Search"], url: "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/" },
  { id: 84, title: "Largest Rectangle in Histogram", difficulty: "Hard", tags: ["Array", "Stack", "Monotonic Stack"], url: "https://leetcode.com/problems/largest-rectangle-in-histogram/" },
  { id: 85, title: "Maximal Rectangle", difficulty: "Hard", tags: ["Array", "Dynamic Programming", "Stack", "Matrix", "Monotonic Stack"], url: "https://leetcode.com/problems/maximal-rectangle/" },
  { id: 90, title: "Subsets II", difficulty: "Medium", tags: ["Array", "Backtracking", "Bit Manipulation"], url: "https://leetcode.com/problems/subsets-ii/" },
  { id: 152, title: "Maximum Product Subarray", difficulty: "Medium", tags: ["Array", "Dynamic Programming"], url: "https://leetcode.com/problems/maximum-product-subarray/" },
  { id: 153, title: "Find Minimum in Rotated Sorted Array", difficulty: "Medium", tags: ["Array", "Binary Search"], url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/" },
  { id: 162, title: "Find Peak Element", difficulty: "Medium", tags: ["Array", "Binary Search"], url: "https://leetcode.com/problems/find-peak-element/" },
  { id: 163, title: "Missing Ranges", difficulty: "Easy", tags: ["Array"], url: "https://leetcode.com/problems/missing-ranges/" },
  { id: 209, title: "Minimum Size Subarray Sum", difficulty: "Medium", tags: ["Array", "Binary Search", "Sliding Window"], url: "https://leetcode.com/problems/minimum-size-subarray-sum/" },
  { id: 215, title: "Kth Largest Element in an Array", difficulty: "Medium", tags: ["Array", "Divide and Conquer", "Sorting", "Heap"], url: "https://leetcode.com/problems/kth-largest-element-in-an-array/" },
  { id: 216, title: "Combination Sum III", difficulty: "Medium", tags: ["Array", "Backtracking"], url: "https://leetcode.com/problems/combination-sum-iii/" },
  { id: 228, title: "Summary Ranges", difficulty: "Easy", tags: ["Array"], url: "https://leetcode.com/problems/summary-ranges/" },
  { id: 229, title: "Majority Element II", difficulty: "Medium", tags: ["Array", "Hash Table", "Sorting"], url: "https://leetcode.com/problems/majority-element-ii/" },
  { id: 240, title: "Search a 2D Matrix II", difficulty: "Medium", tags: ["Array", "Binary Search", "Divide and Conquer", "Matrix"], url: "https://leetcode.com/problems/search-a-2d-matrix-ii/" },
  { id: 243, title: "Shortest Word Distance", difficulty: "Easy", tags: ["Array"], url: "https://leetcode.com/problems/shortest-word-distance/" },
  { id: 252, title: "Meeting Rooms", difficulty: "Easy", tags: ["Array", "Sorting"], url: "https://leetcode.com/problems/meeting-rooms/" },
  { id: 253, title: "Meeting Rooms II", difficulty: "Medium", tags: ["Array", "Two Pointers", "Greedy", "Sorting", "Heap"], url: "https://leetcode.com/problems/meeting-rooms-ii/" },
  { id: 259, title: "3Sum Smaller", difficulty: "Medium", tags: ["Array", "Two Pointers", "Binary Search", "Sorting"], url: "https://leetcode.com/problems/3sum-smaller/" },
  { id: 267, title: "Palindrome Permutation II", difficulty: "Medium", tags: ["Array", "Hash Table", "Backtracking"], url: "https://leetcode.com/problems/palindrome-permutation-ii/" },
  { id: 274, title: "H-Index", difficulty: "Medium", tags: ["Array", "Sorting", "Counting Sort"], url: "https://leetcode.com/problems/h-index/" },
  { id: 280, title: "Wiggle Sort", difficulty: "Medium", tags: ["Array", "Greedy", "Sorting"], url: "https://leetcode.com/problems/wiggle-sort/" },
  { id: 287, title: "Find the Duplicate Number", difficulty: "Medium", tags: ["Array", "Two Pointers", "Binary Search", "Bit Manipulation"], url: "https://leetcode.com/problems/find-the-duplicate-number/" },
  { id: 289, title: "Game of Life", difficulty: "Medium", tags: ["Array", "Matrix", "Simulation"], url: "https://leetcode.com/problems/game-of-life/" },
  { id: 296, title: "Best Meeting Point", difficulty: "Hard", tags: ["Array", "Math", "Matrix", "Sorting"], url: "https://leetcode.com/problems/best-meeting-point/" },
  { id: 311, title: "Sparse Matrix Multiplication", difficulty: "Medium", tags: ["Array", "Hash Table", "Matrix"], url: "https://leetcode.com/problems/sparse-matrix-multiplication/" },
  { id: 315, title: "Count of Smaller Numbers After Self", difficulty: "Hard", tags: ["Array", "Binary Search", "Divide and Conquer", "Binary Indexed Tree", "Merge Sort"], url: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/" },
]

const stringProblems: Omit<LeetCodeProblem, 'done' | 'doneAt' | 'notes'>[] = [
  { id: 3, title: "Longest Substring Without Repeating Characters", difficulty: "Medium", tags: ["Hash Table", "String", "Sliding Window"], url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
  { id: 5, title: "Longest Palindromic Substring", difficulty: "Medium", tags: ["String", "Dynamic Programming"], url: "https://leetcode.com/problems/longest-palindromic-substring/" },
  { id: 6, title: "Zigzag Conversion", difficulty: "Medium", tags: ["String"], url: "https://leetcode.com/problems/zigzag-conversion/" },
  { id: 8, title: "String to Integer (atoi)", difficulty: "Medium", tags: ["String"], url: "https://leetcode.com/problems/string-to-integer-atoi/" },
  { id: 10, title: "Regular Expression Matching", difficulty: "Hard", tags: ["String", "Dynamic Programming", "Recursion"], url: "https://leetcode.com/problems/regular-expression-matching/" },
  { id: 12, title: "Integer to Roman", difficulty: "Medium", tags: ["Hash Table", "Math", "String"], url: "https://leetcode.com/problems/integer-to-roman/" },
  { id: 13, title: "Roman to Integer", difficulty: "Easy", tags: ["Hash Table", "Math", "String"], url: "https://leetcode.com/problems/roman-to-integer/" },
  { id: 14, title: "Longest Common Prefix", difficulty: "Easy", tags: ["String", "Trie"], url: "https://leetcode.com/problems/longest-common-prefix/" },
  { id: 17, title: "Letter Combinations of a Phone Number", difficulty: "Medium", tags: ["Hash Table", "String", "Backtracking"], url: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/" },
  { id: 20, title: "Valid Parentheses", difficulty: "Easy", tags: ["String", "Stack"], url: "https://leetcode.com/problems/valid-parentheses/" },
  { id: 22, title: "Generate Parentheses", difficulty: "Medium", tags: ["String", "Dynamic Programming", "Backtracking"], url: "https://leetcode.com/problems/generate-parentheses/" },
  { id: 28, title: "Find the Index of the First Occurrence in a String", difficulty: "Easy", tags: ["Two Pointers", "String", "String Matching"], url: "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/" },
  { id: 38, title: "Count and Say", difficulty: "Medium", tags: ["String"], url: "https://leetcode.com/problems/count-and-say/" },
  { id: 43, title: "Multiply Strings", difficulty: "Medium", tags: ["Math", "String", "Simulation"], url: "https://leetcode.com/problems/multiply-strings/" },
  { id: 44, title: "Wildcard Matching", difficulty: "Hard", tags: ["String", "Dynamic Programming", "Greedy", "Recursion"], url: "https://leetcode.com/problems/wildcard-matching/" },
  { id: 49, title: "Group Anagrams", difficulty: "Medium", tags: ["Array", "Hash Table", "String", "Sorting"], url: "https://leetcode.com/problems/group-anagrams/" },
  { id: 58, title: "Length of Last Word", difficulty: "Easy", tags: ["String"], url: "https://leetcode.com/problems/length-of-last-word/" },
  { id: 67, title: "Add Binary", difficulty: "Easy", tags: ["Math", "String", "Bit Manipulation", "Simulation"], url: "https://leetcode.com/problems/add-binary/" },
  { id: 71, title: "Simplify Path", difficulty: "Medium", tags: ["String", "Stack"], url: "https://leetcode.com/problems/simplify-path/" },
  { id: 72, title: "Edit Distance", difficulty: "Medium", tags: ["String", "Dynamic Programming"], url: "https://leetcode.com/problems/edit-distance/" },
  { id: 76, title: "Minimum Window Substring", difficulty: "Hard", tags: ["Hash Table", "String", "Sliding Window"], url: "https://leetcode.com/problems/minimum-window-substring/" },
  { id: 91, title: "Decode Ways", difficulty: "Medium", tags: ["String", "Dynamic Programming"], url: "https://leetcode.com/problems/decode-ways/" },
  { id: 93, title: "Restore IP Addresses", difficulty: "Medium", tags: ["String", "Backtracking"], url: "https://leetcode.com/problems/restore-ip-addresses/" },
  { id: 97, title: "Interleaving String", difficulty: "Medium", tags: ["String", "Dynamic Programming"], url: "https://leetcode.com/problems/interleaving-string/" },
  { id: 115, title: "Distinct Subsequences", difficulty: "Hard", tags: ["String", "Dynamic Programming"], url: "https://leetcode.com/problems/distinct-subsequences/" },
  { id: 125, title: "Valid Palindrome", difficulty: "Easy", tags: ["Two Pointers", "String"], url: "https://leetcode.com/problems/valid-palindrome/" },
  { id: 126, title: "Word Ladder II", difficulty: "Hard", tags: ["Hash Table", "String", "Backtracking", "BFS"], url: "https://leetcode.com/problems/word-ladder-ii/" },
  { id: 127, title: "Word Ladder", difficulty: "Hard", tags: ["Hash Table", "String", "BFS"], url: "https://leetcode.com/problems/word-ladder/" },
  { id: 131, title: "Palindrome Partitioning", difficulty: "Medium", tags: ["String", "Dynamic Programming", "Backtracking"], url: "https://leetcode.com/problems/palindrome-partitioning/" },
  { id: 139, title: "Word Break", difficulty: "Medium", tags: ["Hash Table", "String", "Dynamic Programming", "Trie", "Memoization"], url: "https://leetcode.com/problems/word-break/" },
  { id: 140, title: "Word Break II", difficulty: "Hard", tags: ["Hash Table", "String", "Dynamic Programming", "Backtracking", "Trie", "Memoization"], url: "https://leetcode.com/problems/word-break-ii/" },
  { id: 151, title: "Reverse Words in a String", difficulty: "Medium", tags: ["Two Pointers", "String"], url: "https://leetcode.com/problems/reverse-words-in-a-string/" },
  { id: 159, title: "Longest Substring with At Most Two Distinct Characters", difficulty: "Medium", tags: ["Hash Table", "String", "Sliding Window"], url: "https://leetcode.com/problems/longest-substring-with-at-most-two-distinct-characters/" },
  { id: 161, title: "One Edit Distance", difficulty: "Medium", tags: ["Two Pointers", "String"], url: "https://leetcode.com/problems/one-edit-distance/" },
  { id: 165, title: "Compare Version Numbers", difficulty: "Medium", tags: ["Two Pointers", "String"], url: "https://leetcode.com/problems/compare-version-numbers/" },
  { id: 186, title: "Reverse Words in a String II", difficulty: "Medium", tags: ["Two Pointers", "String"], url: "https://leetcode.com/problems/reverse-words-in-a-string-ii/" },
  { id: 205, title: "Isomorphic Strings", difficulty: "Easy", tags: ["Hash Table", "String"], url: "https://leetcode.com/problems/isomorphic-strings/" },
  { id: 208, title: "Implement Trie (Prefix Tree)", difficulty: "Medium", tags: ["Hash Table", "String", "Design", "Trie"], url: "https://leetcode.com/problems/implement-trie-prefix-tree/" },
  { id: 211, title: "Design Add and Search Words Data Structure", difficulty: "Medium", tags: ["String", "DFS", "Design", "Trie"], url: "https://leetcode.com/problems/design-add-and-search-words-data-structure/" },
  { id: 214, title: "Shortest Palindrome", difficulty: "Hard", tags: ["String", "Rolling Hash", "String Matching", "Hash Function"], url: "https://leetcode.com/problems/shortest-palindrome/" },
  { id: 218, title: "The Skyline Problem", difficulty: "Hard", tags: ["Array", "Divide and Conquer", "Binary Indexed Tree", "Segment Tree", "Line Sweep", "Heap", "Ordered Set"], url: "https://leetcode.com/problems/the-skyline-problem/" },
  { id: 224, title: "Basic Calculator", difficulty: "Hard", tags: ["Math", "String", "Stack", "Recursion"], url: "https://leetcode.com/problems/basic-calculator/" },
  { id: 227, title: "Basic Calculator II", difficulty: "Medium", tags: ["Math", "String", "Stack"], url: "https://leetcode.com/problems/basic-calculator-ii/" },
  { id: 242, title: "Valid Anagram", difficulty: "Easy", tags: ["Hash Table", "String", "Sorting"], url: "https://leetcode.com/problems/valid-anagram/" },
  { id: 244, title: "Shortest Word Distance II", difficulty: "Medium", tags: ["Array", "Hash Table", "Design", "Two Pointers"], url: "https://leetcode.com/problems/shortest-word-distance-ii/" },
  { id: 249, title: "Group Shifted Strings", difficulty: "Medium", tags: ["Array", "Hash Table", "String"], url: "https://leetcode.com/problems/group-shifted-strings/" },
  { id: 250, title: "Count Univalue Subtrees", difficulty: "Medium", tags: ["Tree", "DFS", "Binary Tree"], url: "https://leetcode.com/problems/count-univalue-subtrees/" },
  { id: 255, title: "Verify Preorder Sequence in Binary Search Tree", difficulty: "Medium", tags: ["Array", "Stack", "Tree", "Binary Search Tree", "Monotonic Stack", "Binary Tree"], url: "https://leetcode.com/problems/verify-preorder-sequence-in-binary-search-tree/" },
  { id: 257, title: "Binary Tree Paths", difficulty: "Easy", tags: ["String", "Backtracking", "Tree", "DFS", "Binary Tree"], url: "https://leetcode.com/problems/binary-tree-paths/" },
  { id: 271, title: "Encode and Decode Strings", difficulty: "Medium", tags: ["Array", "String", "Design"], url: "https://leetcode.com/problems/encode-and-decode-strings/" },
  { id: 273, title: "Integer to English Words", difficulty: "Hard", tags: ["Math", "String", "Recursion"], url: "https://leetcode.com/problems/integer-to-english-words/" },
]

const linkedListProblems: Omit<LeetCodeProblem, 'done' | 'doneAt' | 'notes'>[] = [
  { id: 2, title: "Add Two Numbers", difficulty: "Medium", tags: ["Linked List", "Math", "Recursion"], url: "https://leetcode.com/problems/add-two-numbers/" },
  { id: 19, title: "Remove Nth Node From End of List", difficulty: "Medium", tags: ["Linked List", "Two Pointers"], url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
  { id: 21, title: "Merge Two Sorted Lists", difficulty: "Easy", tags: ["Linked List", "Recursion"], url: "https://leetcode.com/problems/merge-two-sorted-lists/" },
  { id: 23, title: "Merge k Sorted Lists", difficulty: "Hard", tags: ["Linked List", "Divide and Conquer", "Heap", "Merge Sort"], url: "https://leetcode.com/problems/merge-k-sorted-lists/" },
  { id: 24, title: "Swap Nodes in Pairs", difficulty: "Medium", tags: ["Linked List", "Recursion"], url: "https://leetcode.com/problems/swap-nodes-in-pairs/" },
  { id: 25, title: "Reverse Nodes in k-Group", difficulty: "Hard", tags: ["Linked List", "Recursion"], url: "https://leetcode.com/problems/reverse-nodes-in-k-group/" },
  { id: 61, title: "Rotate List", difficulty: "Medium", tags: ["Linked List", "Two Pointers"], url: "https://leetcode.com/problems/rotate-list/" },
  { id: 82, title: "Remove Duplicates from Sorted List II", difficulty: "Medium", tags: ["Linked List", "Two Pointers"], url: "https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/" },
  { id: 83, title: "Remove Duplicates from Sorted List", difficulty: "Easy", tags: ["Linked List"], url: "https://leetcode.com/problems/remove-duplicates-from-sorted-list/" },
  { id: 86, title: "Partition List", difficulty: "Medium", tags: ["Linked List", "Two Pointers"], url: "https://leetcode.com/problems/partition-list/" },
  { id: 92, title: "Reverse Linked List II", difficulty: "Medium", tags: ["Linked List"], url: "https://leetcode.com/problems/reverse-linked-list-ii/" },
  { id: 138, title: "Copy List with Random Pointer", difficulty: "Medium", tags: ["Hash Table", "Linked List"], url: "https://leetcode.com/problems/copy-list-with-random-pointer/" },
  { id: 141, title: "Linked List Cycle", difficulty: "Easy", tags: ["Hash Table", "Linked List", "Two Pointers"], url: "https://leetcode.com/problems/linked-list-cycle/" },
  { id: 142, title: "Linked List Cycle II", difficulty: "Medium", tags: ["Hash Table", "Linked List", "Two Pointers"], url: "https://leetcode.com/problems/linked-list-cycle-ii/" },
  { id: 143, title: "Reorder List", difficulty: "Medium", tags: ["Linked List", "Two Pointers", "Stack", "Recursion"], url: "https://leetcode.com/problems/reorder-list/" },
  { id: 148, title: "Sort List", difficulty: "Medium", tags: ["Linked List", "Two Pointers", "Divide and Conquer", "Sorting", "Merge Sort"], url: "https://leetcode.com/problems/sort-list/" },
  { id: 160, title: "Intersection of Two Linked Lists", difficulty: "Easy", tags: ["Hash Table", "Linked List", "Two Pointers"], url: "https://leetcode.com/problems/intersection-of-two-linked-lists/" },
  { id: 203, title: "Remove Linked List Elements", difficulty: "Easy", tags: ["Linked List", "Recursion"], url: "https://leetcode.com/problems/remove-linked-list-elements/" },
  { id: 206, title: "Reverse Linked List", difficulty: "Easy", tags: ["Linked List", "Recursion"], url: "https://leetcode.com/problems/reverse-linked-list/" },
  { id: 234, title: "Palindrome Linked List", difficulty: "Easy", tags: ["Linked List", "Two Pointers", "Stack", "Recursion"], url: "https://leetcode.com/problems/palindrome-linked-list/" },
  { id: 237, title: "Delete Node in a Linked List", difficulty: "Medium", tags: ["Linked List"], url: "https://leetcode.com/problems/delete-node-in-a-linked-list/" },
  { id: 328, title: "Odd Even Linked List", difficulty: "Medium", tags: ["Linked List"], url: "https://leetcode.com/problems/odd-even-linked-list/" },
  { id: 369, title: "Plus One Linked List", difficulty: "Medium", tags: ["Linked List", "Math"], url: "https://leetcode.com/problems/plus-one-linked-list/" },
  { id: 430, title: "Flatten a Multilevel Doubly Linked List", difficulty: "Medium", tags: ["Linked List", "DFS", "Doubly-Linked List"], url: "https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/" },
  { id: 445, title: "Add Two Numbers II", difficulty: "Medium", tags: ["Linked List", "Math", "Stack"], url: "https://leetcode.com/problems/add-two-numbers-ii/" },
  { id: 707, title: "Design Linked List", difficulty: "Medium", tags: ["Linked List", "Design"], url: "https://leetcode.com/problems/design-linked-list/" },
  { id: 708, title: "Insert into a Sorted Circular Linked List", difficulty: "Medium", tags: ["Linked List"], url: "https://leetcode.com/problems/insert-into-a-sorted-circular-linked-list/" },
  { id: 725, title: "Split Linked List in Parts", difficulty: "Medium", tags: ["Linked List"], url: "https://leetcode.com/problems/split-linked-list-in-parts/" },
  { id: 817, title: "Linked List Components", difficulty: "Medium", tags: ["Hash Table", "Linked List"], url: "https://leetcode.com/problems/linked-list-components/" },
  { id: 876, title: "Middle of the Linked List", difficulty: "Easy", tags: ["Linked List", "Two Pointers"], url: "https://leetcode.com/problems/middle-of-the-linked-list/" },
]

const stackQueueProblems: Omit<LeetCodeProblem, 'done' | 'doneAt' | 'notes'>[] = [
  { id: 155, title: "Min Stack", difficulty: "Medium", tags: ["Stack", "Design"], url: "https://leetcode.com/problems/min-stack/" },
  { id: 173, title: "Binary Search Tree Iterator", difficulty: "Medium", tags: ["Stack", "Tree", "Design", "Binary Search Tree", "Iterator", "Binary Tree"], url: "https://leetcode.com/problems/binary-search-tree-iterator/" },
  { id: 225, title: "Implement Stack using Queues", difficulty: "Easy", tags: ["Stack", "Design", "Queue"], url: "https://leetcode.com/problems/implement-stack-using-queues/" },
  { id: 232, title: "Implement Queue using Stacks", difficulty: "Easy", tags: ["Stack", "Design", "Queue"], url: "https://leetcode.com/problems/implement-queue-using-stacks/" },
  { id: 239, title: "Sliding Window Maximum", difficulty: "Hard", tags: ["Array", "Queue", "Sliding Window", "Heap", "Monotonic Queue"], url: "https://leetcode.com/problems/sliding-window-maximum/" },
  { id: 295, title: "Find Median from Data Stream", difficulty: "Hard", tags: ["Two Pointers", "Design", "Sorting", "Heap", "Data Stream"], url: "https://leetcode.com/problems/find-median-from-data-stream/" },
  { id: 341, title: "Flatten Nested List Iterator", difficulty: "Medium", tags: ["Stack", "Tree", "DFS", "Design", "Queue", "Iterator"], url: "https://leetcode.com/problems/flatten-nested-list-iterator/" },
  { id: 346, title: "Moving Average from Data Stream", difficulty: "Easy", tags: ["Array", "Design", "Queue", "Data Stream"], url: "https://leetcode.com/problems/moving-average-from-data-stream/" },
  { id: 394, title: "Decode String", difficulty: "Medium", tags: ["String", "Stack", "Recursion"], url: "https://leetcode.com/problems/decode-string/" },
  { id: 402, title: "Remove K Digits", difficulty: "Medium", tags: ["String", "Stack", "Greedy", "Monotonic Stack"], url: "https://leetcode.com/problems/remove-k-digits/" },
  { id: 496, title: "Next Greater Element I", difficulty: "Easy", tags: ["Array", "Hash Table", "Stack", "Monotonic Stack"], url: "https://leetcode.com/problems/next-greater-element-i/" },
  { id: 503, title: "Next Greater Element II", difficulty: "Medium", tags: ["Array", "Stack", "Monotonic Stack"], url: "https://leetcode.com/problems/next-greater-element-ii/" },
  { id: 581, title: "Shortest Unsorted Continuous Subarray", difficulty: "Medium", tags: ["Array", "Two Pointers", "Stack", "Greedy", "Sorting", "Monotonic Stack"], url: "https://leetcode.com/problems/shortest-unsorted-continuous-subarray/" },
  { id: 636, title: "Exclusive Time of Functions", difficulty: "Medium", tags: ["Array", "Stack"], url: "https://leetcode.com/problems/exclusive-time-of-functions/" },
  { id: 641, title: "Design Circular Deque", difficulty: "Medium", tags: ["Array", "Linked List", "Design", "Queue"], url: "https://leetcode.com/problems/design-circular-deque/" },
  { id: 678, title: "Valid Parenthesis String", difficulty: "Medium", tags: ["String", "Dynamic Programming", "Stack", "Greedy"], url: "https://leetcode.com/problems/valid-parenthesis-string/" },
  { id: 682, title: "Baseball Game", difficulty: "Easy", tags: ["Array", "Stack", "Simulation"], url: "https://leetcode.com/problems/baseball-game/" },
  { id: 716, title: "Max Stack", difficulty: "Hard", tags: ["Linked List", "Stack", "Design", "Doubly-Linked List", "Ordered Set"], url: "https://leetcode.com/problems/max-stack/" },
  { id: 735, title: "Asteroid Collision", difficulty: "Medium", tags: ["Array", "Stack", "Simulation"], url: "https://leetcode.com/problems/asteroid-collision/" },
  { id: 739, title: "Daily Temperatures", difficulty: "Medium", tags: ["Array", "Stack", "Monotonic Stack"], url: "https://leetcode.com/problems/daily-temperatures/" },
  { id: 844, title: "Backspace String Compare", difficulty: "Easy", tags: ["Two Pointers", "String", "Stack", "Simulation"], url: "https://leetcode.com/problems/backspace-string-compare/" },
  { id: 856, title: "Score of Parentheses", difficulty: "Medium", tags: ["String", "Stack"], url: "https://leetcode.com/problems/score-of-parentheses/" },
  { id: 895, title: "Maximum Frequency Stack", difficulty: "Hard", tags: ["Hash Table", "Stack", "Design", "Ordered Set"], url: "https://leetcode.com/problems/maximum-frequency-stack/" },
  { id: 901, title: "Online Stock Span", difficulty: "Medium", tags: ["Stack", "Design", "Monotonic Stack", "Data Stream"], url: "https://leetcode.com/problems/online-stock-span/" },
  { id: 907, title: "Sum of Subarray Minimums", difficulty: "Medium", tags: ["Array", "Dynamic Programming", "Stack", "Monotonic Stack"], url: "https://leetcode.com/problems/sum-of-subarray-minimums/" },
  { id: 921, title: "Minimum Add to Make Parentheses Valid", difficulty: "Medium", tags: ["String", "Stack", "Greedy"], url: "https://leetcode.com/problems/minimum-add-to-make-parentheses-valid/" },
  { id: 946, title: "Validate Stack Sequences", difficulty: "Medium", tags: ["Array", "Stack", "Simulation"], url: "https://leetcode.com/problems/validate-stack-sequences/" },
  { id: 962, title: "Maximum Width Ramp", difficulty: "Medium", tags: ["Array", "Stack", "Monotonic Stack"], url: "https://leetcode.com/problems/maximum-width-ramp/" },
  { id: 1047, title: "Remove All Adjacent Duplicates In String", difficulty: "Easy", tags: ["String", "Stack"], url: "https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string/" },
  { id: 1209, title: "Remove All Adjacent Duplicates in String II", difficulty: "Medium", tags: ["String", "Stack"], url: "https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string-ii/" },
  { id: 1249, title: "Minimum Remove to Make Valid Parentheses", difficulty: "Medium", tags: ["String", "Stack"], url: "https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses/" },
]

const treeProblems: Omit<LeetCodeProblem, 'done' | 'doneAt' | 'notes'>[] = [
  { id: 94, title: "Binary Tree Inorder Traversal", difficulty: "Easy", tags: ["Stack", "Tree", "DFS", "Binary Tree"], url: "https://leetcode.com/problems/binary-tree-inorder-traversal/" },
  { id: 95, title: "Unique Binary Search Trees II", difficulty: "Medium", tags: ["Dynamic Programming", "Backtracking", "Tree", "Memoization", "Binary Search Tree", "Binary Tree"], url: "https://leetcode.com/problems/unique-binary-search-trees-ii/" },
  { id: 96, title: "Unique Binary Search Trees", difficulty: "Medium", tags: ["Math", "Dynamic Programming", "Tree", "Binary Search Tree", "Binary Tree"], url: "https://leetcode.com/problems/unique-binary-search-trees/" },
  { id: 98, title: "Validate Binary Search Tree", difficulty: "Medium", tags: ["Tree", "DFS", "Binary Search Tree", "Binary Tree"], url: "https://leetcode.com/problems/validate-binary-search-tree/" },
  { id: 99, title: "Recover Binary Search Tree", difficulty: "Medium", tags: ["Tree", "DFS", "Binary Search Tree", "Binary Tree"], url: "https://leetcode.com/problems/recover-binary-search-tree/" },
  { id: 100, title: "Same Tree", difficulty: "Easy", tags: ["Tree", "DFS", "BFS", "Binary Tree"], url: "https://leetcode.com/problems/same-tree/" },
  { id: 101, title: "Symmetric Tree", difficulty: "Easy", tags: ["Tree", "DFS", "BFS", "Binary Tree"], url: "https://leetcode.com/problems/symmetric-tree/" },
  { id: 102, title: "Binary Tree Level Order Traversal", difficulty: "Medium", tags: ["Tree", "BFS", "Binary Tree"], url: "https://leetcode.com/problems/binary-tree-level-order-traversal/" },
  { id: 103, title: "Binary Tree Zigzag Level Order Traversal", difficulty: "Medium", tags: ["Tree", "BFS", "Binary Tree"], url: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/" },
  { id: 104, title: "Maximum Depth of Binary Tree", difficulty: "Easy", tags: ["Tree", "DFS", "BFS", "Binary Tree"], url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/" },
  { id: 105, title: "Construct Binary Tree from Preorder and Inorder Traversal", difficulty: "Medium", tags: ["Array", "Hash Table", "Divide and Conquer", "Tree", "Binary Tree"], url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/" },
  { id: 106, title: "Construct Binary Tree from Inorder and Postorder Traversal", difficulty: "Medium", tags: ["Array", "Hash Table", "Divide and Conquer", "Tree", "Binary Tree"], url: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/" },
  { id: 107, title: "Binary Tree Level Order Traversal II", difficulty: "Medium", tags: ["Tree", "BFS", "Binary Tree"], url: "https://leetcode.com/problems/binary-tree-level-order-traversal-ii/" },
  { id: 108, title: "Convert Sorted Array to Binary Search Tree", difficulty: "Easy", tags: ["Array", "Divide and Conquer", "Tree", "Binary Search Tree", "Binary Tree"], url: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/" },
  { id: 110, title: "Balanced Binary Tree", difficulty: "Easy", tags: ["Tree", "DFS", "Binary Tree"], url: "https://leetcode.com/problems/balanced-binary-tree/" },
  { id: 111, title: "Minimum Depth of Binary Tree", difficulty: "Easy", tags: ["Tree", "DFS", "BFS", "Binary Tree"], url: "https://leetcode.com/problems/minimum-depth-of-binary-tree/" },
  { id: 112, title: "Path Sum", difficulty: "Easy", tags: ["Tree", "DFS", "BFS", "Binary Tree"], url: "https://leetcode.com/problems/path-sum/" },
  { id: 113, title: "Path Sum II", difficulty: "Medium", tags: ["Backtracking", "Tree", "DFS", "Binary Tree"], url: "https://leetcode.com/problems/path-sum-ii/" },
  { id: 114, title: "Flatten Binary Tree to Linked List", difficulty: "Medium", tags: ["Linked List", "Stack", "Tree", "DFS", "Binary Tree"], url: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/" },
  { id: 116, title: "Populating Next Right Pointers in Each Node", difficulty: "Medium", tags: ["Linked List", "Tree", "DFS", "BFS", "Binary Tree"], url: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node/" },
  { id: 117, title: "Populating Next Right Pointers in Each Node II", difficulty: "Medium", tags: ["Linked List", "Tree", "DFS", "BFS", "Binary Tree"], url: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii/" },
  { id: 124, title: "Binary Tree Maximum Path Sum", difficulty: "Hard", tags: ["Dynamic Programming", "Tree", "DFS", "Binary Tree"], url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/" },
  { id: 144, title: "Binary Tree Preorder Traversal", difficulty: "Easy", tags: ["Stack", "Tree", "DFS", "Binary Tree"], url: "https://leetcode.com/problems/binary-tree-preorder-traversal/" },
  { id: 145, title: "Binary Tree Postorder Traversal", difficulty: "Easy", tags: ["Stack", "Tree", "DFS", "Binary Tree"], url: "https://leetcode.com/problems/binary-tree-postorder-traversal/" },
  { id: 156, title: "Binary Tree Upside Down", difficulty: "Medium", tags: ["Tree", "DFS", "Binary Tree"], url: "https://leetcode.com/problems/binary-tree-upside-down/" },
  { id: 199, title: "Binary Tree Right Side View", difficulty: "Medium", tags: ["Tree", "DFS", "BFS", "Binary Tree"], url: "https://leetcode.com/problems/binary-tree-right-side-view/" },
  { id: 222, title: "Count Complete Tree Nodes", difficulty: "Easy", tags: ["Binary Search", "Bit Manipulation", "Tree", "Binary Search Tree", "Binary Tree"], url: "https://leetcode.com/problems/count-complete-tree-nodes/" },
  { id: 226, title: "Invert Binary Tree", difficulty: "Easy", tags: ["Tree", "DFS", "BFS", "Binary Tree"], url: "https://leetcode.com/problems/invert-binary-tree/" },
  { id: 230, title: "Kth Smallest Element in a BST", difficulty: "Medium", tags: ["Tree", "DFS", "Binary Search Tree", "Binary Tree"], url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/" },
  { id: 235, title: "Lowest Common Ancestor of a Binary Search Tree", difficulty: "Medium", tags: ["Tree", "DFS", "Binary Search Tree", "Binary Tree"], url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/" },
  { id: 236, title: "Lowest Common Ancestor of a Binary Tree", difficulty: "Medium", tags: ["Tree", "DFS", "Binary Tree"], url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/" },
  { id: 297, title: "Serialize and Deserialize Binary Tree", difficulty: "Hard", tags: ["String", "Tree", "DFS", "BFS", "Design", "Binary Tree"], url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/" },
  { id: 298, title: "Binary Tree Longest Consecutive Sequence", difficulty: "Medium", tags: ["Tree", "DFS", "Binary Tree"], url: "https://leetcode.com/problems/binary-tree-longest-consecutive-sequence/" },
  { id: 337, title: "House Robber III", difficulty: "Medium", tags: ["Dynamic Programming", "Tree", "DFS", "Binary Tree"], url: "https://leetcode.com/problems/house-robber-iii/" },
  { id: 366, title: "Find Leaves of Binary Tree", difficulty: "Medium", tags: ["Tree", "DFS", "Sorting", "Binary Tree"], url: "https://leetcode.com/problems/find-leaves-of-binary-tree/" },
  { id: 404, title: "Sum of Left Leaves", difficulty: "Easy", tags: ["Tree", "DFS", "BFS", "Binary Tree"], url: "https://leetcode.com/problems/sum-of-left-leaves/" },
  { id: 437, title: "Path Sum III", difficulty: "Medium", tags: ["Tree", "DFS", "Binary Tree"], url: "https://leetcode.com/problems/path-sum-iii/" },
  { id: 513, title: "Find Bottom Left Tree Value", difficulty: "Medium", tags: ["Tree", "DFS", "BFS", "Binary Tree"], url: "https://leetcode.com/problems/find-bottom-left-tree-value/" },
]

const graphProblems: Omit<LeetCodeProblem, 'done' | 'doneAt' | 'notes'>[] = [
  { id: 133, title: "Clone Graph", difficulty: "Medium", tags: ["Hash Table", "DFS", "BFS", "Graph"], url: "https://leetcode.com/problems/clone-graph/" },
  { id: 200, title: "Number of Islands", difficulty: "Medium", tags: ["Array", "DFS", "BFS", "Union Find", "Matrix"], url: "https://leetcode.com/problems/number-of-islands/" },
  { id: 207, title: "Course Schedule", difficulty: "Medium", tags: ["DFS", "BFS", "Graph", "Topological Sort"], url: "https://leetcode.com/problems/course-schedule/" },
  { id: 210, title: "Course Schedule II", difficulty: "Medium", tags: ["DFS", "BFS", "Graph", "Topological Sort"], url: "https://leetcode.com/problems/course-schedule-ii/" },
  { id: 261, title: "Graph Valid Tree", difficulty: "Medium", tags: ["DFS", "BFS", "Union Find", "Graph"], url: "https://leetcode.com/problems/graph-valid-tree/" },
  { id: 269, title: "Alien Dictionary", difficulty: "Hard", tags: ["Array", "String", "DFS", "BFS", "Graph", "Topological Sort"], url: "https://leetcode.com/problems/alien-dictionary/" },
  { id: 286, title: "Walls and Gates", difficulty: "Medium", tags: ["Array", "BFS", "Matrix"], url: "https://leetcode.com/problems/walls-and-gates/" },
  { id: 310, title: "Minimum Height Trees", difficulty: "Medium", tags: ["DFS", "BFS", "Graph", "Topological Sort"], url: "https://leetcode.com/problems/minimum-height-trees/" },
  { id: 317, title: "Shortest Distance from All Buildings", difficulty: "Hard", tags: ["Array", "BFS", "Matrix"], url: "https://leetcode.com/problems/shortest-distance-from-all-buildings/" },
  { id: 323, title: "Number of Connected Components in an Undirected Graph", difficulty: "Medium", tags: ["DFS", "BFS", "Union Find", "Graph"], url: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/" },
  { id: 329, title: "Longest Increasing Path in a Matrix", difficulty: "Hard", tags: ["Array", "Dynamic Programming", "DFS", "BFS", "Graph", "Topological Sort", "Memoization", "Matrix"], url: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix/" },
  { id: 399, title: "Evaluate Division", difficulty: "Medium", tags: ["Array", "DFS", "BFS", "Union Find", "Graph", "Shortest Path"], url: "https://leetcode.com/problems/evaluate-division/" },
  { id: 417, title: "Pacific Atlantic Water Flow", difficulty: "Medium", tags: ["Array", "DFS", "BFS", "Matrix"], url: "https://leetcode.com/problems/pacific-atlantic-water-flow/" },
  { id: 444, title: "Sequence Reconstruction", difficulty: "Medium", tags: ["Array", "BFS", "Graph", "Topological Sort"], url: "https://leetcode.com/problems/sequence-reconstruction/" },
  { id: 490, title: "The Maze", difficulty: "Medium", tags: ["Array", "DFS", "BFS", "Matrix"], url: "https://leetcode.com/problems/the-maze/" },
  { id: 505, title: "The Maze II", difficulty: "Medium", tags: ["Array", "DFS", "BFS", "Graph", "Heap", "Matrix", "Shortest Path"], url: "https://leetcode.com/problems/the-maze-ii/" },
  { id: 542, title: "01 Matrix", difficulty: "Medium", tags: ["Array", "Dynamic Programming", "BFS", "Matrix"], url: "https://leetcode.com/problems/01-matrix/" },
  { id: 547, title: "Number of Provinces", difficulty: "Medium", tags: ["DFS", "BFS", "Union Find", "Graph"], url: "https://leetcode.com/problems/number-of-provinces/" },
  { id: 684, title: "Redundant Connection", difficulty: "Medium", tags: ["DFS", "BFS", "Union Find", "Graph"], url: "https://leetcode.com/problems/redundant-connection/" },
  { id: 695, title: "Max Area of Island", difficulty: "Medium", tags: ["Array", "DFS", "BFS", "Union Find", "Matrix"], url: "https://leetcode.com/problems/max-area-of-island/" },
  { id: 721, title: "Accounts Merge", difficulty: "Medium", tags: ["Array", "Hash Table", "String", "DFS", "BFS", "Union Find", "Sorting"], url: "https://leetcode.com/problems/accounts-merge/" },
  { id: 743, title: "Network Delay Time", difficulty: "Medium", tags: ["DFS", "BFS", "Graph", "Heap", "Shortest Path"], url: "https://leetcode.com/problems/network-delay-time/" },
  { id: 785, title: "Is Graph Bipartite?", difficulty: "Medium", tags: ["DFS", "BFS", "Union Find", "Graph"], url: "https://leetcode.com/problems/is-graph-bipartite/" },
  { id: 787, title: "Cheapest Flights Within K Stops", difficulty: "Medium", tags: ["Dynamic Programming", "DFS", "BFS", "Graph", "Heap", "Shortest Path"], url: "https://leetcode.com/problems/cheapest-flights-within-k-stops/" },
  { id: 802, title: "Find Eventual Safe States", difficulty: "Medium", tags: ["DFS", "BFS", "Graph", "Topological Sort"], url: "https://leetcode.com/problems/find-eventual-safe-states/" },
  { id: 815, title: "Bus Routes", difficulty: "Hard", tags: ["Array", "Hash Table", "BFS"], url: "https://leetcode.com/problems/bus-routes/" },
  { id: 827, title: "Making A Large Island", difficulty: "Hard", tags: ["Array", "DFS", "BFS", "Union Find", "Matrix"], url: "https://leetcode.com/problems/making-a-large-island/" },
  { id: 847, title: "Shortest Path Visiting All Nodes", difficulty: "Hard", tags: ["Dynamic Programming", "BFS", "Bit Manipulation", "Graph", "Bitmask"], url: "https://leetcode.com/problems/shortest-path-visiting-all-nodes/" },
  { id: 886, title: "Possible Bipartition", difficulty: "Medium", tags: ["DFS", "BFS", "Union Find", "Graph"], url: "https://leetcode.com/problems/possible-bipartition/" },
  { id: 994, title: "Rotting Oranges", difficulty: "Medium", tags: ["Array", "BFS", "Matrix"], url: "https://leetcode.com/problems/rotting-oranges/" },
  { id: 1059, title: "All Paths from Source Lead to Destination", difficulty: "Medium", tags: ["DFS", "Graph"], url: "https://leetcode.com/problems/all-paths-from-source-lead-to-destination/" },
]

const dpProblems: Omit<LeetCodeProblem, 'done' | 'doneAt' | 'notes'>[] = [
  { id: 70, title: "Climbing Stairs", difficulty: "Easy", tags: ["Math", "Dynamic Programming", "Memoization"], url: "https://leetcode.com/problems/climbing-stairs/" },
  { id: 62, title: "Unique Paths", difficulty: "Medium", tags: ["Math", "Dynamic Programming", "Combinatorics"], url: "https://leetcode.com/problems/unique-paths/" },
  { id: 63, title: "Unique Paths II", difficulty: "Medium", tags: ["Array", "Dynamic Programming", "Matrix"], url: "https://leetcode.com/problems/unique-paths-ii/" },
  { id: 64, title: "Minimum Path Sum", difficulty: "Medium", tags: ["Array", "Dynamic Programming", "Matrix"], url: "https://leetcode.com/problems/minimum-path-sum/" },
  { id: 118, title: "Pascal's Triangle", difficulty: "Easy", tags: ["Array", "Dynamic Programming"], url: "https://leetcode.com/problems/pascals-triangle/" },
  { id: 119, title: "Pascal's Triangle II", difficulty: "Easy", tags: ["Array", "Dynamic Programming"], url: "https://leetcode.com/problems/pascals-triangle-ii/" },
  { id: 120, title: "Triangle", difficulty: "Medium", tags: ["Array", "Dynamic Programming"], url: "https://leetcode.com/problems/triangle/" },
  { id: 123, title: "Best Time to Buy and Sell Stock III", difficulty: "Hard", tags: ["Array", "Dynamic Programming"], url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/" },
  { id: 132, title: "Palindrome Partitioning II", difficulty: "Hard", tags: ["String", "Dynamic Programming"], url: "https://leetcode.com/problems/palindrome-partitioning-ii/" },
  { id: 174, title: "Dungeon Game", difficulty: "Hard", tags: ["Array", "Dynamic Programming", "Matrix"], url: "https://leetcode.com/problems/dungeon-game/" },
  { id: 188, title: "Best Time to Buy and Sell Stock IV", difficulty: "Hard", tags: ["Array", "Dynamic Programming"], url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/" },
  { id: 198, title: "House Robber", difficulty: "Medium", tags: ["Array", "Dynamic Programming"], url: "https://leetcode.com/problems/house-robber/" },
  { id: 213, title: "House Robber II", difficulty: "Medium", tags: ["Array", "Dynamic Programming"], url: "https://leetcode.com/problems/house-robber-ii/" },
  { id: 221, title: "Maximal Square", difficulty: "Medium", tags: ["Array", "Dynamic Programming", "Matrix"], url: "https://leetcode.com/problems/maximal-square/" },
  { id: 256, title: "Paint House", difficulty: "Medium", tags: ["Array", "Dynamic Programming"], url: "https://leetcode.com/problems/paint-house/" },
  { id: 264, title: "Ugly Number II", difficulty: "Medium", tags: ["Hash Table", "Math", "Dynamic Programming", "Heap"], url: "https://leetcode.com/problems/ugly-number-ii/" },
  { id: 276, title: "Paint Fence", difficulty: "Medium", tags: ["Dynamic Programming"], url: "https://leetcode.com/problems/paint-fence/" },
  { id: 279, title: "Perfect Squares", difficulty: "Medium", tags: ["Math", "Dynamic Programming", "BFS"], url: "https://leetcode.com/problems/perfect-squares/" },
  { id: 300, title: "Longest Increasing Subsequence", difficulty: "Medium", tags: ["Array", "Binary Search", "Dynamic Programming"], url: "https://leetcode.com/problems/longest-increasing-subsequence/" },
  { id: 303, title: "Range Sum Query - Immutable", difficulty: "Easy", tags: ["Array", "Design", "Prefix Sum"], url: "https://leetcode.com/problems/range-sum-query-immutable/" },
  { id: 304, title: "Range Sum Query 2D - Immutable", difficulty: "Medium", tags: ["Array", "Design", "Matrix", "Prefix Sum"], url: "https://leetcode.com/problems/range-sum-query-2d-immutable/" },
  { id: 309, title: "Best Time to Buy and Sell Stock with Cooldown", difficulty: "Medium", tags: ["Array", "Dynamic Programming"], url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/" },
  { id: 312, title: "Burst Balloons", difficulty: "Hard", tags: ["Array", "Dynamic Programming"], url: "https://leetcode.com/problems/burst-balloons/" },
  { id: 313, title: "Super Ugly Number", difficulty: "Medium", tags: ["Array", "Math", "Dynamic Programming"], url: "https://leetcode.com/problems/super-ugly-number/" },
  { id: 322, title: "Coin Change", difficulty: "Medium", tags: ["Array", "Dynamic Programming", "BFS"], url: "https://leetcode.com/problems/coin-change/" },
  { id: 338, title: "Counting Bits", difficulty: "Easy", tags: ["Dynamic Programming", "Bit Manipulation"], url: "https://leetcode.com/problems/counting-bits/" },
  { id: 343, title: "Integer Break", difficulty: "Medium", tags: ["Math", "Dynamic Programming"], url: "https://leetcode.com/problems/integer-break/" },
  { id: 357, title: "Count Numbers with Unique Digits", difficulty: "Medium", tags: ["Math", "Dynamic Programming", "Backtracking"], url: "https://leetcode.com/problems/count-numbers-with-unique-digits/" },
  { id: 368, title: "Largest Divisible Subset", difficulty: "Medium", tags: ["Array", "Math", "Dynamic Programming", "Sorting"], url: "https://leetcode.com/problems/largest-divisible-subset/" },
  { id: 375, title: "Guess Number Higher or Lower II", difficulty: "Medium", tags: ["Math", "Dynamic Programming", "Game Theory"], url: "https://leetcode.com/problems/guess-number-higher-or-lower-ii/" },
  { id: 377, title: "Combination Sum IV", difficulty: "Medium", tags: ["Array", "Dynamic Programming"], url: "https://leetcode.com/problems/combination-sum-iv/" },
  { id: 392, title: "Is Subsequence", difficulty: "Easy", tags: ["Two Pointers", "String", "Dynamic Programming"], url: "https://leetcode.com/problems/is-subsequence/" },
  { id: 397, title: "Integer Replacement", difficulty: "Medium", tags: ["Dynamic Programming", "Greedy", "Bit Manipulation", "Memoization"], url: "https://leetcode.com/problems/integer-replacement/" },
  { id: 403, title: "Frog Jump", difficulty: "Hard", tags: ["Array", "Dynamic Programming"], url: "https://leetcode.com/problems/frog-jump/" },
  { id: 410, title: "Split Array Largest Sum", difficulty: "Hard", tags: ["Array", "Binary Search", "Dynamic Programming", "Greedy", "Prefix Sum"], url: "https://leetcode.com/problems/split-array-largest-sum/" },
  { id: 413, title: "Arithmetic Slices", difficulty: "Medium", tags: ["Array", "Dynamic Programming"], url: "https://leetcode.com/problems/arithmetic-slices/" },
  { id: 416, title: "Partition Equal Subset Sum", difficulty: "Medium", tags: ["Array", "Dynamic Programming"], url: "https://leetcode.com/problems/partition-equal-subset-sum/" },
  { id: 418, title: "Sentence Screen Fitting", difficulty: "Medium", tags: ["Array", "String", "Dynamic Programming"], url: "https://leetcode.com/problems/sentence-screen-fitting/" },
  { id: 446, title: "Arithmetic Slices II - Subsequence", difficulty: "Hard", tags: ["Array", "Dynamic Programming"], url: "https://leetcode.com/problems/arithmetic-slices-ii-subsequence/" },
  { id: 464, title: "Can I Win", difficulty: "Medium", tags: ["Math", "Dynamic Programming", "Bit Manipulation", "Memoization", "Game Theory", "Bitmask"], url: "https://leetcode.com/problems/can-i-win/" },
  { id: 467, title: "Unique Substrings in Wraparound String", difficulty: "Medium", tags: ["String", "Dynamic Programming"], url: "https://leetcode.com/problems/unique-substrings-in-wraparound-string/" },
  { id: 474, title: "Ones and Zeroes", difficulty: "Medium", tags: ["Array", "String", "Dynamic Programming"], url: "https://leetcode.com/problems/ones-and-zeroes/" },
  { id: 486, title: "Predict the Winner", difficulty: "Medium", tags: ["Array", "Math", "Dynamic Programming", "Game Theory"], url: "https://leetcode.com/problems/predict-the-winner/" },
  { id: 494, title: "Target Sum", difficulty: "Medium", tags: ["Array", "Dynamic Programming", "Backtracking"], url: "https://leetcode.com/problems/target-sum/" },
  { id: 516, title: "Longest Palindromic Subsequence", difficulty: "Medium", tags: ["String", "Dynamic Programming"], url: "https://leetcode.com/problems/longest-palindromic-subsequence/" },
  { id: 518, title: "Coin Change II", difficulty: "Medium", tags: ["Array", "Dynamic Programming"], url: "https://leetcode.com/problems/coin-change-ii/" },
  { id: 523, title: "Continuous Subarray Sum", difficulty: "Medium", tags: ["Array", "Hash Table", "Math", "Prefix Sum"], url: "https://leetcode.com/problems/continuous-subarray-sum/" },
  { id: 525, title: "Contiguous Array", difficulty: "Medium", tags: ["Array", "Hash Table", "Prefix Sum"], url: "https://leetcode.com/problems/contiguous-array/" },
  { id: 526, title: "Beautiful Arrangement", difficulty: "Medium", tags: ["Array", "Dynamic Programming", "Backtracking", "Bit Manipulation", "Bitmask"], url: "https://leetcode.com/problems/beautiful-arrangement/" },
  { id: 546, title: "Remove Boxes", difficulty: "Hard", tags: ["Array", "Dynamic Programming", "Memoization"], url: "https://leetcode.com/problems/remove-boxes/" },
  { id: 552, title: "Student Attendance Record II", difficulty: "Hard", tags: ["Dynamic Programming"], url: "https://leetcode.com/problems/student-attendance-record-ii/" },
]

const binarySearchProblems: Omit<LeetCodeProblem, 'done' | 'doneAt' | 'notes'>[] = [
  { id: 4, title: "Median of Two Sorted Arrays", difficulty: "Hard", tags: ["Array", "Binary Search", "Divide and Conquer"], url: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
  { id: 69, title: "Sqrt(x)", difficulty: "Easy", tags: ["Math", "Binary Search"], url: "https://leetcode.com/problems/sqrtx/" },
  { id: 74, title: "Search a 2D Matrix", difficulty: "Medium", tags: ["Array", "Binary Search", "Matrix"], url: "https://leetcode.com/problems/search-a-2d-matrix/" },
  { id: 154, title: "Find Minimum in Rotated Sorted Array II", difficulty: "Hard", tags: ["Array", "Binary Search"], url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/" },
  { id: 167, title: "Two Sum II - Input Array Is Sorted", difficulty: "Medium", tags: ["Array", "Two Pointers", "Binary Search"], url: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/" },
  { id: 222, title: "Count Complete Tree Nodes", difficulty: "Easy", tags: ["Binary Search", "Bit Manipulation", "Tree", "Binary Search Tree", "Binary Tree"], url: "https://leetcode.com/problems/count-complete-tree-nodes/" },
  { id: 270, title: "Closest Binary Search Tree Value", difficulty: "Easy", tags: ["Binary Search", "Tree", "DFS", "Binary Search Tree", "Binary Tree"], url: "https://leetcode.com/problems/closest-binary-search-tree-value/" },
  { id: 275, title: "H-Index II", difficulty: "Medium", tags: ["Array", "Binary Search"], url: "https://leetcode.com/problems/h-index-ii/" },
  { id: 278, title: "First Bad Version", difficulty: "Easy", tags: ["Binary Search", "Interactive"], url: "https://leetcode.com/problems/first-bad-version/" },
  { id: 374, title: "Guess Number Higher or Lower", difficulty: "Easy", tags: ["Binary Search", "Interactive"], url: "https://leetcode.com/problems/guess-number-higher-or-lower/" },
  { id: 378, title: "Kth Smallest Element in a Sorted Matrix", difficulty: "Medium", tags: ["Array", "Binary Search", "Sorting", "Heap", "Matrix"], url: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/" },
  { id: 410, title: "Split Array Largest Sum", difficulty: "Hard", tags: ["Array", "Binary Search", "Dynamic Programming", "Greedy", "Prefix Sum"], url: "https://leetcode.com/problems/split-array-largest-sum/" },
  { id: 436, title: "Find Right Interval", difficulty: "Medium", tags: ["Array", "Binary Search", "Sorting"], url: "https://leetcode.com/problems/find-right-interval/" },
  { id: 441, title: "Arranging Coins", difficulty: "Easy", tags: ["Math", "Binary Search"], url: "https://leetcode.com/problems/arranging-coins/" },
  { id: 454, title: "4Sum II", difficulty: "Medium", tags: ["Array", "Hash Table"], url: "https://leetcode.com/problems/4sum-ii/" },
  { id: 475, title: "Heaters", difficulty: "Medium", tags: ["Array", "Two Pointers", "Binary Search", "Sorting"], url: "https://leetcode.com/problems/heaters/" },
  { id: 540, title: "Single Element in a Sorted Array", difficulty: "Medium", tags: ["Array", "Binary Search"], url: "https://leetcode.com/problems/single-element-in-a-sorted-array/" },
  { id: 611, title: "Valid Triangle Number", difficulty: "Medium", tags: ["Array", "Two Pointers", "Binary Search", "Greedy", "Sorting"], url: "https://leetcode.com/problems/valid-triangle-number/" },
  { id: 668, title: "Kth Smallest Number in Multiplication Table", difficulty: "Hard", tags: ["Math", "Binary Search"], url: "https://leetcode.com/problems/kth-smallest-number-in-multiplication-table/" },
  { id: 702, title: "Search in a Sorted Array of Unknown Size", difficulty: "Medium", tags: ["Array", "Binary Search", "Interactive"], url: "https://leetcode.com/problems/search-in-a-sorted-array-of-unknown-size/" },
]

const backtrackingProblems: Omit<LeetCodeProblem, 'done' | 'doneAt' | 'notes'>[] = [
  { id: 37, title: "Sudoku Solver", difficulty: "Hard", tags: ["Array", "Hash Table", "Backtracking", "Matrix"], url: "https://leetcode.com/problems/sudoku-solver/" },
  { id: 46, title: "Permutations", difficulty: "Medium", tags: ["Array", "Backtracking"], url: "https://leetcode.com/problems/permutations/" },
  { id: 47, title: "Permutations II", difficulty: "Medium", tags: ["Array", "Backtracking"], url: "https://leetcode.com/problems/permutations-ii/" },
  { id: 51, title: "N-Queens", difficulty: "Hard", tags: ["Array", "Backtracking"], url: "https://leetcode.com/problems/n-queens/" },
  { id: 52, title: "N-Queens II", difficulty: "Hard", tags: ["Backtracking"], url: "https://leetcode.com/problems/n-queens-ii/" },
  { id: 77, title: "Combinations", difficulty: "Medium", tags: ["Backtracking"], url: "https://leetcode.com/problems/combinations/" },
  { id: 89, title: "Gray Code", difficulty: "Medium", tags: ["Math", "Backtracking", "Bit Manipulation"], url: "https://leetcode.com/problems/gray-code/" },
  { id: 254, title: "Factor Combinations", difficulty: "Medium", tags: ["Backtracking"], url: "https://leetcode.com/problems/factor-combinations/" },
  { id: 291, title: "Word Pattern II", difficulty: "Medium", tags: ["Hash Table", "String", "Backtracking"], url: "https://leetcode.com/problems/word-pattern-ii/" },
  { id: 301, title: "Remove Invalid Parentheses", difficulty: "Hard", tags: ["String", "DFS", "BFS", "Backtracking"], url: "https://leetcode.com/problems/remove-invalid-parentheses/" },
  { id: 320, title: "Generalized Abbreviation", difficulty: "Medium", tags: ["String", "Backtracking", "Bit Manipulation"], url: "https://leetcode.com/problems/generalized-abbreviation/" },
  { id: 351, title: "Android Unlock Patterns", difficulty: "Medium", tags: ["Dynamic Programming", "Backtracking"], url: "https://leetcode.com/problems/android-unlock-patterns/" },
]

const heapProblems: Omit<LeetCodeProblem, 'done' | 'doneAt' | 'notes'>[] = [
  { id: 218, title: "The Skyline Problem", difficulty: "Hard", tags: ["Array", "Divide and Conquer", "Heap", "Line Sweep"], url: "https://leetcode.com/problems/the-skyline-problem/" },
  { id: 253, title: "Meeting Rooms II", difficulty: "Medium", tags: ["Array", "Two Pointers", "Greedy", "Sorting", "Heap"], url: "https://leetcode.com/problems/meeting-rooms-ii/" },
  { id: 264, title: "Ugly Number II", difficulty: "Medium", tags: ["Hash Table", "Math", "Dynamic Programming", "Heap"], url: "https://leetcode.com/problems/ugly-number-ii/" },
  { id: 295, title: "Find Median from Data Stream", difficulty: "Hard", tags: ["Two Pointers", "Design", "Sorting", "Heap", "Data Stream"], url: "https://leetcode.com/problems/find-median-from-data-stream/" },
  { id: 347, title: "Top K Frequent Elements", difficulty: "Medium", tags: ["Array", "Hash Table", "Divide and Conquer", "Sorting", "Heap", "Bucket Sort", "Counting"], url: "https://leetcode.com/problems/top-k-frequent-elements/" },
  { id: 355, title: "Design Twitter", difficulty: "Medium", tags: ["Hash Table", "Linked List", "Design", "Heap"], url: "https://leetcode.com/problems/design-twitter/" },
  { id: 358, title: "Rearrange String k Distance Apart", difficulty: "Hard", tags: ["Hash Table", "String", "Greedy", "Sorting", "Heap", "Counting"], url: "https://leetcode.com/problems/rearrange-string-k-distance-apart/" },
  { id: 373, title: "Find K Pairs with Smallest Sums", difficulty: "Medium", tags: ["Array", "Heap"], url: "https://leetcode.com/problems/find-k-pairs-with-smallest-sums/" },
  { id: 378, title: "Kth Smallest Element in a Sorted Matrix", difficulty: "Medium", tags: ["Array", "Binary Search", "Sorting", "Heap", "Matrix"], url: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/" },
  { id: 407, title: "Trapping Rain Water II", difficulty: "Hard", tags: ["Array", "BFS", "Heap", "Matrix"], url: "https://leetcode.com/problems/trapping-rain-water-ii/" },
  { id: 451, title: "Sort Characters By Frequency", difficulty: "Medium", tags: ["Hash Table", "String", "Sorting", "Heap", "Bucket Sort", "Counting"], url: "https://leetcode.com/problems/sort-characters-by-frequency/" },
  { id: 502, title: "IPO", difficulty: "Hard", tags: ["Array", "Greedy", "Sorting", "Heap"], url: "https://leetcode.com/problems/ipo/" },
  { id: 506, title: "Relative Ranks", difficulty: "Easy", tags: ["Array", "Sorting", "Heap"], url: "https://leetcode.com/problems/relative-ranks/" },
  { id: 621, title: "Task Scheduler", difficulty: "Medium", tags: ["Array", "Hash Table", "Greedy", "Sorting", "Heap", "Counting"], url: "https://leetcode.com/problems/task-scheduler/" },
  { id: 632, title: "Smallest Range Covering Elements from K Lists", difficulty: "Hard", tags: ["Array", "Hash Table", "Greedy", "Sliding Window", "Sorting", "Heap"], url: "https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/" },
  { id: 658, title: "Find K Closest Elements", difficulty: "Medium", tags: ["Array", "Two Pointers", "Binary Search", "Sorting", "Sliding Window", "Heap"], url: "https://leetcode.com/problems/find-k-closest-elements/" },
  { id: 692, title: "Top K Frequent Words", difficulty: "Medium", tags: ["Hash Table", "String", "Trie", "Sorting", "Heap", "Bucket Sort", "Counting"], url: "https://leetcode.com/problems/top-k-frequent-words/" },
  { id: 703, title: "Kth Largest Element in a Stream", difficulty: "Easy", tags: ["Tree", "Design", "Binary Search Tree", "Heap", "Data Stream", "Binary Tree"], url: "https://leetcode.com/problems/kth-largest-element-in-a-stream/" },
  { id: 767, title: "Reorganize String", difficulty: "Medium", tags: ["Hash Table", "String", "Greedy", "Sorting", "Heap", "Counting"], url: "https://leetcode.com/problems/reorganize-string/" },
  { id: 786, title: "K-th Smallest Prime Fraction", difficulty: "Medium", tags: ["Array", "Two Pointers", "Binary Search", "Sorting", "Heap"], url: "https://leetcode.com/problems/k-th-smallest-prime-fraction/" },
]

const bitProblems: Omit<LeetCodeProblem, 'done' | 'doneAt' | 'notes'>[] = [
  { id: 136, title: "Single Number", difficulty: "Easy", tags: ["Array", "Bit Manipulation"], url: "https://leetcode.com/problems/single-number/" },
  { id: 137, title: "Single Number II", difficulty: "Medium", tags: ["Array", "Bit Manipulation"], url: "https://leetcode.com/problems/single-number-ii/" },
  { id: 190, title: "Reverse Bits", difficulty: "Easy", tags: ["Divide and Conquer", "Bit Manipulation"], url: "https://leetcode.com/problems/reverse-bits/" },
  { id: 191, title: "Number of 1 Bits", difficulty: "Easy", tags: ["Divide and Conquer", "Bit Manipulation"], url: "https://leetcode.com/problems/number-of-1-bits/" },
  { id: 201, title: "Bitwise AND of Numbers Range", difficulty: "Medium", tags: ["Bit Manipulation"], url: "https://leetcode.com/problems/bitwise-and-of-numbers-range/" },
  { id: 231, title: "Power of Two", difficulty: "Easy", tags: ["Math", "Bit Manipulation", "Recursion"], url: "https://leetcode.com/problems/power-of-two/" },
  { id: 260, title: "Single Number III", difficulty: "Medium", tags: ["Array", "Bit Manipulation"], url: "https://leetcode.com/problems/single-number-iii/" },
  { id: 318, title: "Maximum Product of Word Lengths", difficulty: "Medium", tags: ["Array", "String", "Bit Manipulation"], url: "https://leetcode.com/problems/maximum-product-of-word-lengths/" },
  { id: 338, title: "Counting Bits", difficulty: "Easy", tags: ["Dynamic Programming", "Bit Manipulation"], url: "https://leetcode.com/problems/counting-bits/" },
  { id: 342, title: "Power of Four", difficulty: "Easy", tags: ["Math", "Bit Manipulation", "Recursion"], url: "https://leetcode.com/problems/power-of-four/" },
  { id: 371, title: "Sum of Two Integers", difficulty: "Medium", tags: ["Math", "Bit Manipulation"], url: "https://leetcode.com/problems/sum-of-two-integers/" },
  { id: 389, title: "Find the Difference", difficulty: "Easy", tags: ["Hash Table", "String", "Bit Manipulation", "Sorting"], url: "https://leetcode.com/problems/find-the-difference/" },
  { id: 393, title: "UTF-8 Validation", difficulty: "Medium", tags: ["Array", "Bit Manipulation"], url: "https://leetcode.com/problems/utf-8-validation/" },
  { id: 398, title: "Random Pick Index", difficulty: "Medium", tags: ["Hash Table", "Math", "Reservoir Sampling", "Randomized"], url: "https://leetcode.com/problems/random-pick-index/" },
  { id: 401, title: "Binary Watch", difficulty: "Easy", tags: ["Backtracking", "Bit Manipulation"], url: "https://leetcode.com/problems/binary-watch/" },
  { id: 405, title: "Convert a Number to Hexadecimal", difficulty: "Easy", tags: ["Math", "Bit Manipulation"], url: "https://leetcode.com/problems/convert-a-number-to-hexadecimal/" },
  { id: 421, title: "Maximum XOR of Two Numbers in an Array", difficulty: "Medium", tags: ["Array", "Hash Table", "Bit Manipulation", "Trie"], url: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/" },
  { id: 461, title: "Hamming Distance", difficulty: "Easy", tags: ["Bit Manipulation"], url: "https://leetcode.com/problems/hamming-distance/" },
  { id: 476, title: "Number Complement", difficulty: "Easy", tags: ["Bit Manipulation"], url: "https://leetcode.com/problems/number-complement/" },
  { id: 477, title: "Total Hamming Distance", difficulty: "Medium", tags: ["Array", "Math", "Bit Manipulation"], url: "https://leetcode.com/problems/total-hamming-distance/" },
  { id: 693, title: "Binary Number with Alternating Bits", difficulty: "Easy", tags: ["Bit Manipulation"], url: "https://leetcode.com/problems/binary-number-with-alternating-bits/" },
  { id: 762, title: "Prime Number of Set Bits in Binary Representation", difficulty: "Easy", tags: ["Math", "Bit Manipulation"], url: "https://leetcode.com/problems/prime-number-of-set-bits-in-binary-representation/" },
  { id: 784, title: "Letter Case Permutation", difficulty: "Medium", tags: ["String", "Backtracking", "Bit Manipulation"], url: "https://leetcode.com/problems/letter-case-permutation/" },
  { id: 832, title: "Flipping an Image", difficulty: "Easy", tags: ["Array", "Two Pointers", "Bit Manipulation"], url: "https://leetcode.com/problems/flipping-an-image/" },
  { id: 861, title: "Score After Flipping Matrix", difficulty: "Medium", tags: ["Array", "Greedy", "Bit Manipulation", "Matrix"], url: "https://leetcode.com/problems/score-after-flipping-matrix/" },
  { id: 868, title: "Binary Gap", difficulty: "Easy", tags: ["Bit Manipulation"], url: "https://leetcode.com/problems/binary-gap/" },
  { id: 898, title: "Bitwise ORs of Subarrays", difficulty: "Medium", tags: ["Array", "Dynamic Programming", "Bit Manipulation"], url: "https://leetcode.com/problems/bitwise-ors-of-subarrays/" },
  { id: 1318, title: "Minimum Flips to Make a OR b Equal to c", difficulty: "Medium", tags: ["Bit Manipulation"], url: "https://leetcode.com/problems/minimum-flips-to-make-a-or-b-equal-to-c/" },
  { id: 1356, title: "Sort Integers by The Number of 1 Bits", difficulty: "Easy", tags: ["Array", "Sorting", "Bit Manipulation", "Counting"], url: "https://leetcode.com/problems/sort-integers-by-the-number-of-1-bits/" },
  { id: 1486, title: "XOR Operation in an Array", difficulty: "Easy", tags: ["Math", "Bit Manipulation"], url: "https://leetcode.com/problems/xor-operation-in-an-array/" },
]

const slidingWindowProblems: Omit<LeetCodeProblem, 'done' | 'doneAt' | 'notes'>[] = [
  { id: 3, title: "Longest Substring Without Repeating Characters", difficulty: "Medium", tags: ["Hash Table", "String", "Sliding Window"], url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
  { id: 30, title: "Substring with Concatenation of All Words", difficulty: "Hard", tags: ["Hash Table", "String", "Sliding Window"], url: "https://leetcode.com/problems/substring-with-concatenation-of-all-words/" },
  { id: 76, title: "Minimum Window Substring", difficulty: "Hard", tags: ["Hash Table", "String", "Sliding Window"], url: "https://leetcode.com/problems/minimum-window-substring/" },
  { id: 159, title: "Longest Substring with At Most Two Distinct Characters", difficulty: "Medium", tags: ["Hash Table", "String", "Sliding Window"], url: "https://leetcode.com/problems/longest-substring-with-at-most-two-distinct-characters/" },
  { id: 209, title: "Minimum Size Subarray Sum", difficulty: "Medium", tags: ["Array", "Binary Search", "Sliding Window"], url: "https://leetcode.com/problems/minimum-size-subarray-sum/" },
  { id: 239, title: "Sliding Window Maximum", difficulty: "Hard", tags: ["Array", "Queue", "Sliding Window", "Heap", "Monotonic Queue"], url: "https://leetcode.com/problems/sliding-window-maximum/" },
  { id: 340, title: "Longest Substring with At Most K Distinct Characters", difficulty: "Medium", tags: ["Hash Table", "String", "Sliding Window"], url: "https://leetcode.com/problems/longest-substring-with-at-most-k-distinct-characters/" },
  { id: 395, title: "Longest Substring with At Least K Repeating Characters", difficulty: "Medium", tags: ["Hash Table", "String", "Divide and Conquer", "Sliding Window"], url: "https://leetcode.com/problems/longest-substring-with-at-least-k-repeating-characters/" },
  { id: 424, title: "Longest Repeating Character Replacement", difficulty: "Medium", tags: ["Hash Table", "String", "Sliding Window"], url: "https://leetcode.com/problems/longest-repeating-character-replacement/" },
  { id: 438, title: "Find All Anagrams in a String", difficulty: "Medium", tags: ["Hash Table", "String", "Sliding Window"], url: "https://leetcode.com/problems/find-all-anagrams-in-a-string/" },
  { id: 480, title: "Sliding Window Median", difficulty: "Hard", tags: ["Array", "Hash Table", "Sliding Window", "Heap", "Ordered Set"], url: "https://leetcode.com/problems/sliding-window-median/" },
  { id: 487, title: "Max Consecutive Ones II", difficulty: "Medium", tags: ["Array", "Dynamic Programming", "Sliding Window"], url: "https://leetcode.com/problems/max-consecutive-ones-ii/" },
  { id: 567, title: "Permutation in String", difficulty: "Medium", tags: ["Hash Table", "Two Pointers", "String", "Sliding Window"], url: "https://leetcode.com/problems/permutation-in-string/" },
  { id: 594, title: "Longest Harmonious Subsequence", difficulty: "Easy", tags: ["Array", "Hash Table", "Sorting", "Sliding Window"], url: "https://leetcode.com/problems/longest-harmonious-subsequence/" },
  { id: 643, title: "Maximum Average Subarray I", difficulty: "Easy", tags: ["Array", "Sliding Window"], url: "https://leetcode.com/problems/maximum-average-subarray-i/" },
  { id: 713, title: "Subarray Product Less Than K", difficulty: "Medium", tags: ["Array", "Sliding Window"], url: "https://leetcode.com/problems/subarray-product-less-than-k/" },
  { id: 718, title: "Maximum Length of Repeated Subarray", difficulty: "Medium", tags: ["Array", "Binary Search", "Dynamic Programming", "Sliding Window", "Rolling Hash", "Hash Function"], url: "https://leetcode.com/problems/maximum-length-of-repeated-subarray/" },
  { id: 727, title: "Minimum Window Subsequence", difficulty: "Hard", tags: ["String", "Dynamic Programming", "Sliding Window"], url: "https://leetcode.com/problems/minimum-window-subsequence/" },
  { id: 904, title: "Fruit Into Baskets", difficulty: "Medium", tags: ["Array", "Hash Table", "Sliding Window"], url: "https://leetcode.com/problems/fruit-into-baskets/" },
  { id: 930, title: "Binary Subarrays With Sum", difficulty: "Medium", tags: ["Array", "Hash Table", "Sliding Window", "Prefix Sum"], url: "https://leetcode.com/problems/binary-subarrays-with-sum/" },
  { id: 992, title: "Subarrays with K Different Integers", difficulty: "Hard", tags: ["Array", "Hash Table", "Sliding Window", "Counting"], url: "https://leetcode.com/problems/subarrays-with-k-different-integers/" },
  { id: 1004, title: "Max Consecutive Ones III", difficulty: "Medium", tags: ["Array", "Binary Search", "Sliding Window", "Prefix Sum"], url: "https://leetcode.com/problems/max-consecutive-ones-iii/" },
  { id: 1052, title: "Grumpy Bookstore Owner", difficulty: "Medium", tags: ["Array", "Sliding Window"], url: "https://leetcode.com/problems/grumpy-bookstore-owner/" },
  { id: 1100, title: "Find K-Length Substrings With No Repeated Characters", difficulty: "Medium", tags: ["Hash Table", "String", "Sliding Window"], url: "https://leetcode.com/problems/find-k-length-substrings-with-no-repeated-characters/" },
  { id: 1151, title: "Minimum Swaps to Group All 1's Together", difficulty: "Medium", tags: ["Array", "Sliding Window"], url: "https://leetcode.com/problems/minimum-swaps-to-group-all-1s-together/" },
  { id: 1176, title: "Diet Plan Performance", difficulty: "Easy", tags: ["Array", "Sliding Window"], url: "https://leetcode.com/problems/diet-plan-performance/" },
  { id: 1208, title: "Get Equal Substrings Within Budget", difficulty: "Medium", tags: ["String", "Binary Search", "Sliding Window", "Prefix Sum"], url: "https://leetcode.com/problems/get-equal-substrings-within-budget/" },
  { id: 1423, title: "Maximum Points You Can Obtain from Cards", difficulty: "Medium", tags: ["Array", "Sliding Window", "Prefix Sum"], url: "https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/" },
  { id: 1456, title: "Maximum Number of Vowels in a Substring of Given Length", difficulty: "Medium", tags: ["String", "Sliding Window"], url: "https://leetcode.com/problems/maximum-number-of-vowels-in-a-substring-of-given-length/" },
  { id: 1695, title: "Maximum Erasure Value", difficulty: "Medium", tags: ["Array", "Hash Table", "Sliding Window"], url: "https://leetcode.com/problems/maximum-erasure-value/" },
]

// Combine all problems, deduplicate by ID, and add done/notes fields
function buildProblems(): LeetCodeProblem[] {
  const all = [
    ...arrayProblems,
    ...stringProblems,
    ...linkedListProblems,
    ...stackQueueProblems,
    ...treeProblems,
    ...graphProblems,
    ...dpProblems,
    ...binarySearchProblems,
    ...backtrackingProblems,
    ...heapProblems,
    ...bitProblems,
    ...slidingWindowProblems,
  ]

  const seen = new Set<number>()
  const unique: LeetCodeProblem[] = []
  for (const p of all) {
    if (!seen.has(p.id)) {
      seen.add(p.id)
      unique.push({ ...p, done: false })
    }
  }

  // Sort by ID
  return unique.sort((a, b) => a.id - b.id)
}

export const LEETCODE_PROBLEMS: LeetCodeProblem[] = buildProblems()

export const LEETCODE_TAGS = [
  "Array", "String", "Hash Table", "Dynamic Programming", "Math",
  "Sorting", "Greedy", "Depth-First Search", "DFS", "BFS",
  "Binary Search", "Tree", "Matrix", "Two Pointers", "Bit Manipulation",
  "Stack", "Heap", "Backtracking", "Graph", "Linked List",
  "Sliding Window", "Union Find", "Trie", "Recursion", "Prefix Sum",
  "Monotonic Stack", "Design", "Simulation"
]

export function getLeetCodeStats(problems: LeetCodeProblem[]) {
  const total = problems.length
  const done = problems.filter(p => p.done).length
  const easy = problems.filter(p => p.difficulty === 'Easy')
  const medium = problems.filter(p => p.difficulty === 'Medium')
  const hard = problems.filter(p => p.difficulty === 'Hard')
  return {
    total,
    done,
    easy: { total: easy.length, done: easy.filter(p => p.done).length },
    medium: { total: medium.length, done: medium.filter(p => p.done).length },
    hard: { total: hard.length, done: hard.filter(p => p.done).length },
  }
}
