import type { Phase, Week, DailyTask, PhaseId } from "@/types"

function makeTask(
  id: string,
  phaseId: PhaseId,
  week: number,
  day: number,
  title: string,
  description: string,
  estimatedHours: number,
  type: DailyTask['type'],
  resource?: DailyTask['resource']
): DailyTask {
  return {
    id,
    phaseId,
    week,
    day,
    title,
    description,
    estimatedHours,
    type,
    resource,
    status: 'pending',
  }
}

// ─── Phase 1: Rust Foundations (Weeks 1–4) ────────────────────────────────────
const phase1Weeks: Week[] = [
  {
    weekNumber: 1,
    phaseWeek: 1,
    phaseId: 1,
    title: "Setup & Rust Basics",
    goal: "Install Rust toolchain, understand Cargo, write your first programs with variables, types, and functions.",
    isCompleted: false,
    tasks: [
      makeTask("p1w1d1", 1, 1, 1, "Install Rust & Cargo Setup", "Install rustup, configure VS Code with rust-analyzer, create first 'Hello World' project, explore cargo commands: build, run, check, fmt, clippy.", 4, "coding", { url: "https://www.udemy.com/course/learn-to-code-with-rust/", label: "Learn to Code with Rust — Section 1", platform: "udemy" }),
      makeTask("p1w1d2", 1, 1, 2, "Variables, Mutability & Data Types", "Learn let/let mut, scalar types (i32, f64, bool, char), type inference, constants, shadowing. Practice in Rust Playground.", 4, "video", { url: "https://www.udemy.com/course/learn-to-code-with-rust/", label: "Learn to Code with Rust — Section 2", platform: "udemy" }),
      makeTask("p1w1d3", 1, 1, 3, "Functions & Control Flow", "Define functions, understand parameters/return types, if/else expressions, loop/while/for, range patterns.", 4, "video", { url: "https://www.udemy.com/course/learn-to-code-with-rust/", label: "Learn to Code with Rust — Section 3", platform: "udemy" }),
      makeTask("p1w1d4", 1, 1, 4, "Compound Types: Tuples & Arrays", "Tuples vs arrays, destructuring, indexing, slices. Build a temperature converter program.", 4, "coding", { url: "https://doc.rust-lang.org/book/ch03-02-data-types.html", label: "The Rust Book — Ch 3.2", platform: "docs" }),
      makeTask("p1w1d5", 1, 1, 5, "The Stack & Heap — Mental Model", "Understand how Rust manages memory: stack vs heap, why this matters for ownership. Read Rust Book Ch 4.1.", 4, "reading", { url: "https://doc.rust-lang.org/book/ch04-01-what-is-ownership.html", label: "The Rust Book — Ch 4.1", platform: "docs" }),
      makeTask("p1w1d6", 1, 1, 6, "Practice: Fibonacci & Prime Sieve", "Implement Fibonacci (iterative + recursive), Sieve of Eratosthenes in Rust. Use cargo test.", 4, "exercise", { url: "https://exercism.org/tracks/rust", label: "Exercism Rust Track", platform: "custom" }),
      makeTask("p1w1d7", 1, 1, 7, "Week 1 Review & Mini Project", "Build a CLI number guessing game using rand crate. Review all week concepts. Write summary notes.", 4, "project", { url: "https://doc.rust-lang.org/book/ch02-00-guessing-game-tutorial.html", label: "Rust Book — Guessing Game", platform: "docs" }),
    ],
  },
  {
    weekNumber: 2,
    phaseWeek: 2,
    phaseId: 1,
    title: "Ownership, Borrowing & References",
    goal: "Master Rust's core memory model: ownership rules, borrowing, references, and slices.",
    isCompleted: false,
    tasks: [
      makeTask("p1w2d1", 1, 2, 1, "Ownership Rules Deep Dive", "The 3 ownership rules. Move semantics, Copy trait. Why String vs &str. Work through Rust Book Ch 4.1–4.2.", 4, "reading", { url: "https://doc.rust-lang.org/book/ch04-01-what-is-ownership.html", label: "Rust Book — Ownership", platform: "docs" }),
      makeTask("p1w2d2", 1, 2, 2, "References & Borrowing", "Immutable vs mutable references, the borrow checker rules, dangling references. Practice fixing borrow errors.", 4, "video", { url: "https://www.udemy.com/course/learn-to-code-with-rust/", label: "Learn to Code with Rust — Borrowing", platform: "udemy" }),
      makeTask("p1w2d3", 1, 2, 3, "Slices: &str and &[T]", "String slices, array slices, slice syntax. Understand why slices are safer than indices.", 4, "coding", { url: "https://doc.rust-lang.org/book/ch04-03-slices.html", label: "Rust Book — Slices", platform: "docs" }),
      makeTask("p1w2d4", 1, 2, 4, "String Types: String vs &str", "Heap-allocated String, string literals, String methods, format! macro, string concatenation. Build string manipulation exercises.", 4, "coding", { url: "https://www.udemy.com/course/learn-to-code-with-rust/", label: "Learn to Code with Rust — Strings", platform: "udemy" }),
      makeTask("p1w2d5", 1, 2, 5, "Clone vs Copy — Understanding the Trait", "Why some types implement Copy (stack-only) vs Clone (heap types). Derive macros: #[derive(Clone, Copy)].", 4, "video", { url: "https://www.udemy.com/course/learn-to-code-with-rust/", label: "Learn to Code with Rust", platform: "udemy" }),
      makeTask("p1w2d6", 1, 2, 6, "Borrow Checker Practice — Fix the Errors", "15 intentionally broken programs. Fix each borrow error. Understand compiler messages.", 4, "exercise", { url: "https://github.com/rust-lang/rustlings", label: "Rustlings Exercises", platform: "github" }),
      makeTask("p1w2d7", 1, 2, 7, "Week 2 Project: Word Counter CLI", "Build a word-count tool that reads a file, returns word frequency map. Use String, &str, slices, references.", 4, "project", { url: "https://doc.rust-lang.org/book/", label: "Rust Book Reference", platform: "docs" }),
    ],
  },
  {
    weekNumber: 3,
    phaseWeek: 3,
    phaseId: 1,
    title: "Structs, Enums & Pattern Matching",
    goal: "Build custom data types with structs and enums, master pattern matching and Option/Result.",
    isCompleted: false,
    tasks: [
      makeTask("p1w3d1", 1, 3, 1, "Structs: Defining & Using", "Struct syntax, field shorthand, struct update syntax, tuple structs, unit structs. Implement methods with impl block.", 4, "video", { url: "https://www.udemy.com/course/learn-to-code-with-rust/", label: "Learn to Code with Rust — Structs", platform: "udemy" }),
      makeTask("p1w3d2", 1, 3, 2, "Methods & Associated Functions", "Difference between &self, &mut self, self. Associated functions (like new). Build a Rectangle struct with area/perimeter methods.", 4, "coding", { url: "https://doc.rust-lang.org/book/ch05-03-method-syntax.html", label: "Rust Book — Methods", platform: "docs" }),
      makeTask("p1w3d3", 1, 3, 3, "Enums & Match Expressions", "Enum variants with data, match arms, exhaustive matching, _ wildcard, match guards. Rust Book Ch 6.", 4, "video", { url: "https://www.udemy.com/course/learn-to-code-with-rust/", label: "Learn to Code with Rust — Enums", platform: "udemy" }),
      makeTask("p1w3d4", 1, 3, 4, "Option<T> — Null Safety in Rust", "Option::Some/None, unwrap/expect/unwrap_or, if let, while let patterns. Replace null-checks with Option.", 4, "coding", { url: "https://doc.rust-lang.org/book/ch06-01-defining-an-enum.html", label: "Rust Book — Option", platform: "docs" }),
      makeTask("p1w3d5", 1, 3, 5, "Result<T, E> — Error Handling Basics", "Result::Ok/Err, match on Result, ? operator, error propagation. Build a file-parsing function with proper errors.", 4, "video", { url: "https://www.udemy.com/course/learn-to-code-with-rust/", label: "Learn to Code with Rust — Result", platform: "udemy" }),
      makeTask("p1w3d6", 1, 3, 6, "Pattern Matching Deep Dive", "Destructuring structs/enums/tuples in match, if let chains, @ bindings, nested patterns.", 4, "exercise", { url: "https://doc.rust-lang.org/book/ch18-00-patterns.html", label: "Rust Book — Patterns", platform: "docs" }),
      makeTask("p1w3d7", 1, 3, 7, "Project: Student Grade Tracker", "Build a struct-based grade tracking app. StudentRecord with name, grades Vec, avg method. Enum for letter grades.", 4, "project", { url: "https://www.udemy.com/course/learn-to-code-with-rust/", label: "Learn to Code with Rust", platform: "udemy" }),
    ],
  },
  {
    weekNumber: 4,
    phaseWeek: 4,
    phaseId: 1,
    title: "Traits, Iterators & Error Handling",
    goal: "Understand trait-based polymorphism, use iterators functionally, and handle errors idiomatically.",
    isCompleted: false,
    tasks: [
      makeTask("p1w4d1", 1, 4, 1, "Traits: Defining & Implementing", "Define custom traits, implement for your types, default implementations, trait bounds. Display/Debug traits.", 4, "video", { url: "https://www.udemy.com/course/learn-to-code-with-rust/", label: "Learn to Code with Rust — Traits", platform: "udemy" }),
      makeTask("p1w4d2", 1, 4, 2, "Iterators & Closures", "Iterator trait, map/filter/fold/collect, closure syntax, move closures, chaining iterators.", 4, "video", { url: "https://www.udemy.com/course/learn-to-code-with-rust/", label: "Learn to Code with Rust — Iterators", platform: "udemy" }),
      makeTask("p1w4d3", 1, 4, 3, "Collections: Vec, HashMap, HashSet", "Vec methods, HashMap insert/get/entry API, HashSet operations. When to use each.", 4, "coding", { url: "https://doc.rust-lang.org/book/ch08-00-common-collections.html", label: "Rust Book — Collections", platform: "docs" }),
      makeTask("p1w4d4", 1, 4, 4, "Error Handling: Box<dyn Error> & thiserror", "Custom error types, Box<dyn Error>, the thiserror crate, anyhow crate. Write robust error handling.", 4, "coding", { url: "https://doc.rust-lang.org/book/ch09-00-error-handling.html", label: "Rust Book — Error Handling", platform: "docs" }),
      makeTask("p1w4d5", 1, 4, 5, "Generics & Type Parameters", "Generic functions, generic structs, multiple type parameters, where clauses. Rust Book Ch 10.", 4, "reading", { url: "https://doc.rust-lang.org/book/ch10-01-syntax.html", label: "Rust Book — Generics", platform: "docs" }),
      makeTask("p1w4d6", 1, 4, 6, "Testing in Rust", "#[test], #[cfg(test)], assert!/assert_eq!, integration tests, doctests. Test your grade tracker.", 4, "exercise", { url: "https://doc.rust-lang.org/book/ch11-00-testing.html", label: "Rust Book — Testing", platform: "docs" }),
      makeTask("p1w4d7", 1, 4, 7, "Phase 1 Capstone: CLI Todo App", "Build a full CLI todo app with: add/remove/complete/list tasks, persist to JSON file, proper error handling, unit tests.", 4, "project", { url: "https://www.udemy.com/course/learn-to-code-with-rust/", label: "Learn to Code with Rust", platform: "udemy" }),
    ],
  },
]

// ─── Phase 2: Rust Advanced (Weeks 5–8) ──────────────────────────────────────
const phase2Weeks: Week[] = [
  {
    weekNumber: 5,
    phaseWeek: 1,
    phaseId: 2,
    title: "Generics, Trait Objects & Lifetimes",
    goal: "Master advanced type-system features: generics, dynamic dispatch with trait objects, and lifetime annotations.",
    isCompleted: false,
    tasks: [
      makeTask("p2w1d1", 2, 5, 1, "Advanced Generics & Monomorphization", "Generic functions/structs/enums, monomorphization cost, associated types vs type parameters. PhantomData.", 4, "video", { url: "https://www.udemy.com/course/rust-programming-master-class-from-beginner-to-expert/", label: "Rust Master Class — Generics", platform: "udemy" }),
      makeTask("p2w1d2", 2, 5, 2, "Advanced Trait Patterns", "Trait bounds, where clauses, supertraits, blanket implementations, From/Into/AsRef/AsMut.", 4, "video", { url: "https://www.udemy.com/course/rust-programming-master-class-from-beginner-to-expert/", label: "Rust Master Class — Advanced Traits", platform: "udemy" }),
      makeTask("p2w1d3", 2, 5, 3, "Trait Objects: dyn Trait", "Static vs dynamic dispatch, vtable, Box<dyn Trait>, dyn Trait in function signatures, object safety.", 4, "coding", { url: "https://doc.rust-lang.org/book/ch17-02-trait-objects.html", label: "Rust Book — Trait Objects", platform: "docs" }),
      makeTask("p2w1d4", 2, 5, 4, "Lifetime Annotations", "What lifetimes mean, 'a syntax, lifetime in function signatures, structs with references, lifetime elision rules.", 4, "video", { url: "https://www.udemy.com/course/rust-programming-master-class-from-beginner-to-expert/", label: "Rust Master Class — Lifetimes", platform: "udemy" }),
      makeTask("p2w1d5", 2, 5, 5, "Advanced Lifetime Scenarios", "Multiple lifetimes, lifetime bounds, 'static lifetime, lifetime with trait objects, NLL (Non-Lexical Lifetimes).", 4, "reading", { url: "https://doc.rust-lang.org/nomicon/lifetimes.html", label: "Rustonomicon — Lifetimes", platform: "docs" }),
      makeTask("p2w1d6", 2, 5, 6, "Practice: Generic Data Structures", "Implement a generic Stack<T>, Queue<T>, and BinaryTree<T> from scratch.", 4, "exercise", { url: "https://exercism.org/tracks/rust", label: "Exercism — Data Structures", platform: "custom" }),
      makeTask("p2w1d7", 2, 5, 7, "Project: Generic Event System", "Build a type-safe event emitter using generics + trait objects. Support multiple event types.", 4, "project", { url: "https://www.udemy.com/course/rust-programming-master-class-from-beginner-to-expert/", label: "Rust Master Class", platform: "udemy" }),
    ],
  },
  {
    weekNumber: 6,
    phaseWeek: 2,
    phaseId: 2,
    title: "Smart Pointers & Interior Mutability",
    goal: "Understand Rust's smart pointer types and interior mutability patterns for shared ownership.",
    isCompleted: false,
    tasks: [
      makeTask("p2w2d1", 2, 6, 1, "Box<T> — Heap Allocation & Indirection", "When to use Box, recursive types, deref coercion, Box for trait objects.", 4, "video", { url: "https://doc.rust-lang.org/book/ch15-01-box.html", label: "Rust Book — Box", platform: "docs" }),
      makeTask("p2w2d2", 2, 6, 2, "Rc<T> & Arc<T> — Reference Counting", "Shared ownership with Rc, atomic reference counting with Arc, when to use which.", 4, "video", { url: "https://www.udemy.com/course/rust-programming-master-class-from-beginner-to-expert/", label: "Rust Master Class — Rc/Arc", platform: "udemy" }),
      makeTask("p2w2d3", 2, 6, 3, "RefCell<T> & Interior Mutability", "The interior mutability pattern, RefCell borrow checking at runtime, Cell<T>, panic on double-borrow.", 4, "coding", { url: "https://doc.rust-lang.org/book/ch15-05-interior-mutability.html", label: "Rust Book — Interior Mutability", platform: "docs" }),
      makeTask("p2w2d4", 2, 6, 4, "Mutex<T> & RwLock<T>", "Thread-safe shared state, Arc<Mutex<T>> pattern, deadlock prevention, RwLock for read-heavy workloads.", 4, "coding", { url: "https://www.udemy.com/course/rust-programming-master-class-from-beginner-to-expert/", label: "Rust Master Class — Mutex", platform: "udemy" }),
      makeTask("p2w2d5", 2, 6, 5, "Deref Trait & Coercions", "Implement Deref, deref coercion rules, * operator, auto-deref in method calls.", 4, "reading", { url: "https://doc.rust-lang.org/book/ch15-02-deref.html", label: "Rust Book — Deref", platform: "docs" }),
      makeTask("p2w2d6", 2, 6, 6, "Drop Trait & RAII", "Custom cleanup with Drop, RAII pattern, std::mem::drop, why you can't call drop manually.", 4, "exercise", { url: "https://doc.rust-lang.org/book/ch15-03-drop.html", label: "Rust Book — Drop", platform: "docs" }),
      makeTask("p2w2d7", 2, 6, 7, "Project: Thread-Safe Cache", "Build an LRU cache with Arc<Mutex<HashMap>> accessible from multiple threads.", 4, "project", { url: "https://www.udemy.com/course/rust-programming-master-class-from-beginner-to-expert/", label: "Rust Master Class", platform: "udemy" }),
    ],
  },
  {
    weekNumber: 7,
    phaseWeek: 3,
    phaseId: 2,
    title: "Async/Await, Tokio & Concurrency",
    goal: "Write asynchronous Rust programs using Tokio, understand futures and concurrency primitives.",
    isCompleted: false,
    tasks: [
      makeTask("p2w3d1", 2, 7, 1, "Async/Await Fundamentals", "async fn, .await, Future trait, executor model. Why async in Rust is different from other languages.", 4, "video", { url: "https://www.udemy.com/course/rust-programming-master-class-from-beginner-to-expert/", label: "Rust Master Class — Async", platform: "udemy" }),
      makeTask("p2w3d2", 2, 7, 2, "Tokio Runtime & Tasks", "tokio::main, tokio::spawn, task handles, JoinHandle, tokio::select!, task cancellation.", 4, "video", { url: "https://tokio.rs/tokio/tutorial", label: "Tokio Tutorial", platform: "docs" }),
      makeTask("p2w3d3", 2, 7, 3, "Channels: mpsc, oneshot, broadcast", "std::sync::mpsc, tokio channels, choosing the right channel type, backpressure.", 4, "coding", { url: "https://tokio.rs/tokio/tutorial/channels", label: "Tokio — Channels", platform: "docs" }),
      makeTask("p2w3d4", 2, 7, 4, "Streams & AsyncRead/Write", "tokio::io traits, BufReader, StreamExt, processing async data streams.", 4, "coding", { url: "https://tokio.rs/tokio/tutorial/io", label: "Tokio — I/O", platform: "docs" }),
      makeTask("p2w3d5", 2, 7, 5, "Error Handling in Async Code", "? operator in async, anyhow in async context, JoinError, handling panics in tasks.", 4, "video", { url: "https://www.udemy.com/course/rust-programming-master-class-from-beginner-to-expert/", label: "Rust Master Class", platform: "udemy" }),
      makeTask("p2w3d6", 2, 7, 6, "Rayon: Data Parallelism", "rayon::par_iter, parallel map/filter/reduce, when to use Rayon vs Tokio.", 4, "exercise", { url: "https://docs.rs/rayon/latest/rayon/", label: "Rayon Docs", platform: "docs" }),
      makeTask("p2w3d7", 2, 7, 7, "Project: Async Web Scraper", "Build async web scraper with reqwest + Tokio. Fetch 20 URLs concurrently, parse HTML, save results.", 4, "project", { url: "https://www.udemy.com/course/rust-programming-master-class-from-beginner-to-expert/", label: "Rust Master Class", platform: "udemy" }),
    ],
  },
  {
    weekNumber: 8,
    phaseWeek: 4,
    phaseId: 2,
    title: "Macros, Unsafe & FFI",
    goal: "Write declarative macros, understand unsafe Rust boundaries, and call C code from Rust.",
    isCompleted: false,
    tasks: [
      makeTask("p2w4d1", 2, 8, 1, "Declarative Macros (macro_rules!)", "macro_rules! syntax, patterns, $expr/$ident/$ty, building your own vec!-like macro.", 4, "video", { url: "https://www.udemy.com/course/rust-programming-master-class-from-beginner-to-expert/", label: "Rust Master Class — Macros", platform: "udemy" }),
      makeTask("p2w4d2", 2, 8, 2, "Procedural Macros", "Custom derive, attribute macros, function-like proc macros. Use syn + quote crates.", 4, "reading", { url: "https://doc.rust-lang.org/reference/procedural-macros.html", label: "Rust Reference — Proc Macros", platform: "docs" }),
      makeTask("p2w4d3", 2, 8, 3, "Unsafe Rust — The Contract", "unsafe blocks, raw pointers, unsafe functions/traits, when unsafe is appropriate. Rustonomicon overview.", 4, "reading", { url: "https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html", label: "Rust Book — Unsafe", platform: "docs" }),
      makeTask("p2w4d4", 2, 8, 4, "FFI — Calling C from Rust", "extern 'C' blocks, #[repr(C)], bindgen tool, libc crate, calling printf from Rust.", 4, "coding", { url: "https://doc.rust-lang.org/nomicon/ffi.html", label: "Rustonomicon — FFI", platform: "docs" }),
      makeTask("p2w4d5", 2, 8, 5, "Performance: Profiling & Benchmarking", "criterion crate for benchmarks, perf/flamegraph basics, SIMD basics, avoid unnecessary allocations.", 4, "coding", { url: "https://www.udemy.com/course/rust-programming-master-class-from-beginner-to-expert/", label: "Rust Master Class — Performance", platform: "udemy" }),
      makeTask("p2w4d6", 2, 8, 6, "Optimization Patterns", "Zero-cost abstractions, inlining, newtype pattern, avoid Box where possible, string interning.", 4, "exercise", { url: "https://nnethercote.github.io/perf-book/", label: "Rust Performance Book", platform: "docs" }),
      makeTask("p2w4d7", 2, 8, 7, "Phase 2 Capstone: HTTP Server", "Build a minimal HTTP/1.1 server from scratch using Tokio with async handlers, routing, middleware concept.", 4, "project", { url: "https://www.udemy.com/course/rust-programming-master-class-from-beginner-to-expert/", label: "Rust Master Class", platform: "udemy" }),
    ],
  },
]

// ─── Phase 3: Ardan Labs Certification (Weeks 9–12) ──────────────────────────
const phase3Weeks: Week[] = [
  {
    weekNumber: 9,
    phaseWeek: 1,
    phaseId: 3,
    title: "Systems Programming & Memory Model",
    goal: "Deep dive into systems programming concepts: memory layout, alignment, low-level operations.",
    isCompleted: false,
    tasks: [
      makeTask("p3w1d1", 3, 9, 1, "Memory Layout & Alignment", "struct layout, repr(C) vs repr(Rust), padding, size_of, align_of, memory layout tools.", 4, "video", { url: "https://www.ardanlabs.com/training/", label: "Ardan Labs — Systems Programming", platform: "ardan" }),
      makeTask("p3w1d2", 3, 9, 2, "The Rust Type System at Depth", "PhantomData, variance, covariance/contravariance, sized/unsized types, fat pointers.", 4, "video", { url: "https://www.ardanlabs.com/training/", label: "Ardan Labs — Type System", platform: "ardan" }),
      makeTask("p3w1d3", 3, 9, 3, "Global State & Lazy Initialization", "std::sync::OnceLock, once_cell, lazy_static. Safe global configuration patterns.", 4, "coding", { url: "https://www.ardanlabs.com/training/", label: "Ardan Labs Training", platform: "ardan" }),
      makeTask("p3w1d4", 3, 9, 4, "Service Patterns in Rust", "Builder pattern, service struct with handlers, dependency injection without DI framework.", 4, "coding", { url: "https://www.ardanlabs.com/training/", label: "Ardan Labs — Service Patterns", platform: "ardan" }),
      makeTask("p3w1d5", 3, 9, 5, "Concurrency Deep Dive", "Send + Sync traits, thread safety proofs, work-stealing, Tokio internals overview.", 4, "reading", { url: "https://www.ardanlabs.com/training/", label: "Ardan Labs — Concurrency", platform: "ardan" }),
      makeTask("p3w1d6", 3, 9, 6, "gRPC in Rust with Tonic", "Protocol Buffers, tonic crate, define service, implement server/client, streaming RPCs.", 4, "coding", { url: "https://github.com/hyperium/tonic", label: "Tonic gRPC", platform: "github" }),
      makeTask("p3w1d7", 3, 9, 7, "Mock Exam: Systems Topics (25q)", "Take 25-question mock focused on memory layout, concurrency, unsafe. Score yourself. Review wrong answers.", 4, "exam", { url: "https://www.ardanlabs.com/training/", label: "Ardan Labs Mock Exam", platform: "ardan" }),
    ],
  },
  {
    weekNumber: 10,
    phaseWeek: 2,
    phaseId: 3,
    title: "Concurrency Patterns & Advanced APIs",
    goal: "Master concurrency patterns used in production Rust systems and the full Ardan curriculum.",
    isCompleted: false,
    tasks: [
      makeTask("p3w2d1", 3, 10, 1, "Thread Pools & Work Queues", "Build a thread pool from scratch. Arc<Mutex<VecDeque>>, worker threads, graceful shutdown.", 4, "coding", { url: "https://www.ardanlabs.com/training/", label: "Ardan Labs — Thread Pools", platform: "ardan" }),
      makeTask("p3w2d2", 3, 10, 2, "Actor Pattern in Rust", "Tokio-based actor model, message passing, supervision, state isolation without shared memory.", 4, "video", { url: "https://www.ardanlabs.com/training/", label: "Ardan Labs — Actor Pattern", platform: "ardan" }),
      makeTask("p3w2d3", 3, 10, 3, "Advanced Error Handling at Scale", "Error hierarchies with thiserror, converting between error types, context propagation with tracing.", 4, "coding", { url: "https://docs.rs/thiserror/latest/thiserror/", label: "thiserror crate", platform: "docs" }),
      makeTask("p3w2d4", 3, 10, 4, "Observability: Tracing & Metrics", "tracing crate, structured logging, spans, tokio-console, metrics with prometheus client.", 4, "video", { url: "https://www.ardanlabs.com/training/", label: "Ardan Labs — Observability", platform: "ardan" }),
      makeTask("p3w2d5", 3, 10, 5, "Testing at Scale: Integration & E2E", "Test organization, test fixtures, mock HTTP servers with wiremock, database test patterns.", 4, "exercise", { url: "https://www.ardanlabs.com/training/", label: "Ardan Labs — Testing", platform: "ardan" }),
      makeTask("p3w2d6", 3, 10, 6, "CI/CD for Rust Projects", "GitHub Actions for Rust: clippy, fmt, test, audit, deny. Cross-compilation targets.", 4, "coding", { url: "https://github.com/actions/starter-workflows", label: "GitHub Actions", platform: "github" }),
      makeTask("p3w2d7", 3, 10, 7, "Mock Exam: Full Ardan Format (50q)", "50-question mock exam covering all Ardan topics. Time: 45 minutes. Review all wrong answers.", 4, "exam", { url: "https://www.ardanlabs.com/training/", label: "Ardan Labs Mock Exam", platform: "ardan" }),
    ],
  },
  {
    weekNumber: 11,
    phaseWeek: 3,
    phaseId: 3,
    title: "Mock Exams & Weak Area Focus",
    goal: "Take full 100-question mock exams, identify weak areas, drill targeted practice.",
    isCompleted: false,
    tasks: [
      makeTask("p3w3d1", 3, 11, 1, "Full Mock Exam #1 (100q/90min)", "Simulated Ardan Rust Certification exam. 100 questions, 90 minutes. No peeking.", 4, "exam", { url: "https://www.ardanlabs.com/certification/", label: "Ardan Labs Certification", platform: "ardan" }),
      makeTask("p3w3d2", 3, 11, 2, "Exam #1 Review & Analysis", "Go through every wrong answer. Categorize by topic. Create flashcards for weak areas.", 4, "exercise", { url: "https://www.ardanlabs.com/certification/", label: "Ardan Labs Certification", platform: "ardan" }),
      makeTask("p3w3d3", 3, 11, 3, "Drill: Ownership & Borrowing (50 questions)", "Focused drilling on ownership, borrowing, lifetimes. These are highest-weight topics on the exam.", 4, "exam", { url: "https://www.ardanlabs.com/certification/", label: "Ardan Labs Certification", platform: "ardan" }),
      makeTask("p3w3d4", 3, 11, 4, "Drill: Concurrency & Async (30 questions)", "Focused drilling on async/await, channels, Arc<Mutex<T>>, Send + Sync.", 4, "exam", { url: "https://www.ardanlabs.com/certification/", label: "Ardan Labs Certification", platform: "ardan" }),
      makeTask("p3w3d5", 3, 11, 5, "Full Mock Exam #2 (100q/90min)", "Second full mock. Compare score to Exam #1. Look for improvement.", 4, "exam", { url: "https://www.ardanlabs.com/certification/", label: "Ardan Labs Certification", platform: "ardan" }),
      makeTask("p3w3d6", 3, 11, 6, "Exam #2 Review & Remediation", "Deep review of persistent weak areas. Reread relevant Rust Book chapters.", 4, "reading", { url: "https://doc.rust-lang.org/book/", label: "The Rust Book", platform: "docs" }),
      makeTask("p3w3d7", 3, 11, 7, "Full Mock Exam #3 (100q/90min)", "Third mock — targeting 85%+ score. You need 80% to pass the real exam.", 4, "exam", { url: "https://www.ardanlabs.com/certification/", label: "Ardan Labs Certification", platform: "ardan" }),
    ],
  },
  {
    weekNumber: 12,
    phaseWeek: 4,
    phaseId: 3,
    title: "Exam Day Preparation",
    goal: "Final preparation, exam logistics, and take the official Ardan Labs Rust Certification.",
    isCompleted: false,
    tasks: [
      makeTask("p3w4d1", 3, 12, 1, "Final Topic Review: Trait System", "All trait-related topics: object safety, blanket impls, orphan rule, coherence. High-yield review.", 4, "reading", { url: "https://doc.rust-lang.org/reference/items/traits.html", label: "Rust Reference — Traits", platform: "docs" }),
      makeTask("p3w4d2", 3, 12, 2, "Final Topic Review: Memory & Lifetimes", "Lifetime elision, 'static, lifetime variance. Write 20 programs from memory with complex lifetimes.", 4, "coding", { url: "https://doc.rust-lang.org/nomicon/", label: "Rustonomicon", platform: "docs" }),
      makeTask("p3w4d3", 3, 12, 3, "Final Mock Exam #4 (100q/75min)", "Tighter time limit. Simulate real exam pressure. Target: 90%.", 4, "exam", { url: "https://www.ardanlabs.com/certification/", label: "Ardan Labs Certification", platform: "ardan" }),
      makeTask("p3w4d4", 3, 12, 4, "Exam Day Checklist & Logistics", "Review exam format, proctoring setup, ID requirements, equipment check. Rest and prepare.", 4, "exercise", { url: "https://www.ardanlabs.com/certification/", label: "Ardan Labs Certification Page", platform: "ardan" }),
      makeTask("p3w4d5", 3, 12, 5, "TAKE THE ARDAN RUST CERTIFICATION EXAM", "Official exam day. 100 questions, 90 minutes, 80% to pass. Certificate + badge on completion.", 4, "exam", { url: "https://www.ardanlabs.com/certification/", label: "Ardan Labs Certification — Take Exam", platform: "ardan" }),
      makeTask("p3w4d6", 3, 12, 6, "Celebrate & Share Your Badge", "Share LinkedIn badge, GitHub profile README update. Post on X/Twitter. Take a rest day.", 2, "exercise", { url: "https://www.linkedin.com/", label: "LinkedIn — Update Profile", platform: "custom" }),
      makeTask("p3w4d7", 3, 12, 7, "Phase 3 Retrospective & Phase 4 Planning", "Write down what worked, what didn't. Set up LeetCode account with Rust as primary language. Create tracking spreadsheet.", 2, "exercise", { url: "https://leetcode.com/", label: "LeetCode — Rust Setup", platform: "leetcode" }),
    ],
  },
]

// ─── Phase 4: LeetCode Grind (Weeks 13–16) ────────────────────────────────────
const phase4Weeks: Week[] = [
  {
    weekNumber: 13,
    phaseWeek: 1,
    phaseId: 4,
    title: "Arrays, Strings & Hash Maps",
    goal: "Solve 231 LeetCode problems in Arrays, Strings, and Hash Maps categories using Rust.",
    isCompleted: false,
    tasks: [
      makeTask("p4w1d1", 4, 13, 1, "Arrays: Two Sum, Best Time to Buy (33 problems)", "Focus: Two pointers, sliding window, prefix sum. Easy: 20 problems. Medium: 13 problems.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=array&difficulty=EASY", label: "LeetCode — Array Easy", platform: "leetcode" }),
      makeTask("p4w1d2", 4, 13, 2, "Array: Sliding Window & Prefix Sum (33 problems)", "Subarray sum, max/min subarray, fixed-size window problems in Rust.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=array&difficulty=MEDIUM", label: "LeetCode — Array Medium", platform: "leetcode" }),
      makeTask("p4w1d3", 4, 13, 3, "Strings: Palindromes & Anagrams (33 problems)", "String manipulation, character frequency, anagram detection, longest palindrome.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=string", label: "LeetCode — String", platform: "leetcode" }),
      makeTask("p4w1d4", 4, 13, 4, "Hash Maps & Sets (33 problems)", "Frequency maps, two-sum with HashMap, group anagrams, LRU cache concept.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=hash-table", label: "LeetCode — Hash Table", platform: "leetcode" }),
      makeTask("p4w1d5", 4, 13, 5, "Two Pointers Pattern (33 problems)", "Valid palindrome, 3Sum, container with most water, remove duplicates.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=two-pointers", label: "LeetCode — Two Pointers", platform: "leetcode" }),
      makeTask("p4w1d6", 4, 13, 6, "Review & Re-solve Hard Array Problems (33 problems)", "Median of two sorted arrays, trapping rain water, jump game II. Understand optimal solutions.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=array&difficulty=HARD", label: "LeetCode — Array Hard", platform: "leetcode" }),
      makeTask("p4w1d7", 4, 13, 7, "Catch-up Day + Rust Idioms for Competitive Coding", "Complete any missed problems. Learn Rust-specific patterns: BTreeMap, BinaryHeap, VecDeque.", 4, "leetcode", { url: "https://leetcode.com/", label: "LeetCode", platform: "leetcode" }),
    ],
  },
  {
    weekNumber: 14,
    phaseWeek: 2,
    phaseId: 4,
    title: "Linked Lists, Stacks, Trees & BST",
    goal: "Solve 231 LeetCode problems on linked list, stack/queue, tree traversal topics.",
    isCompleted: false,
    tasks: [
      makeTask("p4w2d1", 4, 14, 1, "Linked Lists in Rust (33 problems)", "Reverse linked list, merge sorted lists, detect cycle. Rust linked lists are tricky — use Box.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=linked-list", label: "LeetCode — Linked List", platform: "leetcode" }),
      makeTask("p4w2d2", 4, 14, 2, "Stacks & Queues (33 problems)", "Valid parentheses, min stack, implement queue with stacks, daily temperatures.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=stack", label: "LeetCode — Stack", platform: "leetcode" }),
      makeTask("p4w2d3", 4, 14, 3, "Binary Tree Traversal (33 problems)", "Inorder/preorder/postorder, level order BFS, max depth, symmetric tree.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=binary-tree", label: "LeetCode — Binary Tree", platform: "leetcode" }),
      makeTask("p4w2d4", 4, 14, 4, "Binary Search Tree (33 problems)", "Insert/delete/search in BST, validate BST, kth smallest element, BST iterator.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=binary-search-tree", label: "LeetCode — BST", platform: "leetcode" }),
      makeTask("p4w2d5", 4, 14, 5, "Tree: Advanced Patterns (33 problems)", "Path sum, lowest common ancestor, serialize/deserialize, count complete tree nodes.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=tree", label: "LeetCode — Tree", platform: "leetcode" }),
      makeTask("p4w2d6", 4, 14, 6, "Monotonic Stack & Deque (33 problems)", "Largest rectangle in histogram, sliding window maximum, next greater element.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=monotonic-stack", label: "LeetCode — Monotonic Stack", platform: "leetcode" }),
      makeTask("p4w2d7", 4, 14, 7, "Catch-up + Review Rust Tree Patterns", "Complete missed problems. Implement a proper BST in Rust with Box<Option<Node>>.", 4, "leetcode", { url: "https://leetcode.com/", label: "LeetCode", platform: "leetcode" }),
    ],
  },
  {
    weekNumber: 15,
    phaseWeek: 3,
    phaseId: 4,
    title: "Graphs, BFS/DFS & Dynamic Programming",
    goal: "Solve 231 problems on graph traversal and DP foundations.",
    isCompleted: false,
    tasks: [
      makeTask("p4w3d1", 4, 15, 1, "Graph: BFS Patterns (33 problems)", "Word ladder, shortest path, bipartite graph, 01 matrix distance.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=breadth-first-search", label: "LeetCode — BFS", platform: "leetcode" }),
      makeTask("p4w3d2", 4, 15, 2, "Graph: DFS & Backtracking (33 problems)", "Number of islands, clone graph, course schedule, all paths from source.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=depth-first-search", label: "LeetCode — DFS", platform: "leetcode" }),
      makeTask("p4w3d3", 4, 15, 3, "Union Find (Disjoint Set) (33 problems)", "Friend circles, redundant connection, number of connected components, accounts merge.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=union-find", label: "LeetCode — Union Find", platform: "leetcode" }),
      makeTask("p4w3d4", 4, 15, 4, "DP Foundations: 1D DP (33 problems)", "Climbing stairs, house robber, longest increasing subsequence, coin change.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=dynamic-programming", label: "LeetCode — DP", platform: "leetcode" }),
      makeTask("p4w3d5", 4, 15, 5, "DP: 2D DP & Grids (33 problems)", "Unique paths, minimum path sum, edit distance, longest common subsequence.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=dynamic-programming", label: "LeetCode — DP 2D", platform: "leetcode" }),
      makeTask("p4w3d6", 4, 15, 6, "DP: Interval & Sequence DP (33 problems)", "Burst balloons, palindrome partitioning, matrix chain multiplication, word break.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=dynamic-programming", label: "LeetCode — Interval DP", platform: "leetcode" }),
      makeTask("p4w3d7", 4, 15, 7, "Catch-up + Complexity Analysis Practice", "Review Big-O for all solved problems. Implement graph algorithms from scratch in Rust.", 4, "leetcode", { url: "https://leetcode.com/", label: "LeetCode", platform: "leetcode" }),
    ],
  },
  {
    weekNumber: 16,
    phaseWeek: 4,
    phaseId: 4,
    title: "Binary Search, Heaps & Final Sprint",
    goal: "Solve 307 problems on binary search, backtracking, heaps and complete 1000-problem goal.",
    isCompleted: false,
    tasks: [
      makeTask("p4w4d1", 4, 16, 1, "Binary Search Patterns (44 problems)", "Classic binary search, search in rotated array, find first/last position, search 2D matrix.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=binary-search", label: "LeetCode — Binary Search", platform: "leetcode" }),
      makeTask("p4w4d2", 4, 16, 2, "Backtracking (44 problems)", "Permutations, combinations, subsets, N-queens, Sudoku solver, word search.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=backtracking", label: "LeetCode — Backtracking", platform: "leetcode" }),
      makeTask("p4w4d3", 4, 16, 3, "Heaps & Priority Queues (44 problems)", "Kth largest element, top K frequent, merge k sorted lists, find median from stream.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=heap-priority-queue", label: "LeetCode — Heap", platform: "leetcode" }),
      makeTask("p4w4d4", 4, 16, 4, "Bit Manipulation (44 problems)", "Single number, count bits, reverse bits, missing number, power of two.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=bit-manipulation", label: "LeetCode — Bit Manipulation", platform: "leetcode" }),
      makeTask("p4w4d5", 4, 16, 5, "Trie & Advanced Data Structures (44 problems)", "Implement Trie, word search II, design add and search words.", 4, "leetcode", { url: "https://leetcode.com/problemset/?topicSlugs=trie", label: "LeetCode — Trie", platform: "leetcode" }),
      makeTask("p4w4d6", 4, 16, 6, "Hard Problems Sprint (44 problems)", "Attack 44 Hard problems from mixed categories. Quality over speed here.", 4, "leetcode", { url: "https://leetcode.com/problemset/?difficulty=HARD", label: "LeetCode — Hard", platform: "leetcode" }),
      makeTask("p4w4d7", 4, 16, 7, "1000 Problems Complete! Review & Celebrate", "Verify 1000 problems done. Review the 50 most educational solutions. Prepare for Solana phase.", 3, "exercise", { url: "https://neetcode.io/", label: "NeetCode — Review", platform: "custom" }),
    ],
  },
]

// ─── Phase 5: Solana + Anchor (Weeks 17–20) ───────────────────────────────────
const phase5Weeks: Week[] = [
  {
    weekNumber: 17,
    phaseWeek: 1,
    phaseId: 5,
    title: "Solana Architecture & Accounts Model",
    goal: "Understand Solana's unique architecture: accounts, programs, runtime, and transaction model.",
    isCompleted: false,
    tasks: [
      makeTask("p5w1d1", 5, 17, 1, "Solana Overview & Architecture", "Proof of History, Tower BFT, Turbine, Gulf Stream. How Solana achieves 65k TPS. Architecture overview.", 4, "reading", { url: "https://docs.solanalabs.com/consensus/synchronization", label: "Solana Docs — Architecture", platform: "docs" }),
      makeTask("p5w1d2", 5, 17, 2, "Accounts Model Deep Dive", "Everything is an account. Account structure (data, lamports, owner, executable). System program, rent, account creation.", 4, "video", { url: "https://docs.solanalabs.com/terminology#account", label: "Solana Docs — Accounts", platform: "docs" }),
      makeTask("p5w1d3", 5, 17, 3, "Programs & Instructions", "Program structure, instruction format, program IDs, sysvar accounts. Difference from EVM smart contracts.", 4, "reading", { url: "https://solana.com/docs/core/programs", label: "Solana Docs — Programs", platform: "docs" }),
      makeTask("p5w1d4", 5, 17, 4, "Transactions & Signers", "Transaction anatomy, multiple instructions, compute units, transaction fees, priority fees.", 4, "coding", { url: "https://solana.com/docs/core/transactions", label: "Solana Docs — Transactions", platform: "docs" }),
      makeTask("p5w1d5", 5, 17, 5, "Setup: Solana CLI & Local Validator", "Install Solana CLI, set up localnet, airdrop SOL, explore CLI commands, deploy a native program.", 4, "coding", { url: "https://docs.solanalabs.com/cli/install", label: "Solana CLI Setup", platform: "docs" }),
      makeTask("p5w1d6", 5, 17, 6, "web3.js Basics — Client Side", "Connect to cluster, create keypair, query account info, send SOL transfer, parse transaction logs.", 4, "coding", { url: "https://solana-labs.github.io/solana-web3.js/", label: "Solana web3.js", platform: "docs" }),
      makeTask("p5w1d7", 5, 17, 7, "Project: SOL Transfer CLI", "Build a CLI tool in Rust that: creates wallets, checks balances, transfers SOL, shows transaction details.", 4, "project", { url: "https://docs.solanalabs.com/cli/", label: "Solana CLI Docs", platform: "docs" }),
    ],
  },
  {
    weekNumber: 18,
    phaseWeek: 2,
    phaseId: 5,
    title: "Anchor Framework Fundamentals",
    goal: "Build Solana programs using the Anchor framework — accounts, instructions, and PDAs.",
    isCompleted: false,
    tasks: [
      makeTask("p5w2d1", 5, 18, 1, "Anchor Setup & First Program", "Install Anchor CLI, anchor init, program structure, #[program] macro, deploy to localnet.", 4, "coding", { url: "https://www.anchor-lang.com/docs/installation", label: "Anchor Book — Installation", platform: "docs" }),
      makeTask("p5w2d2", 5, 18, 2, "Anchor Accounts: #[account] & #[derive(Accounts)]", "Account validation macros, Account<'info, T>, Signer, Program, SystemAccount, init constraint.", 4, "video", { url: "https://www.anchor-lang.com/docs/account-types", label: "Anchor — Account Types", platform: "docs" }),
      makeTask("p5w2d3", 5, 18, 3, "PDAs — Program Derived Addresses", "How PDAs are derived, seeds, bump, find_program_address vs create_program_address. Seeds in Anchor.", 4, "coding", { url: "https://solana.com/docs/core/pda", label: "Solana Docs — PDAs", platform: "docs" }),
      makeTask("p5w2d4", 5, 18, 4, "Anchor Instructions & Context", "Context<T>, remaining_accounts, instruction data, multiple instructions in one program.", 4, "coding", { url: "https://www.anchor-lang.com/docs/instructions", label: "Anchor — Instructions", platform: "docs" }),
      makeTask("p5w2d5", 5, 18, 5, "Anchor Constraints & Validation", "has_one, constraint, address, mut, close, seeds, bump constraints. Security via constraints.", 4, "reading", { url: "https://www.anchor-lang.com/docs/account-constraints", label: "Anchor — Constraints", platform: "docs" }),
      makeTask("p5w2d6", 5, 18, 6, "Anchor Events & Errors", "emit! macro, event listening on client, custom error codes with #[error_code], error messages.", 4, "coding", { url: "https://www.anchor-lang.com/docs/errors", label: "Anchor — Errors", platform: "docs" }),
      makeTask("p5w2d7", 5, 18, 7, "Project: Anchor Counter Program", "Build a counter program: initialize, increment, decrement, reset. Add access control. Full test suite.", 4, "project", { url: "https://www.anchor-lang.com/docs/quickstart/local", label: "Anchor Quickstart", platform: "docs" }),
    ],
  },
  {
    weekNumber: 19,
    phaseWeek: 3,
    phaseId: 5,
    title: "CPIs, Token Program & SPL Tokens",
    goal: "Master cross-program invocations and build programs that interact with the SPL Token program.",
    isCompleted: false,
    tasks: [
      makeTask("p5w3d1", 5, 19, 1, "Cross-Program Invocations (CPIs)", "invoke vs invoke_signed, passing accounts in CPI, signed CPIs with PDAs, CPI in Anchor with CpiContext.", 4, "coding", { url: "https://solana.com/docs/core/cpi", label: "Solana Docs — CPI", platform: "docs" }),
      makeTask("p5w3d2", 5, 19, 2, "SPL Token Program — Mint & Accounts", "Token mint account, token account (ATA), mint authority, freeze authority, token decimals.", 4, "video", { url: "https://spl.solana.com/token", label: "SPL Token Docs", platform: "docs" }),
      makeTask("p5w3d3", 5, 19, 3, "Minting & Transferring SPL Tokens", "Create mint, create ATA, mint tokens, transfer tokens, approve delegate, revoke, burn.", 4, "coding", { url: "https://www.anchor-lang.com/docs/spl-tokens", label: "Anchor — SPL Tokens", platform: "docs" }),
      makeTask("p5w3d4", 5, 19, 4, "Token-2022: New Token Standard", "Extensions: transfer fees, confidential transfers, interest-bearing, permanent delegate, non-transferable.", 4, "reading", { url: "https://spl.solana.com/token-2022", label: "Token-2022 Docs", platform: "docs" }),
      makeTask("p5w3d5", 5, 19, 5, "NFTs on Solana: Metaplex Overview", "Metaplex protocol, metadata program, master edition, NFT standard, collection standard.", 4, "reading", { url: "https://developers.metaplex.com/", label: "Metaplex Docs", platform: "docs" }),
      makeTask("p5w3d6", 5, 19, 6, "Build: Token Vault Program", "Program that accepts SPL tokens, holds them in PDA vault, allows owner to withdraw.", 4, "coding", { url: "https://www.anchor-lang.com/docs/", label: "Anchor Docs", platform: "docs" }),
      makeTask("p5w3d7", 5, 19, 7, "Project: SPL Token Launch Program", "Full token launch: create mint, distribute initial supply, set up liquidity, vesting schedule via PDA.", 4, "project", { url: "https://solana.com/developers", label: "Solana Developers", platform: "docs" }),
    ],
  },
  {
    weekNumber: 20,
    phaseWeek: 4,
    phaseId: 5,
    title: "Testing, Security & Production Patterns",
    goal: "Write comprehensive tests for Anchor programs and apply security best practices.",
    isCompleted: false,
    tasks: [
      makeTask("p5w4d1", 5, 20, 1, "Anchor Testing with Mocha/Chai", "anchor test setup, TypeScript client, BN.js for u64, account fetching, asserting state.", 4, "coding", { url: "https://www.anchor-lang.com/docs/testing/basics", label: "Anchor — Testing", platform: "docs" }),
      makeTask("p5w4d2", 5, 20, 2, "Bankrun: Fast Local Testing", "solana-bankrun for lightweight testing, process_transaction, advance_clock, simulate scenarios.", 4, "video", { url: "https://kevinheavey.github.io/solana-bankrun/", label: "Solana Bankrun", platform: "docs" }),
      makeTask("p5w4d3", 5, 20, 3, "Common Solana Security Vulnerabilities", "Account owner check, signer check, PDA seed collision, integer overflow, unauthorized CPI.", 4, "reading", { url: "https://www.sec3.dev/blog/how-to-audit-solana-smart-contracts-part-1", label: "sec3 — Solana Security", platform: "custom" }),
      makeTask("p5w4d4", 5, 20, 4, "Anchor Security: Checks & Guards", "Correct use of constraints, account type checks, has_one vs manual checks, reentrancy in Solana.", 4, "reading", { url: "https://docs.coral-xyz.com/", label: "Anchor Security Guide", platform: "docs" }),
      makeTask("p5w4d5", 5, 20, 5, "Performance: Compute Units Optimization", "Compute budget, measure CU usage, optimize account loading order, avoid unnecessary CPIs.", 4, "coding", { url: "https://solana.com/docs/programs/limitations", label: "Solana Program Limitations", platform: "docs" }),
      makeTask("p5w4d6", 5, 20, 6, "Deployment: Devnet & Mainnet", "anchor deploy to devnet, upgrade authority, program buffer, close program, versioning strategy.", 4, "coding", { url: "https://www.anchor-lang.com/docs/deployment", label: "Anchor Deployment", platform: "docs" }),
      makeTask("p5w4d7", 5, 20, 7, "Phase 5 Capstone: Mini DEX", "Build a simple constant product AMM with Anchor: initialize pool, add liquidity, swap. Full tests.", 4, "project", { url: "https://www.anchor-lang.com/docs/", label: "Anchor Docs", platform: "docs" }),
    ],
  },
]

// Helper to generate remaining phase weeks with consistent pattern
function makeSimpleWeek(
  weekNumber: number,
  phaseWeek: number,
  phaseId: PhaseId,
  title: string,
  goal: string,
  dayTitles: string[],
  platform: DailyTask['resource'] extends { platform: infer P } | undefined ? P : never,
  resourceUrl: string,
  resourceLabel: string,
  type: DailyTask['type'] = 'coding'
): Week {
  const platformTyped = platform as 'udemy' | 'ardan' | 'leetcode' | 'github' | 'docs' | 'youtube' | 'custom'
  return {
    weekNumber,
    phaseWeek,
    phaseId,
    title,
    goal,
    isCompleted: false,
    tasks: dayTitles.map((dayTitle, i) =>
      makeTask(
        `p${phaseId}w${phaseWeek}d${i + 1}`,
        phaseId,
        phaseWeek,
        i + 1,
        dayTitle,
        `${goal} — Day ${i + 1}: ${dayTitle}`,
        4,
        type,
        { url: resourceUrl, label: resourceLabel, platform: platformTyped }
      )
    ),
  }
}

// ─── Phase 6: Solana Smart Contracts (Weeks 21–28) ───────────────────────────
const phase6Weeks: Week[] = [
  makeSimpleWeek(21, 1, 6, "DeFi Primitives: AMM & Liquidity Pools", "Build an automated market maker with constant product formula (x*y=k).",
    ["AMM Math: x*y=k formula", "Pool state account design", "Add liquidity instruction", "Remove liquidity instruction", "Swap instruction with price impact", "Fee collection & LP tokens", "Full AMM integration tests"],
    "docs", "https://solana.com/developers", "Solana Developers", "coding"),
  makeSimpleWeek(22, 2, 6, "AMM Advanced: Price Oracle & Flash Loans", "Add oracle price feeds and flash loan capability to the AMM.",
    ["TWAP oracle implementation", "Price manipulation resistance", "Flash loan: borrow & repay in one tx", "Flash loan fee mechanism", "Arbitrage simulation", "Front-running protection", "AMM security audit checklist"],
    "docs", "https://docs.switchboard.xyz/", "Switchboard Oracle Docs", "coding"),
  makeSimpleWeek(23, 3, 6, "Lending Protocol: Core Logic", "Build a lending/borrowing protocol with interest rate model.",
    ["Lending pool state design", "Deposit collateral instruction", "Borrow against collateral", "Interest rate model (linear/kinked)", "Liquidation condition logic", "Repay loan instruction", "Withdraw collateral instruction"],
    "docs", "https://solana.com/developers", "Solana — DeFi Examples", "coding"),
  makeSimpleWeek(24, 4, 6, "Lending Protocol: Safety & Liquidations", "Add liquidation engine, price-based safety checks, and protocol fees.",
    ["Health factor calculation", "Liquidation bonus mechanics", "Oracle price integration", "Bad debt handling", "Protocol fee treasury", "Emergency pause mechanism", "Full lending protocol tests"],
    "docs", "https://solana.com/developers", "Solana Developers", "coding"),
  makeSimpleWeek(25, 5, 6, "NFT Programs: Mint & Metadata", "Build a custom NFT program with metadata, collection, and royalties.",
    ["NFT mint program structure", "Metadata account with Metaplex", "On-chain royalty enforcement", "Collection verification", "Update authority controls", "Burn NFT instruction", "NFT marketplace listing"],
    "custom", "https://developers.metaplex.com/", "Metaplex Developers", "coding"),
  makeSimpleWeek(26, 6, 6, "NFT Marketplace: Listing & Trading", "Build NFT marketplace with listing, bidding, and royalty distribution.",
    ["List NFT for sale (PDA escrow)", "Cancel listing", "Execute purchase (CPI to token)", "Auction: English auction logic", "Bid/cancel-bid instructions", "Royalty split on sale", "Marketplace fee collection"],
    "custom", "https://developers.metaplex.com/", "Metaplex Docs", "coding"),
  makeSimpleWeek(27, 7, 6, "Security Auditing: Vulnerability Patterns", "Learn common Solana smart contract vulnerabilities and how to prevent them.",
    ["Owner checks & account validation", "Signer authorization patterns", "PDA seed manipulation attacks", "Integer overflow/underflow prevention", "Reentrancy in multi-instruction txs", "Anchor constraint audit checklist", "Full program audit walkthrough"],
    "custom", "https://github.com/coral-xyz/anchor/blob/master/SECURITY.md", "Anchor Security", "reading"),
  makeSimpleWeek(28, 8, 6, "Production Hardening & Phase 6 Capstone", "Harden your programs for production and build a full DeFi protocol.",
    ["Upgrade authority best practices", "Multi-sig for admin actions", "Compute unit budget optimization", "Error handling & logging", "Devnet deployment & testing", "Mainnet readiness checklist", "Phase 6 Capstone: Full DeFi suite deploy"],
    "docs", "https://solana.com/developers", "Solana Developers", "project"),
]

// ─── Phase 7: 10 Solana Projects (Weeks 29–32) ────────────────────────────────
const phase7Weeks: Week[] = [
  makeSimpleWeek(29, 1, 7, "Projects 1–2: Token Launch & NFT Mint", "Build and deploy your first two portfolio projects.",
    ["Token Launch: SPL token with vesting PDA", "Token Launch: Distribution logic", "Token Launch: Deploy & test devnet", "NFT Mint: Collection initialization", "NFT Mint: Mint instruction with Metaplex", "NFT Mint: Royalties & update auth", "Both projects: README & GitHub"],
    "docs", "https://solana.com/developers", "Solana Developers", "project"),
  makeSimpleWeek(30, 2, 7, "Projects 3–5: DEX, Staking, DAO", "Build three mid-complexity DeFi projects.",
    ["DEX: AMM with constant product", "DEX: Frontend with @solana/wallet-adapter", "Staking: Lock tokens, earn rewards by time", "Staking: Early withdrawal penalty", "DAO: Governance token + proposal creation", "DAO: Vote instruction, quorum check", "DAO: Execution after vote passes"],
    "docs", "https://solana.com/developers", "Solana Developers", "project"),
  makeSimpleWeek(31, 3, 7, "Projects 6–8: Escrow, Lending, Lottery", "Build three advanced DeFi projects.",
    ["Escrow: Safe P2P token swap", "Escrow: Time-locked release", "Lending: Deposit/borrow/repay cycle", "Lending: Interest accrual model", "Lottery: VRF randomness with Switchboard", "Lottery: Ticket purchase & winner selection", "Deploy all three to devnet"],
    "docs", "https://solana.com/developers", "Solana Developers", "project"),
  makeSimpleWeek(32, 4, 7, "Projects 9–10: Bridge & ZK+Solana", "Build your most ambitious Solana projects.",
    ["Bridge: Wormhole SDK integration", "Bridge: Lock-and-mint pattern", "Bridge: Cross-chain message passing", "ZK+Solana: Groth16 verifier on Solana", "ZK+Solana: Private transaction circuit", "ZK+Solana: Full proof pipeline", "Portfolio polish: README, deploy, demo video"],
    "docs", "https://docs.wormhole.com/", "Wormhole Docs", "project"),
]

// ─── Phase 8: Price Oracle Blockchain (Weeks 33–36) ──────────────────────────
const phase8Weeks: Week[] = [
  makeSimpleWeek(33, 1, 8, "P2P Networking with libp2p", "Build the networking layer of your custom blockchain.",
    ["libp2p: Node identity & keypairs", "Swarm & transport setup", "Peer discovery with Kademlia DHT", "Gossipsub for message broadcasting", "Request/response protocol", "Peer store & connection management", "P2P integration test: 3-node network"],
    "docs", "https://libp2p.io/", "libp2p Documentation", "coding"),
  makeSimpleWeek(34, 2, 8, "Block Structure & Transaction Model", "Design and implement the blockchain data structures.",
    ["Block header: hash, prev_hash, timestamp", "Merkle tree implementation in Rust", "Transaction model: from/to/amount/sig", "ECDSA signing with k256 crate", "Block validation logic", "Chain state: HashMap<Hash, Block>", "Mempool: pending transaction queue"],
    "github", "https://github.com/topics/blockchain-rust", "Blockchain Rust Examples", "coding"),
  makeSimpleWeek(35, 3, 8, "Consensus: Proof of Authority", "Implement a simplified PoA consensus mechanism.",
    ["Validator set: authorized block producers", "Round-robin block proposal", "Block signature threshold (2/3+1)", "Fork choice rule: heaviest chain", "Sync protocol: request missing blocks", "Slash conditions for misbehavior", "Consensus integration test"],
    "docs", "https://tokio.rs/", "Tokio Async Runtime", "coding"),
  makeSimpleWeek(36, 4, 8, "Price Oracle & REST API", "Add the price oracle functionality and external interface.",
    ["Price feed aggregation logic", "Median price calculation", "Oracle submit_price instruction", "Aggregator smart contract logic", "REST API: GET /blocks, /txs, /price", "Block explorer HTML page", "End-to-end: 3 nodes + price oracle running"],
    "docs", "https://docs.rs/axum/latest/axum/", "Axum Web Framework", "project"),
]

// ─── Phase 9: ZK Learning & Building (Weeks 37–44) ────────────────────────────
const phase9Weeks: Week[] = [
  makeSimpleWeek(37, 1, 9, "ZK Fundamentals: Proofs & Properties", "Understand the theoretical foundations of zero-knowledge proof systems.",
    ["What is a ZKP: completeness, soundness, ZK", "Interactive vs non-interactive proofs", "Fiat-Shamir transform", "Sigma protocols (Schnorr)", "zk-SNARKs vs zk-STARKs comparison", "Applications: privacy, scaling, identity", "ZK math foundations: modular arithmetic"],
    "custom", "https://zk-learning.org/", "ZK Learning (Berkeley MOOC)", "reading"),
  makeSimpleWeek(38, 2, 9, "Math: Finite Fields & Elliptic Curves", "Master the mathematical primitives underlying ZK systems.",
    ["Finite fields: Fp arithmetic", "Field extensions: Fp2, Fp12", "Elliptic curve: point addition/doubling", "Scalar multiplication: double-and-add", "Pairings: Weil & Tate", "BN254 curve (used by Groth16)", "Polynomial commitment basics"],
    "custom", "https://rareskills.io/zk-book", "RareSkills ZK Book", "reading"),
  makeSimpleWeek(39, 3, 9, "zk-SNARKs: R1CS, QAP & Groth16", "Understand the complete Groth16 proving system from circuit to proof.",
    ["R1CS: rank-1 constraint system", "Arithmetic circuits to R1CS", "QAP: quadratic arithmetic programs", "Groth16 setup: proving + verification key", "Toxic waste in trusted setup", "Proof: (A, B, C) elliptic curve points", "Verify: pairing equation check"],
    "custom", "https://zk-learning.org/", "ZK Learning MOOC", "reading"),
  makeSimpleWeek(40, 4, 9, "Circom: Circuit Programming", "Write arithmetic circuits in Circom language.",
    ["Circom syntax: signals, constraints, components", "First circuit: hash preimage proof", "Comparators & logic gates", "MiMC hash circuit", "Merkle tree membership circuit", "Range proof circuit", "circom compile + witness generation"],
    "custom", "https://docs.circom.io/", "Circom Documentation", "coding"),
  makeSimpleWeek(41, 5, 9, "SnarkJS: Proofs & Solidity Verifier", "Generate Groth16 proofs and deploy verifier contracts.",
    ["snarkjs setup ceremony (Powers of Tau)", "Groth16 key generation", "Generate witness & proof", "Verify proof with snarkjs verify", "Export Solidity verifier contract", "Deploy verifier to local Hardhat network", "Test full proof pipeline"],
    "github", "https://github.com/iden3/snarkjs", "SnarkJS GitHub", "coding"),
  makeSimpleWeek(42, 6, 9, "Build: zkRollup Prototype", "Build a ZK rollup that batches transactions with ZK validity proofs.",
    ["zkRollup architecture: sequencer, prover, verifier", "State tree: Merkle tree of balances", "Transaction circuit: signature + balance check", "Batch multiple txs in one proof", "On-chain verifier contract", "State root update on-chain", "Full zkRollup demo: deposit, transfer, withdraw"],
    "custom", "https://0xparc.org/", "0xPARC Learning", "project"),
  makeSimpleWeek(43, 7, 9, "Build: zkDEX — Private Swaps", "Build a privacy-preserving DEX using ZK proofs.",
    ["zkDEX architecture: confidential amounts", "Nullifier tree for double-spend prevention", "Circuit: prove valid swap without revealing amounts", "Commitment scheme: Pedersen hash", "On-chain matching engine", "ZK proof submission + verification", "End-to-end zkDEX demo"],
    "custom", "https://aztec.network/", "Aztec Network Docs", "project"),
  makeSimpleWeek(44, 8, 9, "Noir Language & Halo2 Intro", "Explore alternative ZK frameworks and build a ZK identity system.",
    ["Noir language syntax (Aztec)", "First Noir circuit: membership proof", "Nargo CLI: compile, prove, verify", "Halo2 overview: PLONKish circuits", "ZK identity: prove attributes without revealing", "ZK age verification circuit", "Phase 9 retrospective & ZK portfolio"],
    "custom", "https://noir-lang.org/", "Noir Language", "coding"),
]

// ─── Phase 10: Certifications & Job Hunt (Weeks 45–48) ───────────────────────
const phase10Weeks: Week[] = [
  makeSimpleWeek(45, 1, 10, "Rust Foundation Certification Prep", "Prepare for and take the Rust Foundation certification exam.",
    ["Review Rust Foundation exam format", "Topic audit: ownership, traits, async", "Full mock exam (Rust Foundation format)", "Weak areas intensive review", "Code exercises: timed challenges", "Final mock exam — target 90%+", "TAKE Rust Foundation Certification"],
    "custom", "https://foundation.rust-lang.org/", "Rust Foundation", "exam"),
  makeSimpleWeek(46, 2, 10, "ZK Certification & Portfolio Polish", "Complete ZK learning path certifications and polish your GitHub portfolio.",
    ["RareSkills ZK completion certificate", "Berkeley ZK MOOC NFT certificate (if available)", "GitHub: all 10 Solana projects with READMEs", "Deploy 3 projects to devnet with live links", "Write blog post: 'I built a zkRollup in 2 months'", "Record 2-min demo videos per project", "Portfolio website or GitHub profile README"],
    "custom", "https://rareskills.io/", "RareSkills ZK", "project"),
  makeSimpleWeek(47, 3, 10, "CV, LinkedIn & Job Applications",
    "Write your technical CV, update LinkedIn, and start applying systematically.",
    ["CV writing: Rust + Solana + ZK focus", "LinkedIn headline + about section overhaul", "Cold outreach template: Web3 companies", "Apply Day 1: 3 jobs (web3.career)", "Apply Day 2: 3 jobs (wellfound.com)", "Apply Day 3: 3 jobs (remote3.io)", "Apply Day 4-7: 3 jobs/day + follow-ups"],
    "custom", "https://web3.career/", "web3.career Jobs", "exercise"),
  makeSimpleWeek(48, 4, 10, "Technical Interviews & Negotiation",
    "Ace Rust technical interviews, system design, and negotiate your salary.",
    ["Rust interview: common questions & answers", "Live coding: solve 5 Rust problems in 45 min", "System design: design a Solana DEX backend", "System design: design a ZK proof service", "Behavioral interviews: STAR format", "Salary negotiation: research + tactics", "You did it — accept an offer and celebrate!"],
    "custom", "https://web3.career/", "web3.career", "exercise"),
]

// ─── Assemble All Phases ──────────────────────────────────────────────────────
export const PHASES: Phase[] = [
  {
    id: 1,
    name: "Rust Foundations",
    shortName: "Rust Basics",
    duration: "1 month",
    totalWeeks: 4,
    description: "Build a solid foundation in Rust: ownership, borrowing, structs, enums, iterators, and error handling. Using Udemy's 'Learn to Code with Rust'.",
    goal: "Write idiomatic Rust code confidently and understand the ownership model completely.",
    color: "#F97316",
    icon: "🦀",
    skills: ["Ownership", "Borrowing", "Structs", "Enums", "Traits", "Iterators", "Error Handling"],
    weeks: phase1Weeks,
    status: "active",
  },
  {
    id: 2,
    name: "Rust Advanced",
    shortName: "Rust Advanced",
    duration: "1 month",
    totalWeeks: 4,
    description: "Deep dive into advanced Rust: generics, lifetimes, smart pointers, async/await, macros, and unsafe Rust. Using 'Rust Programming Master Class'.",
    goal: "Write production-quality async Rust with generics, smart pointers, and macro patterns.",
    color: "#F59E0B",
    icon: "⚙️",
    skills: ["Generics", "Lifetimes", "Smart Pointers", "Async/Await", "Tokio", "Macros", "Unsafe"],
    weeks: phase2Weeks,
    status: "locked",
  },
  {
    id: 3,
    name: "Ardan Labs Rust Cert",
    shortName: "Ardan Cert",
    duration: "1 month",
    totalWeeks: 4,
    description: "Systems programming deep dive with Ardan Labs curriculum. Take and pass the Ardan Labs Rust Certification (100q, 90min, 80%+ to pass, $99).",
    goal: "Pass the Ardan Labs Rust Certification exam on the first attempt.",
    color: "#EF4444",
    icon: "🏆",
    skills: ["Systems Programming", "Memory Layout", "Concurrency", "gRPC", "Service Patterns"],
    weeks: phase3Weeks,
    status: "locked",
  },
  {
    id: 4,
    name: "LeetCode Grind",
    shortName: "LeetCode",
    duration: "1 month",
    totalWeeks: 4,
    description: "Solve 1000 LeetCode problems in Rust at 33/day. Build algorithmic thinking for technical interviews at top blockchain companies.",
    goal: "Complete 1000 LeetCode problems using Rust, achieving fluency in data structures and algorithms.",
    color: "#EAB308",
    icon: "🧮",
    skills: ["Algorithms", "Data Structures", "BFS/DFS", "Dynamic Programming", "Binary Search"],
    weeks: phase4Weeks,
    status: "locked",
  },
  {
    id: 5,
    name: "Solana + Anchor",
    shortName: "Solana Basics",
    duration: "1 month",
    totalWeeks: 4,
    description: "Learn Solana's account model, Anchor framework, PDAs, CPIs, and SPL tokens. Deploy your first on-chain programs.",
    goal: "Deploy functional Solana programs using Anchor with proper testing and security.",
    color: "#8B5CF6",
    icon: "◎",
    skills: ["Solana Accounts", "Anchor", "PDAs", "CPIs", "SPL Tokens", "Testing"],
    weeks: phase5Weeks,
    status: "locked",
  },
  {
    id: 6,
    name: "Solana Smart Contracts",
    shortName: "Solana DeFi",
    duration: "2 months",
    totalWeeks: 8,
    description: "Deep Solana development: AMMs, lending protocols, NFT programs, and security auditing. Build production-quality DeFi contracts.",
    goal: "Build and audit production-quality DeFi protocols on Solana.",
    color: "#7C3AED",
    icon: "🔐",
    skills: ["AMM", "Lending", "NFTs", "Security Auditing", "Metaplex", "Oracle Integration"],
    weeks: phase6Weeks,
    status: "locked",
  },
  {
    id: 7,
    name: "10 Solana Projects",
    shortName: "Projects",
    duration: "1 month",
    totalWeeks: 4,
    description: "Build 10 real Solana projects: DEX, staking, DAO, escrow, lending, lottery, bridge, and ZK+Solana. Each deployed to devnet.",
    goal: "Complete 10 shipped Solana projects that demonstrate full-stack Web3 development ability.",
    color: "#3B82F6",
    icon: "🚀",
    skills: ["DEX", "Staking", "DAO", "NFT Marketplace", "Bridge", "ZK on Solana"],
    weeks: phase7Weeks,
    status: "locked",
  },
  {
    id: 8,
    name: "Rust Price Oracle Chain",
    shortName: "Oracle Chain",
    duration: "1 month",
    totalWeeks: 4,
    description: "Build a price oracle blockchain in pure Rust: P2P networking with libp2p, consensus (PoA), Merkle trees, and REST API.",
    goal: "Complete a working custom blockchain implementation demonstrating systems-level Rust mastery.",
    color: "#06B6D4",
    icon: "⛓️",
    skills: ["libp2p", "Consensus", "Merkle Trees", "P2P Networking", "Blockchain Architecture"],
    weeks: phase8Weeks,
    status: "locked",
  },
  {
    id: 9,
    name: "ZK Learning & Building",
    shortName: "Zero Knowledge",
    duration: "2 months",
    totalWeeks: 8,
    description: "ZK proof fundamentals through implementation: Circom circuits, Groth16, SnarkJS, zkRollup, zkDEX, Noir language, and Halo2.",
    goal: "Build and deploy a working zkRollup and zkDEX demonstrating ZK engineering competency.",
    color: "#10B981",
    icon: "🔮",
    skills: ["ZK-SNARKs", "Circom", "Groth16", "SnarkJS", "zkRollup", "Noir", "Halo2"],
    weeks: phase9Weeks,
    status: "locked",
  },
  {
    id: 10,
    name: "Certifications & Job Hunt",
    shortName: "Get Hired",
    duration: "1 month",
    totalWeeks: 4,
    description: "Complete Rust Foundation and ZK certifications, polish your portfolio, and land a remote Web3/blockchain job.",
    goal: "Land a remote Rust/Solana/ZK engineer role with $150k+ salary.",
    color: "#EC4899",
    icon: "💼",
    skills: ["Rust Foundation Cert", "ZK Cert", "Portfolio", "Technical Interviews", "Negotiation"],
    weeks: phase10Weeks,
    status: "locked",
  },
]

export function getPhaseById(id: number): Phase | undefined {
  return PHASES.find((p) => p.id === id)
}

export function getWeekByNumber(weekNumber: number): Week | undefined {
  for (const phase of PHASES) {
    const week = phase.weeks.find((w) => w.weekNumber === weekNumber)
    if (week) return week
  }
  return undefined
}

export function getAllTasks(): DailyTask[] {
  return PHASES.flatMap((p) => p.weeks.flatMap((w) => w.tasks))
}

export const PHASE_WEEK_COUNTS = [4, 4, 4, 4, 4, 8, 4, 4, 8, 4]
export const TOTAL_WEEKS = PHASE_WEEK_COUNTS.reduce((a, b) => a + b, 0) // 52
