import type { SolanaProject } from '@/types';

export const SOLANA_PROJECTS: Omit<SolanaProject, 'status' | 'startedAt' | 'completedAt' | 'deployedUrl' | 'notes' | 'githubUrl'>[] = [
  {
    id: 1,
    name: 'Token Launch with Vesting',
    description: 'Create an SPL token with a configurable vesting schedule. Token holders can claim vested tokens over time based on a cliff + linear vesting curve.',
    difficulty: 'beginner',
    estimatedDays: 3,
    skills: ['SPL Token', 'Anchor', 'PDAs', 'Token Accounts', 'Time-based Logic'],
    objectives: ['Create SPL token mint', 'Implement vesting schedule account', 'Cliff + linear vesting math', 'Claim instruction with time check'],
    anchorConcepts: ['init', 'has_one', 'Clock sysvar', 'Token CPI'],
    successCriteria: ['Token minted on devnet', 'Vesting starts after cliff date', 'Claim fails before cliff, succeeds after', 'Full test coverage'],
  },
  {
    id: 2,
    name: 'NFT Collection Mint',
    description: 'Build a complete NFT collection minting program with Metaplex metadata, royalties, and candy-machine-style mint authority.',
    difficulty: 'beginner',
    estimatedDays: 3,
    skills: ['Metaplex', 'NFT Standards', 'Metadata Account', 'Royalties', 'Master Edition'],
    objectives: ['Create collection NFT', 'Mint individual NFTs', 'Set creator royalties', 'Verify collection membership'],
    anchorConcepts: ['Metaplex CPI', 'Associated Token Account', 'Edition accounts'],
    successCriteria: ['Collection visible on devnet explorer', 'Royalties set correctly', 'Metadata IPFS link works', 'Collection verified'],
  },
  {
    id: 3,
    name: 'Simple DEX (AMM)',
    description: 'Implement an Automated Market Maker using the constant product formula (x * y = k). Users can create pools, add liquidity, and swap tokens.',
    difficulty: 'intermediate',
    estimatedDays: 3,
    skills: ['AMM', 'Liquidity Pools', 'LP Tokens', 'Swap Math', 'Price Impact'],
    objectives: ['Create trading pool for any token pair', 'Add/remove liquidity', 'Swap tokens with slippage protection', 'LP token minting/burning'],
    anchorConcepts: ['Multiple token accounts', 'CPI to token program', 'PDA authority', 'Math with u128'],
    successCriteria: ['Pool creation works', 'Swap maintains k invariant', 'LP tokens track share correctly', '0.3% fee collected'],
  },
  {
    id: 4,
    name: 'Staking Program',
    description: 'Build a token staking program where users lock tokens for a period and earn rewards proportional to stake and time.',
    difficulty: 'intermediate',
    estimatedDays: 3,
    skills: ['Staking', 'Reward Calculation', 'Lock Periods', 'APY', 'Epoch-based rewards'],
    objectives: ['Stake tokens with lock period', 'Accumulate rewards per second', 'Claim rewards without unstaking', 'Unstake after lock expires'],
    anchorConcepts: ['Clock sysvar', 'i64 arithmetic', 'Escrow pattern', 'Stake account PDA'],
    successCriteria: ['Rewards accrue correctly over time', 'Early withdrawal blocked', 'Reward rate configurable', 'Tests cover edge cases'],
  },
  {
    id: 5,
    name: 'DAO Governance',
    description: 'Build a DAO with governance token-based voting, proposal creation, quorum requirements, and on-chain proposal execution.',
    difficulty: 'intermediate',
    estimatedDays: 3,
    skills: ['Governance', 'Voting', 'Proposals', 'Quorum', 'Execution', 'Timelock'],
    objectives: ['Create governance token', 'Submit proposals', 'Vote with token weight', 'Execute passed proposals after timelock'],
    anchorConcepts: ['Voting record PDA', 'Enum state machine', 'CPI for execution', 'Account constraints'],
    successCriteria: ['Proposal lifecycle works', 'Quorum enforced', 'Double voting prevented', 'Execution only after timelock'],
  },
  {
    id: 6,
    name: 'Escrow (P2P Swap)',
    description: 'Build a trustless peer-to-peer token swap escrow. Alice deposits Token A, Bob deposits Token B, and the program executes the swap atomically.',
    difficulty: 'beginner',
    estimatedDays: 3,
    skills: ['Escrow', 'Atomic Swap', 'Token Transfer', 'Cancel Logic', 'PDA Authority'],
    objectives: ['Maker initializes escrow with desired trade', 'Taker completes swap', 'Maker can cancel and reclaim tokens', 'No partial fills'],
    anchorConcepts: ['Vault PDA', 'Token close_account', 'Maker/taker pattern'],
    successCriteria: ['Swap is atomic (all or nothing)', 'Cancel returns tokens', 'Wrong token amount rejected', 'Tests pass on devnet'],
  },
  {
    id: 7,
    name: 'Lending Protocol',
    description: 'Build a DeFi lending protocol where users deposit collateral, borrow against it, and liquidators can liquidate undercollateralized positions.',
    difficulty: 'advanced',
    estimatedDays: 3,
    skills: ['Lending', 'Collateral', 'Liquidation', 'Interest Rate Model', 'Health Factor', 'Oracle'],
    objectives: ['Deposit collateral', 'Borrow up to LTV ratio', 'Interest accrues per slot', 'Liquidate positions below health threshold'],
    anchorConcepts: ['Oracle CPI (Pyth)', 'Compound interest math', 'Liquidation bonus', 'Reserve accounts'],
    successCriteria: ['Health factor calculated correctly', 'Liquidation at correct threshold', 'Interest compounds correctly', 'Oracle price used for LTV'],
  },
  {
    id: 8,
    name: 'VRF Lottery',
    description: 'Build a provably fair on-chain lottery using Switchboard VRF (Verifiable Random Function) for tamper-proof winner selection.',
    difficulty: 'intermediate',
    estimatedDays: 3,
    skills: ['VRF', 'Randomness', 'Lottery', 'Switchboard', 'Callback Pattern'],
    objectives: ['Accept entries with SOL payment', 'Request VRF from Switchboard', 'Callback selects winner', 'Prize distribution'],
    anchorConcepts: ['Switchboard VRF CPI', 'Callback instruction', 'Entropy account', 'Lottery state machine'],
    successCriteria: ['VRF request successful', 'Winner selected fairly', 'Prize paid out', 'New lottery starts automatically'],
  },
  {
    id: 9,
    name: 'Cross-Chain Bridge (Wormhole)',
    description: 'Build a simplified token bridge using the Wormhole message passing protocol to transfer tokens between Solana and EVM chains.',
    difficulty: 'advanced',
    estimatedDays: 3,
    skills: ['Wormhole', 'Cross-chain', 'VAA', 'Guardian', 'Token Bridge', 'EVM basics'],
    objectives: ['Lock tokens on Solana', 'Emit Wormhole message', 'Verify VAA on target chain', 'Mint wrapped tokens'],
    anchorConcepts: ['Wormhole CPI', 'VAA verification', 'Emitter PDA', 'Sequence account'],
    successCriteria: ['Tokens locked on Solana', 'Wormhole message emitted', 'VAA verified', 'Test with devnet bridge'],
  },
  {
    id: 10,
    name: 'ZK + Solana Private Transfers',
    description: 'Build a private token transfer system using ZK proofs verified on Solana. Users prove they know a secret without revealing amounts or addresses.',
    difficulty: 'advanced',
    estimatedDays: 3,
    skills: ['ZK Proofs', 'Circom', 'Groth16', 'Solana ZK', 'Commitment Scheme', 'Nullifiers'],
    objectives: ['Circom circuit for transfer validity', 'Generate and verify Groth16 proof', 'Solana program verifies proof', 'Nullifier prevents double-spend'],
    anchorConcepts: ['Proof verification', 'Nullifier PDA', 'Commitment account', 'Custom verifier'],
    successCriteria: ['ZK proof generated off-chain', 'Proof verified on-chain', 'Double spend prevented', 'Amounts hidden from observers'],
  },
];

export function getSolanaProject(id: number) {
  return SOLANA_PROJECTS.find((p) => p.id === id);
}
